// vb6_di_gdiplus_image_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "gdiplus"` (Fix 076 scheme).
//
// Family: gdiplus/image   (routed by object domain, see Get-GdiplusSub)   stubs: 20
//
// Each stub reproduces C3's own generated prototype verbatim and forwards 1:1 to
// the real flat API through a function-pointer cast (gdiplus.h is C++-only, so the
// flat API is resolved by name at first use via the loader below).
//
// date: 2026-09-20
// split from vb6_di_gdiplus_stubs.c with the same router as Get-GdiplusSub.

#include <windows.h>
#include <stdint.h>
#pragma comment(lib, "gdiplus.lib")

static void* vb6_di_gdiplus_proc(const char* name) {
    static HMODULE mod = NULL;
    if (mod == NULL) { mod = LoadLibraryA("gdiplus.dll"); }
    return (mod != NULL) ? (void*)GetProcAddress(mod, name) : NULL;
}

/* GdipBitmapLockBits */
intptr_t __stdcall vb6_di_GdipBitmapLockBits(intptr_t mBitmap, void* mRect, int32_t mFlags, intptr_t mPixelFormat, void* mLockedBitmapData) {
    intptr_t (WINAPI *fn)(intptr_t, void*, int32_t, intptr_t, void*) = (intptr_t (WINAPI *)(intptr_t, void*, int32_t, intptr_t, void*))vb6_di_gdiplus_proc("GdipBitmapLockBits");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBitmap, mRect, mFlags, mPixelFormat, mLockedBitmapData);
}

/* GdipBitmapUnlockBits */
intptr_t __stdcall vb6_di_GdipBitmapUnlockBits(intptr_t mBitmap, void* mLockedBitmapData) {
    intptr_t (WINAPI *fn)(intptr_t, void*) = (intptr_t (WINAPI *)(intptr_t, void*))vb6_di_gdiplus_proc("GdipBitmapUnlockBits");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBitmap, mLockedBitmapData);
}

/* GdipCreateBitmapFromHBITMAP */
intptr_t __stdcall vb6_di_GdipCreateBitmapFromHBITMAP(intptr_t mHbm, intptr_t mhPal, int32_t* mBitmap) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateBitmapFromHBITMAP");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mHbm, mhPal, mBitmap);
}

/* GdipCreateBitmapFromScan0 */
intptr_t __stdcall vb6_di_GdipCreateBitmapFromScan0(intptr_t mWidth, intptr_t mHeight, intptr_t mStride, intptr_t mPixelFormat, intptr_t mScan0, int32_t* mBitmap) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateBitmapFromScan0");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mWidth, mHeight, mStride, mPixelFormat, mScan0, mBitmap);
}

/* GdipCreateBitmapFromStream */
intptr_t __stdcall vb6_di_GdipCreateBitmapFromStream(intptr_t pStream, int32_t* pBitmap) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateBitmapFromStream");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(pStream, pBitmap);
}

/* GdipDisposeImage */
intptr_t __stdcall vb6_di_GdipDisposeImage(intptr_t pImage) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDisposeImage");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(pImage);
}

/* GdipDrawImageRectRectI */
intptr_t __stdcall vb6_di_GdipDrawImageRectRectI(intptr_t hGraphics, intptr_t hImage, intptr_t DstX, intptr_t DstY, intptr_t DstWidth, intptr_t DstHeight, intptr_t SrcX, intptr_t SrcY, intptr_t SrcWidth, intptr_t SrcHeight, intptr_t srcUnit, intptr_t imageAttributes, intptr_t Callback, intptr_t callbackData) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawImageRectRectI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(hGraphics, hImage, DstX, DstY, DstWidth, DstHeight, SrcX, SrcY, SrcWidth, SrcHeight, srcUnit, imageAttributes, Callback, callbackData);
}

/* GdipGetImageGraphicsContext */
intptr_t __stdcall vb6_di_GdipGetImageGraphicsContext(intptr_t Image, int32_t* hGraphics) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipGetImageGraphicsContext");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Image, hGraphics);
}

/* GdipGetImageHeight */
intptr_t __stdcall vb6_di_GdipGetImageHeight(intptr_t mImage, int32_t* mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipGetImageHeight");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mImage, mHeight);
}

/* GdipGetImageWidth */
intptr_t __stdcall vb6_di_GdipGetImageWidth(intptr_t mImage, int32_t* mWidth) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipGetImageWidth");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mImage, mWidth);
}

/* GdipCreateEffect */
intptr_t __stdcall vb6_di_GdipCreateEffect(intptr_t dwCid1, intptr_t dwCid2, intptr_t dwCid3, intptr_t dwCid4, int32_t* Effect) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateEffect");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(dwCid1, dwCid2, dwCid3, dwCid4, Effect);
}

/* GdipCreateImageAttributes */
intptr_t __stdcall vb6_di_GdipCreateImageAttributes(int32_t* imageattr) {
    intptr_t (WINAPI *fn)(int32_t*) = (intptr_t (WINAPI *)(int32_t*))vb6_di_gdiplus_proc("GdipCreateImageAttributes");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(imageattr);
}

/* GdipDeleteEffect */
intptr_t __stdcall vb6_di_GdipDeleteEffect(intptr_t Effect) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeleteEffect");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Effect);
}

/* GdipDisposeImageAttributes */
intptr_t __stdcall vb6_di_GdipDisposeImageAttributes(intptr_t imageattr) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDisposeImageAttributes");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(imageattr);
}

/* GdipDrawImageFX */
intptr_t __stdcall vb6_di_GdipDrawImageFX(intptr_t graphics, intptr_t Image, void* Source, intptr_t xForm, intptr_t Effect, intptr_t imageAttributes, intptr_t srcUnit) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, void*, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawImageFX");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, Image, Source, xForm, Effect, imageAttributes, srcUnit);
}

/* GdipDrawImageRectI */
intptr_t __stdcall vb6_di_GdipDrawImageRectI(intptr_t mGraphics, intptr_t mImage, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawImageRectI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mImage, mX, mY, mWidth, mHeight);
}

/* GdipLoadImageFromStream */
intptr_t __stdcall vb6_di_GdipLoadImageFromStream(void* Stream, int32_t* Image) {
    intptr_t (WINAPI *fn)(void*, int32_t*) = (intptr_t (WINAPI *)(void*, int32_t*))vb6_di_gdiplus_proc("GdipLoadImageFromStream");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Stream, Image);
}

/* GdipSetEffectParameters */
intptr_t __stdcall vb6_di_GdipSetEffectParameters(intptr_t Effect, void* params, intptr_t Size) {
    intptr_t (WINAPI *fn)(intptr_t, void*, intptr_t) = (intptr_t (WINAPI *)(intptr_t, void*, intptr_t))vb6_di_gdiplus_proc("GdipSetEffectParameters");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Effect, params, Size);
}

/* GdipSetImageAttributesColorMatrix */
intptr_t __stdcall vb6_di_GdipSetImageAttributesColorMatrix(intptr_t imageattr, intptr_t ColorAdjust, int16_t EnableFlag, void* MatrixColor, void* MatrixGray, intptr_t flags) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, int16_t, void*, void*, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, int16_t, void*, void*, intptr_t))vb6_di_gdiplus_proc("GdipSetImageAttributesColorMatrix");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(imageattr, ColorAdjust, EnableFlag, MatrixColor, MatrixGray, flags);
}

/* GdipImageRotateFlip */
intptr_t __stdcall vb6_di_GdipImageRotateFlip(intptr_t Image, intptr_t rfType) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipImageRotateFlip");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Image, rfType);
}
