// vb6_di_gdiplus_brush_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "gdiplus"` (Fix 076 scheme).
//
// Family: gdiplus/brush   (routed by object domain, see Get-GdiplusSub)   stubs: 18
//
// Each stub reproduces C3's own generated prototype verbatim and forwards 1:1 to
// the real flat API through a function-pointer cast (gdiplus.h is C++-only, so the
// flat API is resolved by name at first use via the loader below).
//
// date: 2026-09-20
// split from vb6_di_gdiplus_stubs.c with the same router as Get-GdiplusSub.

#include <windows.h>
#include <stdint.h>
#pragma comment(lib, "gdiplus.lib")

static void* vb6_di_gdiplus_proc(const char* name) {
    static HMODULE mod = NULL;
    if (mod == NULL) { mod = LoadLibraryA("gdiplus.dll"); }
    return (mod != NULL) ? (void*)GetProcAddress(mod, name) : NULL;
}

/* GdipCreatePen1 */
intptr_t __stdcall vb6_di_GdipCreatePen1(intptr_t mColor, float mWidth, intptr_t mUnit, int32_t* mPen) {
    intptr_t (WINAPI *fn)(intptr_t, float, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, float, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreatePen1");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mColor, mWidth, mUnit, mPen);
}

/* GdipCreateSolidFill */
intptr_t __stdcall vb6_di_GdipCreateSolidFill(intptr_t argb, int32_t* Brush) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateSolidFill");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(argb, Brush);
}

/* GdipDeleteBrush */
intptr_t __stdcall vb6_di_GdipDeleteBrush(intptr_t Brush) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeleteBrush");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Brush);
}

/* GdipDeletePen */
intptr_t __stdcall vb6_di_GdipDeletePen(intptr_t mPen) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeletePen");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPen);
}

/* GdipCreateLineBrushFromRectWithAngleI */
intptr_t __stdcall vb6_di_GdipCreateLineBrushFromRectWithAngleI(void* mRect, intptr_t mColor1, intptr_t mColor2, float mAngle, intptr_t mIsAngleScalable, int32_t mWrapMode, int32_t* mLineGradient) {
    intptr_t (WINAPI *fn)(void*, intptr_t, intptr_t, float, intptr_t, int32_t, int32_t*) = (intptr_t (WINAPI *)(void*, intptr_t, intptr_t, float, intptr_t, int32_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateLineBrushFromRectWithAngleI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mRect, mColor1, mColor2, mAngle, mIsAngleScalable, mWrapMode, mLineGradient);
}

/* GdipCreatePathGradientFromPath */
intptr_t __stdcall vb6_di_GdipCreatePathGradientFromPath(intptr_t mPath, int32_t* mPolyGradient) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreatePathGradientFromPath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPath, mPolyGradient);
}

/* GdipCreatePen2 */
intptr_t __stdcall vb6_di_GdipCreatePen2(intptr_t mBrush, float mWidth, intptr_t mUnit, int32_t* mPen) {
    intptr_t (WINAPI *fn)(intptr_t, float, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, float, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreatePen2");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBrush, mWidth, mUnit, mPen);
}

/* GdipCreateTexture */
intptr_t __stdcall vb6_di_GdipCreateTexture(intptr_t mImage, intptr_t mWrapMode, int32_t* mTexture) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateTexture");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mImage, mWrapMode, mTexture);
}

/* GdipRotatePathGradientTransform */
intptr_t __stdcall vb6_di_GdipRotatePathGradientTransform(intptr_t mBrush, float mAngle, int32_t mOrder) {
    intptr_t (WINAPI *fn)(intptr_t, float, int32_t) = (intptr_t (WINAPI *)(intptr_t, float, int32_t))vb6_di_gdiplus_proc("GdipRotatePathGradientTransform");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBrush, mAngle, mOrder);
}

/* GdipSetPathGradientSurroundColorsWithCount */
intptr_t __stdcall vb6_di_GdipSetPathGradientSurroundColorsWithCount(intptr_t mBrush, int32_t* mColor, int32_t* mCount) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*, int32_t*))vb6_di_gdiplus_proc("GdipSetPathGradientSurroundColorsWithCount");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBrush, mColor, mCount);
}

/* GdipSetPenEndCap */
intptr_t __stdcall vb6_di_GdipSetPenEndCap(intptr_t mPen, int32_t mEndCap) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t) = (intptr_t (WINAPI *)(intptr_t, int32_t))vb6_di_gdiplus_proc("GdipSetPenEndCap");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPen, mEndCap);
}

/* GdipSetPenMode */
intptr_t __stdcall vb6_di_GdipSetPenMode(intptr_t mPen, int32_t mPenMode) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t) = (intptr_t (WINAPI *)(intptr_t, int32_t))vb6_di_gdiplus_proc("GdipSetPenMode");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPen, mPenMode);
}

/* GdipSetPenStartCap */
intptr_t __stdcall vb6_di_GdipSetPenStartCap(intptr_t mPen, int32_t mStartCap) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t) = (intptr_t (WINAPI *)(intptr_t, int32_t))vb6_di_gdiplus_proc("GdipSetPenStartCap");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPen, mStartCap);
}

/* GdipTranslatePathGradientTransform */
intptr_t __stdcall vb6_di_GdipTranslatePathGradientTransform(intptr_t mBrush, float mDx, float mDy, int32_t mOrder) {
    intptr_t (WINAPI *fn)(intptr_t, float, float, int32_t) = (intptr_t (WINAPI *)(intptr_t, float, float, int32_t))vb6_di_gdiplus_proc("GdipTranslatePathGradientTransform");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBrush, mDx, mDy, mOrder);
}

/* GdipSetSolidFillColor */
intptr_t __stdcall vb6_di_GdipSetSolidFillColor(intptr_t Brush, intptr_t ARGB) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetSolidFillColor");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Brush, ARGB);
}

/* GdipTranslateTextureTransform */
intptr_t __stdcall vb6_di_GdipTranslateTextureTransform(intptr_t mBrush, float mDx, float mDy, int32_t mOrder) {
    intptr_t (WINAPI *fn)(intptr_t, float, float, int32_t) = (intptr_t (WINAPI *)(intptr_t, float, float, int32_t))vb6_di_gdiplus_proc("GdipTranslateTextureTransform");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBrush, mDx, mDy, mOrder);
}

/* GdipCreateLineBrushI */
intptr_t __stdcall vb6_di_GdipCreateLineBrushI(void* mPoint1, void* mPoint2, intptr_t mColor1, intptr_t mColor2, int32_t mWrapMode, intptr_t* mLineGradient) {
    intptr_t (WINAPI *fn)(void*, void*, intptr_t, intptr_t, int32_t, intptr_t*) = (intptr_t (WINAPI *)(void*, void*, intptr_t, intptr_t, int32_t, intptr_t*))vb6_di_gdiplus_proc("GdipCreateLineBrushI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPoint1, mPoint2, mColor1, mColor2, mWrapMode, mLineGradient);
}

/* GdipCreateLineBrushFromRect */
intptr_t __stdcall vb6_di_GdipCreateLineBrushFromRect(void* rect, intptr_t color1, intptr_t color2, intptr_t Mode, intptr_t wrapMode, int32_t* lineGradient) {
    intptr_t (WINAPI *fn)(void*, intptr_t, intptr_t, intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(void*, intptr_t, intptr_t, intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateLineBrushFromRect");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(rect, color1, color2, Mode, wrapMode, lineGradient);
}
