// vb6_di_gdiplus_draw_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "gdiplus"` (Fix 076 scheme).
//
// Family: gdiplus/draw   (routed by object domain, see Get-GdiplusSub)   stubs: 35
//
// Each stub reproduces C3's own generated prototype verbatim and forwards 1:1 to
// the real flat API through a function-pointer cast (gdiplus.h is C++-only, so the
// flat API is resolved by name at first use via the loader below).
//
// date: 2026-09-20
// split from vb6_di_gdiplus_stubs.c with the same router as Get-GdiplusSub.

#include <windows.h>
#include <stdint.h>
#pragma comment(lib, "gdiplus.lib")

static void* vb6_di_gdiplus_proc(const char* name) {
    static HMODULE mod = NULL;
    if (mod == NULL) { mod = LoadLibraryA("gdiplus.dll"); }
    return (mod != NULL) ? (void*)GetProcAddress(mod, name) : NULL;
}

/* GdipCreateFromHDC */
intptr_t __stdcall vb6_di_GdipCreateFromHDC(intptr_t hdc, int32_t* hGraphics) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateFromHDC");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(hdc, hGraphics);
}

/* GdipDeleteGraphics */
intptr_t __stdcall vb6_di_GdipDeleteGraphics(intptr_t hGraphics) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeleteGraphics");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(hGraphics);
}

/* GdiplusShutdown */
void __stdcall vb6_di_GdiplusShutdown(intptr_t Token) {
    void (WINAPI *fn)(intptr_t) = (void (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdiplusShutdown");
    if (fn != NULL) { fn(Token); }
}

/* GdiplusStartup */
intptr_t __stdcall vb6_di_GdiplusStartup(int32_t* Token, void* inputBuf, intptr_t outputBuf) {
    intptr_t (WINAPI *fn)(int32_t*, void*, intptr_t) = (intptr_t (WINAPI *)(int32_t*, void*, intptr_t))vb6_di_gdiplus_proc("GdiplusStartup");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Token, inputBuf, outputBuf);
}

/* GdipResetClip */
intptr_t __stdcall vb6_di_GdipResetClip(intptr_t mGraphics) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipResetClip");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics);
}

/* GdipSetClipHrgn */
intptr_t __stdcall vb6_di_GdipSetClipHrgn(intptr_t mGraphics, intptr_t mHRgn, intptr_t mCombineMode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetClipHrgn");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mHRgn, mCombineMode);
}

/* GdipSetClipPath */
intptr_t __stdcall vb6_di_GdipSetClipPath(intptr_t mGraphics, intptr_t mpath, intptr_t mCombineMode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetClipPath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mpath, mCombineMode);
}

/* GdipSetSmoothingMode */
intptr_t __stdcall vb6_di_GdipSetSmoothingMode(intptr_t graphics, intptr_t SmoothingMd) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetSmoothingMode");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, SmoothingMd);
}

/* GdipDrawArc */
intptr_t __stdcall vb6_di_GdipDrawArc(intptr_t mGraphics, intptr_t mPen, float mX, float mY, float mWidth, float mHeight, float mStartAngle, float mSweepAngle) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float, float, float))vb6_di_gdiplus_proc("GdipDrawArc");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX, mY, mWidth, mHeight, mStartAngle, mSweepAngle);
}

/* GdipDrawLineI */
intptr_t __stdcall vb6_di_GdipDrawLineI(intptr_t mGraphics, intptr_t mPen, intptr_t mX1, intptr_t mY1, intptr_t mX2, intptr_t mY2) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawLineI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX1, mY1, mX2, mY2);
}

/* GdipDrawPolygonI */
intptr_t __stdcall vb6_di_GdipDrawPolygonI(intptr_t mGraphics, intptr_t mPen, void* mPoints, intptr_t mCount) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, void*, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t))vb6_di_gdiplus_proc("GdipDrawPolygonI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mPoints, mCount);
}

/* GdipFillPolygonI */
intptr_t __stdcall vb6_di_GdipFillPolygonI(intptr_t mGraphics, intptr_t mBrush, void* mPoints, intptr_t mCount, intptr_t mFillMode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, void*, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipFillPolygonI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mPoints, mCount, mFillMode);
}

/* GdipResetWorldTransform */
intptr_t __stdcall vb6_di_GdipResetWorldTransform(intptr_t mGraphics) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipResetWorldTransform");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics);
}

/* GdipRotateWorldTransform */
intptr_t __stdcall vb6_di_GdipRotateWorldTransform(intptr_t graphics, float Angle, intptr_t Order) {
    intptr_t (WINAPI *fn)(intptr_t, float, intptr_t) = (intptr_t (WINAPI *)(intptr_t, float, intptr_t))vb6_di_gdiplus_proc("GdipRotateWorldTransform");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, Angle, Order);
}

/* GdipSetClipRectI */
intptr_t __stdcall vb6_di_GdipSetClipRectI(intptr_t mGraphics, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight, intptr_t mCombineMode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetClipRectI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mX, mY, mWidth, mHeight, mCombineMode);
}

/* GdipTranslateWorldTransform */
intptr_t __stdcall vb6_di_GdipTranslateWorldTransform(intptr_t graphics, float dX, float dY, intptr_t Order) {
    intptr_t (WINAPI *fn)(intptr_t, float, float, intptr_t) = (intptr_t (WINAPI *)(intptr_t, float, float, intptr_t))vb6_di_gdiplus_proc("GdipTranslateWorldTransform");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, dX, dY, Order);
}

/* GdipDrawCurveI */
intptr_t __stdcall vb6_di_GdipDrawCurveI(intptr_t mGraphics, intptr_t mPen, void* mPoints, intptr_t mCount) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, void*, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t))vb6_di_gdiplus_proc("GdipDrawCurveI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mPoints, mCount);
}

/* GdipDrawEllipseI */
intptr_t __stdcall vb6_di_GdipDrawEllipseI(intptr_t mGraphics, intptr_t mPen, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawEllipseI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX, mY, mWidth, mHeight);
}

/* GdipDrawLine */
intptr_t __stdcall vb6_di_GdipDrawLine(intptr_t mGraphics, intptr_t mPen, float mX1, float mY1, float mX2, float mY2) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float))vb6_di_gdiplus_proc("GdipDrawLine");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX1, mY1, mX2, mY2);
}

/* GdipDrawLinesI */
intptr_t __stdcall vb6_di_GdipDrawLinesI(intptr_t mGraphics, intptr_t mPen, void* mPoints, intptr_t mCount) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, void*, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t))vb6_di_gdiplus_proc("GdipDrawLinesI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mPoints, mCount);
}

/* GdipDrawRectangleI */
intptr_t __stdcall vb6_di_GdipDrawRectangleI(intptr_t mGraphics, intptr_t mPen, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawRectangleI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX, mY, mWidth, mHeight);
}

/* GdipFillEllipseI */
intptr_t __stdcall vb6_di_GdipFillEllipseI(intptr_t mGraphics, intptr_t mBrush, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipFillEllipseI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mX, mY, mWidth, mHeight);
}

/* GdipFillRectangleI */
intptr_t __stdcall vb6_di_GdipFillRectangleI(intptr_t mGraphics, intptr_t mBrush, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipFillRectangleI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mX, mY, mWidth, mHeight);
}

/* GdipSetCompositingQuality */
intptr_t __stdcall vb6_di_GdipSetCompositingQuality(intptr_t mGraphics, intptr_t mCompositingQuality) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetCompositingQuality");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mCompositingQuality);
}

/* GdipDrawPie */
intptr_t __stdcall vb6_di_GdipDrawPie(intptr_t mGraphics, intptr_t mPen, float mX, float mY, float mWidth, float mHeight, float mStartAngle, float mSweepAngle) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float, float, float))vb6_di_gdiplus_proc("GdipDrawPie");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX, mY, mWidth, mHeight, mStartAngle, mSweepAngle);
}

/* GdipFillRectangle */
intptr_t __stdcall vb6_di_GdipFillRectangle(intptr_t mGraphics, intptr_t mBrush, float mX, float mY, float mWidth, float mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float))vb6_di_gdiplus_proc("GdipFillRectangle");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mX, mY, mWidth, mHeight);
}

/* GdipDrawEllipse */
intptr_t __stdcall vb6_di_GdipDrawEllipse(intptr_t mGraphics, intptr_t mPen, float mX, float mY, float mWidth, float mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float))vb6_di_gdiplus_proc("GdipDrawEllipse");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mX, mY, mWidth, mHeight);
}

/* GdipSaveGraphics */
intptr_t __stdcall vb6_di_GdipSaveGraphics(intptr_t mGraphics, int32_t* mState) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipSaveGraphics");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mState);
}

/* GdipRestoreGraphics */
intptr_t __stdcall vb6_di_GdipRestoreGraphics(intptr_t mGraphics, intptr_t mState) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipRestoreGraphics");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mState);
}

/* GdipFillClosedCurveI */
intptr_t __stdcall vb6_di_GdipFillClosedCurveI(intptr_t mGraphics, intptr_t mBrush, void* mPoints, intptr_t mCount) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, void*, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t))vb6_di_gdiplus_proc("GdipFillClosedCurveI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mPoints, mCount);
}

/* GdipFillPie */
intptr_t __stdcall vb6_di_GdipFillPie(intptr_t mGraphics, intptr_t mBrush, float mX, float mY, float mWidth, float mHeight, float mStartAngle, float mSweepAngle) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float, float, float))vb6_di_gdiplus_proc("GdipFillPie");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mX, mY, mWidth, mHeight, mStartAngle, mSweepAngle);
}

/* GdipSetTextRenderingHint */
intptr_t __stdcall vb6_di_GdipSetTextRenderingHint(intptr_t graphics, intptr_t hint) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetTextRenderingHint");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, hint);
}

/* GdipSetPixelOffsetMode */
intptr_t __stdcall vb6_di_GdipSetPixelOffsetMode(intptr_t graphics, intptr_t Mode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetPixelOffsetMode");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, Mode);
}

/* GdipFillEllipse */
intptr_t __stdcall vb6_di_GdipFillEllipse(intptr_t graphics, intptr_t brush, float X, float Y, float Width, float Height) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float))vb6_di_gdiplus_proc("GdipFillEllipse");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, brush, X, Y, Width, Height);
}

/* GdipDrawRectangle */
intptr_t __stdcall vb6_di_GdipDrawRectangle(intptr_t graphics, intptr_t pen, float X, float Y, float Width, float Height) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, float, float, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, float, float, float, float))vb6_di_gdiplus_proc("GdipDrawRectangle");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, pen, X, Y, Width, Height);
}
