#include "backend/cgen.hpp"
#include <algorithm>
#include <cctype>
#include <iostream>
#include <functional>

namespace vb6c3 {

// --- cgen_base.cpp: 辅助函数 + CodeEmitter + 构造 + generate + 类型/命名映射 ---

FrmControlType controlTypeFromName(const std::string& name) {
    static const std::unordered_map<std::string, FrmControlType> map = {
        {"commandbutton", FrmControlType::CommandButton},
        {"textbox", FrmControlType::TextBox},
        {"label", FrmControlType::Label},
        {"checkbox", FrmControlType::CheckBox},
        {"optionbutton", FrmControlType::OptionButton},
        {"listbox", FrmControlType::ListBox},
        {"combobox", FrmControlType::ComboBox},
        {"hscrollbar", FrmControlType::HScrollBar},
        {"vscrollbar", FrmControlType::VScrollBar},
        {"frame", FrmControlType::Frame},
        {"timer", FrmControlType::Timer},
        {"picturebox", FrmControlType::PictureBox},
        {"image", FrmControlType::Image},
    };
    std::string lower = name;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    auto it = map.find(lower);
    return (it != map.end()) ? it->second : FrmControlType::Unknown;
}


// ============================================================
// CodeEmitter
// ============================================================

void CodeEmitter::emitLine(const std::string& line) {
    for (int i = 0; i < indentLevel_; i++) {
        oss_ << "    ";  // 4空格缩进
    }
    oss_ << line << "\n";
}

void CodeEmitter::emit(const std::string& text) {
    oss_ << text;
}

void CodeEmitter::emitBlank() {
    oss_ << "\n";
}

// ============================================================
// CCodeGen 构造
// ============================================================

CCodeGen::CCodeGen(Diagnostics& diag, const SymbolTable& symTab,
                   const TypeSystem& typeSys, bool verbose)
    : diag_(diag), symTab_(symTab), typeSys_(typeSys), verbose_(verbose) {}

// ============================================================
// 主入口: 生成 .h + .c
// ============================================================

bool CCodeGen::generate(Module& module, const std::string& baseName,
                         const std::unordered_set<std::string>& externalModules,
                         bool isDll, const std::string& dllProgId,
                         const FrmFormDesc* frmDesc) {
    currentModule_ = &module;
    baseName_ = baseName;
    moduleName_ = baseName;  // 模块名 = 输出基名（如 "MathUtils"）
    isMultiModule_ = !externalModules.empty();  // 有外部依赖 = 多模块项目
    isClassModule_ = module.isClassModule;
    isFormModule_ = module.isFormModule;
    isDll_ = isDll;  // P6.6
    dllProgId_ = dllProgId;  // P6.6
    emittedSymbols_.clear();
    labelCounter_ = 0;
    tempCounter_ = 0;

    // P6.11: 类模块成员变量类型扫描 (用于方法体内的BSTR安全赋值)
    // 生成代码时类成员的C名格式为 m_Xxx (首字母大写), lowercase 后为 m_xxx
    classBstrMembers_.clear();
    classLongMembers_.clear();
    classDoubleMembers_.clear();
    if (isClassModule_) {
        for (auto& decl : module.declarations) {
            if (decl->kind == ASTNodeKind::VariableDecl) {
                auto& var = static_cast<VariableDecl&>(*decl);
                if (var.asType) {
                    Vb6Type vtype = resolveArrayElemType(var.asType.get());
                    // 注册 C 字段名 m_Xxx 的 lowercase: m_xxx
                    std::string mLower = "m_" + var.name;
                    std::transform(mLower.begin(), mLower.end(), mLower.begin(), ::tolower);
                    // 同时注册不带 m_ 前缀的原始名 lowercase
                    std::string oLower = var.name;
                    std::transform(oLower.begin(), oLower.end(), oLower.begin(), ::tolower);
                    if (vtype == Vb6Type::String) {
                        classBstrMembers_.insert(mLower);
                        classBstrMembers_.insert(oLower);
                    } else if (vtype == Vb6Type::Long || vtype == Vb6Type::Integer || vtype == Vb6Type::Boolean) {
                        classLongMembers_.insert(mLower);
                        classLongMembers_.insert(oLower);
                    } else if (vtype == Vb6Type::Double || vtype == Vb6Type::Single) {
                        classDoubleMembers_.insert(mLower);
                        classDoubleMembers_.insert(oLower);
                    }
                }
            }
        }
    }

    // 生成 .h 头文件
    std::string guard = "VB6CGEN_" + cIdent(baseName_) + "_H";
    for (auto& c : guard) { if (!isalnum((unsigned char)c) && c != '_') c = '_'; }  // 文件名可能含.等非标识符字符
    std::transform(guard.begin(), guard.end(), guard.begin(), ::toupper);

    h_.emitLine("// Generated by vb6c3 (C3.exe) from " + module.filename);
    h_.emitLine("#ifndef " + guard);
    h_.emitLine("#define " + guard);
    h_.emitBlank();
    h_.emitLine("#include <stdint.h>");
    h_.emitLine("#include <stddef.h>");
    h_.emitLine("#include <stdbool.h>");
    h_.emitLine("#include <wchar.h>");
    // P7: 窗体模式下windows.h必须在vb6rtl.h之前, 避免VARIANT重定义冲突
    if (module.isFormModule) {
        h_.emitLine("#include <windows.h>");
        h_.emitLine("#include \"vb6forms.h\"");
    }
    h_.emitLine("#include \"vb6rtl.h\"");
    // DEBUG: Show external modules for this module
        for (const auto& extMod : externalModules) {
        auto* extSym = symTab_.lookup(extMod);
    }
        // P8.7: 跨模块#include策略
    // - 类模块之间的#include保留在.h (相互引用需要完整类型定义)
    // - 标准模块引用类模块的#include保留在.h (类类型需要完整定义)
    // - 标准模块之间的#include移到.c (避免.h之间循环依赖)
    for (const auto& extMod : externalModules) {
        auto* extSym = symTab_.lookup(extMod);
        bool extIsClass = extSym && extSym->kind == SymbolKind::Class;
        if (extIsClass) {
            // 类模块引用其他模块 / 标准模块引用类模块 => 放.h
            h_.emitLine("#include \"" + extMod + ".h\"");
        }
        // 标准模块引用标准模块 => 放.c（见下方）
    }
    h_.emitBlank();

    // 生成 .c 源文件头
    c_.emitLine("// Generated by vb6c3 (C3.exe) from " + module.filename);
    c_.emitLine("#include \"" + baseName_ + ".h\"");
    // P6.6.3: ActiveX DLL classes with events need vb6comserver.h for vb6_FireEvent
    if (isDll_ && isClassModule_) {
        bool _hasEvts = false;
        for (auto& _d : module.declarations) {
            if (_d->kind == ASTNodeKind::EventDecl) { _hasEvts = true; break; }
        }
        if (_hasEvts) {
            c_.emitLine("#include \"vb6comserver.h\"");
        }
    }
    // P8.7: 标准模块之间的跨模块#include放在.c文件，避免.h循环依赖
    if (!isClassModule_) {
        for (const auto& extMod : externalModules) {
            auto* extSym = symTab_.lookup(extMod);
            bool extIsClass = extSym && extSym->kind == SymbolKind::Class;
            if (!extIsClass) {
                c_.emitLine("#include \"" + extMod + ".h\"");
            }
        }
    }
    c_.emitBlank();

    // === 类模块: 生成结构体定义 ===
    if (isClassModule_) {
        std::string clsStruct = "vb6_cls_" + cIdent(baseName_);
        h_.emitLine("// Class module: " + module.moduleName);

        // P6.5: 前向声明event sink结构体 (在类结构体定义之前)
        bool hasEvents = false;
        for (auto& decl : module.declarations) {
            if (decl->kind == ASTNodeKind::EventDecl) { hasEvents = true; break; }
        }
        if (hasEvents) {
            std::string sinkName = "vb6_events_" + cIdent(baseName_);
            h_.emitLine("struct " + sinkName + ";  /* P6.5: forward decl */");
        }

        h_.emitLine("typedef struct " + clsStruct + " {");
    if (isDll_) {
        h_.emitLine("    void* __comObj;  /* P6.6.3: back-ptr to COM wrapper (vb6_ComObject*) */");
    }

        // 收集模块级变量作为结构体字段
        bool hasFields = false;
        for (auto& decl : module.declarations) {
            if (decl->kind == ASTNodeKind::VariableDecl) {
                hasFields = true;
                auto& var = static_cast<VariableDecl&>(*decl);
                std::string cType = mapTypeRef(var.asType.get());
                if (var.isDynamicArray || !var.dimensions.empty()) {
                    // 数组: 存为SAFEARRAY指针
                    Vb6Type elemType = resolveArrayElemType(var.asType.get());
                    h_.emitLine("    SAFEARRAY* " + cIdent(var.name) + "; /* " +
                                TypeSystem::typeToString(elemType) + " array */");
                } else if (var.isNew) {
                    // Dim x As New ClassName → 指针字段
                    h_.emitLine("    void* " + cIdent(var.name) + "; /* As New " +
                                (var.asType ? static_cast<SimpleTypeRef*>(var.asType.get())->name : "Object") + " */");
                } else {
                    h_.emitLine("    " + cType + " " + cIdent(var.name) + ";");
                }
            }
        }
        // C不允许空结构体 → 接口类无数据成员时添加占位字段
        if (!hasFields) {
            h_.emitLine("    int _placeholder;  /* interface class: no data members */");
        }
        // P6.5: 如果类有事件声明，添加事件接收器指针字段
        if (hasEvents) {
            std::string sinkName = "vb6_events_" + cIdent(baseName_);
            h_.emitLine("    struct " + sinkName + "* events;  /* P6.5: event sink */");
        }
        h_.emitLine("} " + clsStruct + ";");
        h_.emitBlank();

        // 类工厂函数声明
        h_.emitLine(clsStruct + "* " + clsStruct + "_New(void);");
        h_.emitLine("void " + clsStruct + "_Destroy(" + clsStruct + "* me);");
        h_.emitBlank();

        // P6.4: 生成接口vtable结构体 + 包装类型 + 全局vtable实例
        if (!module.implements.empty()) {
            emitInterfaceVtable(module);
        }

        // P6.5: 生成事件接收器表 (事件源类的回调函数指针表)
        if (hasEvents) {
            emitEventSink(module);
        }
    }

    // === 第一遍: 声明 (前向声明 → .h, 定义 → .c) ===

    // 模块级声明: 枚举、类型、常量、变量、过程
    // 按类别有序输出, 确保C编译器能看到前向声明

    // 1. Enum定义 (必须最先, 因为常量可能引用枚举值)
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::EnumDecl) {
            visit(static_cast<EnumDecl&>(*decl));
        }
    }

    // 2. Type定义
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::TypeDecl) {
            visit(static_cast<TypeDecl&>(*decl));
        }
    }

    // 3. Const
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::ConstDecl) {
            visit(static_cast<ConstDecl&>(*decl));
        }
    }

    // 4. 类模块不生成模块级变量(变量已在结构体中)
    //    标准模块/窗体模块: 生成变量声明
    if (!isClassModule_) {
        for (auto& decl : module.declarations) {
            if (decl->kind == ASTNodeKind::VariableDecl) {
                visit(static_cast<VariableDecl&>(*decl));
            }
        }
    }

    // === P7: 窗体模块额外代码 ===
    // 窗体模块需要: WndProc声明、控件句柄变量、控件创建函数
    if (module.isFormModule && frmDesc) {
        emitFormFramework(*frmDesc, module);
    }

    // 5. Declare (外部函数声明)
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::DeclareDecl) {
            visit(static_cast<DeclareDecl&>(*decl));
        }
    }

    // 6. Event声明 (类模块中)
    if (isClassModule_) {
        for (auto& decl : module.declarations) {
            if (decl->kind == ASTNodeKind::EventDecl) {
                visit(static_cast<EventDecl&>(*decl));
            }
        }
    }

    // 7. 过程前向声明 → .h
    // P6.4: 接口类的方法不生成前向声明 (方法是抽象的, 由实现类提供)
    bool currentClassIsInterface = false;
    if (isClassModule_) {
        auto* clsSym = symTab_.lookupModule(module.moduleName);
        if (clsSym && clsSym->kind == SymbolKind::Class && clsSym->isInterface) {
            currentClassIsInterface = true;
        }
    }
    for (auto& decl : module.declarations) {
        if (currentClassIsInterface) continue;  // 接口类: 跳过方法声明
        if (decl->kind == ASTNodeKind::SubDecl) {
            auto& sub = static_cast<SubDecl&>(*decl);
            std::string sig = makeProcSignature(sub);
            if (sub.access == AccessLevel::Public) {
                h_.emitLine(sig + ";");
            } else {
                h_.emitLine("static " + sig + ";");
            }
        } else if (decl->kind == ASTNodeKind::FunctionDecl) {
            auto& func = static_cast<FunctionDecl&>(*decl);
            std::string sig = makeProcSignature(func);
            if (func.access == AccessLevel::Public) {
                h_.emitLine(sig + ";");
            } else {
                h_.emitLine("static " + sig + ";");
            }
        } else if (decl->kind == ASTNodeKind::PropertyDecl) {
            auto& prop = static_cast<PropertyDecl&>(*decl);
            std::string sig = makePropertySignature(prop);
            if (prop.access == AccessLevel::Public) {
                h_.emitLine(sig + ";");
            } else {
                h_.emitLine("static " + sig + ";");
            }
        }
    }

    // P6.5: 先生成事件处理器包装函数的.h声明（在#endif之前）
    // 收集wrapper函数签名，稍后在#endif之前输出到.h
    std::vector<std::string> evtWrapperSigs;
    if (!knownWithEventsVars_.empty()) {
        for (auto& [varLower, srcClassName] : knownWithEventsVars_) {
            auto* srcClsSym = symTab_.lookup(srcClassName);
            if (!srcClsSym || srcClsSym->kind != SymbolKind::Class) continue;
            for (auto& evtName : srcClsSym->eventNames) {
                std::string varName = varLower;
                auto* varSym = symTab_.lookup(varLower);
                if (varSym) varName = varSym->name;
                std::string handlerName = varName + "_" + evtName;
                auto* handlerSym = symTab_.lookup(handlerName);
                if (!handlerSym) continue;
                std::string wrapperName = "vb6_evt_wrap_" + varLower + "_" + cIdent(evtName);
                // 查找Event声明的参数
                std::vector<ParameterInfo> evtParams;
                for (auto& decl2 : module.declarations) {
                    if (decl2->kind == ASTNodeKind::SubDecl) {
                        auto& sub = static_cast<SubDecl&>(*decl2);
                        if (Symbol::toLower(sub.name) == Symbol::toLower(handlerName)) {
                            for (auto& param : sub.params) {
                                ParameterInfo pi;
                                pi.name = param->name;
                                pi.type = (param->asType && param->asType->kind == ASTNodeKind::SimpleTypeRef)
                                    ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(param->asType.get())->name)
                                    : Vb6Type::Variant;
                                if (pi.type == Vb6Type::Unknown || pi.type == Vb6Type::Empty)
                                    pi.type = Vb6Type::Variant;
                                pi.isByVal = true;
                                evtParams.push_back(pi);
                            }
                            break;
                        }
                    }
                }
                std::string sig = "void " + wrapperName + "(void* handler";
                for (auto& p : evtParams) {
                    sig += ", " + mapType(p.type) + " " + cIdent(p.name);
                }
                sig += ")";
                evtWrapperSigs.push_back(sig);
            }
        }
    }
    // 输出wrapper声明到.h（在#endif之前）
    for (auto& sig : evtWrapperSigs) {
        h_.emitLine(sig + ";");
        h_.emitBlank();
    }

    h_.emitBlank();
    h_.emitLine("#endif /* " + guard + " */");

    // === 第二遍: 过程体 → .c ===
    c_.emitBlank();
    c_.emitLine("// === 过程实现 ===");
    c_.emitBlank();

    for (auto& decl : module.declarations) {
        if (currentClassIsInterface) continue;  // P6.4: 接口类不生成方法实现体 (由实现类提供)
        if (decl->kind == ASTNodeKind::SubDecl) {
            visit(static_cast<SubDecl&>(*decl));
        } else if (decl->kind == ASTNodeKind::FunctionDecl) {
            visit(static_cast<FunctionDecl&>(*decl));
        } else if (decl->kind == ASTNodeKind::PropertyDecl) {
            visit(static_cast<PropertyDecl&>(*decl));
        }
    }

    // === 类模块: 生成工厂函数 ===
    if (isClassModule_ && !currentClassIsInterface) {  // P6.4: 接口类不生成工厂/析构函数
        emitClassFactory(module);
    }

    // === P6.5: 生成事件处理器包装函数 ===
    // 查找 WithEvents 变量，为 obj_EventName 形式的处理器生成C回调包装
    if (!knownWithEventsVars_.empty()) {
        c_.emitBlank();
        c_.emitLine("// === P6.5: Event handler wrappers ===");
        for (auto& [varLower, srcClassName] : knownWithEventsVars_) {
            auto* srcClsSym = symTab_.lookup(srcClassName);
            if (!srcClsSym || srcClsSym->kind != SymbolKind::Class) continue;

            for (auto& evtName : srcClsSym->eventNames) {
                std::string handlerName;
                // 查找原始变量名（保留大小写）
                std::string varName = varLower;
                // 从符号表查找保留大小写的变量名 (用lookup跨模块查找)
                auto* varSym = symTab_.lookup(varLower);
                if (varSym) varName = varSym->name;
                handlerName = varName + "_" + evtName;

                auto* handlerSym = symTab_.lookup(handlerName);
                if (!handlerSym) continue;

                // 生成包装函数: void vb6_evt_wrap_<var>_<evt>(void* handler, params...)
                std::string wrapperName = "vb6_evt_wrap_" + varLower + "_" + cIdent(evtName);
                std::string sinkName = "vb6_events_" + cIdent(srcClassName);

                // 查找Event声明的参数
                std::vector<ParameterInfo> evtParams;
                for (auto& decl2 : module.declarations) {
                    // 事件处理器参数与源类Event声明参数相同
                    // 从处理器Sub的参数获取
                    if (decl2->kind == ASTNodeKind::SubDecl) {
                        auto& sub = static_cast<SubDecl&>(*decl2);
                        if (Symbol::toLower(sub.name) == Symbol::toLower(handlerName)) {
                            for (auto& param : sub.params) {
                                ParameterInfo pi;
                                pi.name = param->name;
                                pi.type = (param->asType && param->asType->kind == ASTNodeKind::SimpleTypeRef)
                                    ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(param->asType.get())->name)
                                    : Vb6Type::Variant;
                                if (pi.type == Vb6Type::Unknown || pi.type == Vb6Type::Empty)
                                    pi.type = Vb6Type::Variant;
                                pi.isByVal = true;
                                evtParams.push_back(pi);
                            }
                            break;
                        }
                    }
                }

                // 构建包装函数签名
                std::string sig = "void " + wrapperName + "(void* handler";
                for (auto& p : evtParams) {
                    sig += ", " + mapType(p.type) + " " + cIdent(p.name);
                }
                sig += ")";

                // .h前向声明已在上方（#endif之前）输出，此处只生成.c实现

                // 生成.c实现
                c_.emitLine(sig + " {");
                c_.indent();
                // 调用实际的VB6处理器函数
                // 如果是类模块，处理器是 vb6_<Mod>_<HandlerName>(me, params...)
                // 如果是标准模块，处理器是 vb6_<HandlerName>(params...)
                std::string procCall = cProcName(handlerName, handlerSym->access);
                std::string callArgs = "(";
                if (isClassModule_) {
                    callArgs += classMeParam() + "/* from handler */";
                }
                for (size_t i = 0; i < evtParams.size(); i++) {
                    if (i > 0 || isClassModule_) {
                        callArgs += ", ";
                    }
                    callArgs += cIdent(evtParams[i].name);
                }
                callArgs += ");";
                c_.emitLine(procCall + callArgs);
                c_.dedent();
                c_.emitLine("}");
                c_.emitBlank();
            }
        }
    }

        // P13.23: External COM WithEvents event callback generation
        for (auto& [varLower, srcClassName] : knownWithEventsVars_) {
            auto* srcClsSym = symTab_.lookup(srcClassName);
            if (!srcClsSym || srcClsSym->kind != SymbolKind::ComClass) continue;

            for (auto& evtName : srcClsSym->eventNames) {
                std::string varName = varLower;
                auto* varSym = symTab_.lookup(varLower);
                if (varSym) varName = varSym->name;
                std::string handlerName = varName + "_" + evtName;

                auto* handlerSym = symTab_.lookup(handlerName);
                if (!handlerSym) continue;

                // Generate: void vb6_com_evt_<var>_<evt>(VARIANT* args, int argc, VARIANT* result)
                std::string wrapperName = "vb6_com_evt_" + varLower + "_" + cIdent(evtName);

                // Get event handler parameters from Sub declaration
                std::vector<ParameterInfo> evtParams;
                for (auto& decl2 : module.declarations) {
                    if (decl2->kind == ASTNodeKind::SubDecl) {
                        auto& sub = static_cast<SubDecl&>(*decl2);
                        if (Symbol::toLower(sub.name) == Symbol::toLower(handlerName)) {
                            for (auto& param : sub.params) {
                                ParameterInfo pi;
                                pi.name = param->name;
                                pi.type = (param->asType && param->asType->kind == ASTNodeKind::SimpleTypeRef)
                                    ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(param->asType.get())->name)
                                    : Vb6Type::Variant;
                                if (pi.type == Vb6Type::Unknown || pi.type == Vb6Type::Empty)
                                    pi.type = Vb6Type::Variant;
                                pi.isByVal = true;
                                evtParams.push_back(pi);
                            }
                            break;
                        }
                    }
                }

                c_.emitLine("void " + wrapperName + "(VARIANT* args, int argc, VARIANT* result) {");
                c_.indent();

                // Extract parameters from VARIANT args
                for (size_t pi = 0; pi < evtParams.size(); pi++) {
                    std::string pName = cIdent(evtParams[pi].name);
                    std::string pType = mapType(evtParams[pi].type);
                    c_.emitLine(pType + " " + pName + ";");
                    if (evtParams[pi].type == Vb6Type::String) {
                        c_.emitLine(pName + " = (args[" + std::to_string(pi) + "].vt == VT_BSTR) ? args[" + std::to_string(pi) + "].bstrVal : NULL;");
                    } else if (evtParams[pi].type == Vb6Type::Long || evtParams[pi].type == Vb6Type::Integer) {
                        c_.emitLine(pName + " = (" + pType + ")V_I4(&args[" + std::to_string(pi) + "]);");
                    } else if (evtParams[pi].type == Vb6Type::Boolean) {
                        c_.emitLine(pName + " = (args[" + std::to_string(pi) + "].vt == VT_BOOL) ? (V_I4(&args[" + std::to_string(pi) + "]) != 0) : 0;");
                    } else if (evtParams[pi].type == Vb6Type::Single || evtParams[pi].type == Vb6Type::Double) {
                        c_.emitLine(pName + " = (" + pType + ")V_R8(&args[" + std::to_string(pi) + "]);");
                    } else {
                        c_.emitLine(pName + " = args[" + std::to_string(pi) + "];");
                    }
                }

                // Call the VB6 handler function
                std::string procCall = cProcName(handlerName, handlerSym->access);
                std::string callArgs = "(";
                if (isClassModule_) {
                    callArgs += classMeParam() + "/* from com-evt */";
                }
                for (size_t i = 0; i < evtParams.size(); i++) {
                    if (i > 0 || isClassModule_) {
                        callArgs += ", ";
                    }
                    callArgs += cIdent(evtParams[i].name);
                }
                callArgs += ");";
                c_.emitLine(procCall + callArgs);

                c_.dedent();
                c_.emitLine("}");
                c_.emitBlank();
            }
        }
    // 生成入口点 (类模块不生成main; 多模块工程中仅有Sub Main的模块生成main)
    // P6.6: ActiveX DLL入口点统一由dll_entry.c生成, 不在各模块.c中生成
    if (!isClassModule_) {
        if (isDll_) {
            // P6.6: DLL模式下, 入口点由driver额外生成的dll_entry.c提供
            // 这里只生成vb6_Init/vb6_Exit的调用桩 (供dll_entry.c中的DllMain使用)
            // 不再调用emitActiveXDll()以避免符号重复定义
        } else {
            c_.emitBlank();
            c_.emitLine("// === 入口点 ===");
            bool hasMain = false;
        for (auto& decl : module.declarations) {
            if (decl->kind == ASTNodeKind::SubDecl) {
                auto& sub = static_cast<SubDecl&>(*decl);
                if (sub.name == "Main" && sub.access == AccessLevel::Public) {
                    hasMain = true;
                    break;
                }
            }
        }
        // 单模块: 允许用第一个Public Sub作为入口
        // 多模块: 只有Sub Main模块才生成main
        bool shouldGenMain = hasMain;
        if (!shouldGenMain && !isMultiModule_) {
            // 单模块模式: 无Sub Main时自动找首个Public Sub
    for (auto& decl : module.declarations) {
        if (currentClassIsInterface) continue;  // P6.4: 接口类不生成方法实现体
        if (decl->kind == ASTNodeKind::SubDecl) {
                    auto& sub = static_cast<SubDecl&>(*decl);
                    if (sub.access == AccessLevel::Public) {
                        shouldGenMain = true;
                        // P7: 窗体模块生成WinMain, 标准模块生成main
                        if (module.isFormModule && frmDesc) {
                            // 窗体模块: WinMain → 显示窗体 → 消息循环
                            std::string formName = frmDesc->formName;
                            c_.emitLine("int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrevInst, LPSTR lpCmdLine, int nCmdShow) {");
                            c_.indent();
                            c_.emitLine("(void)hPrevInst; (void)lpCmdLine; (void)nCmdShow;");
                            c_.emitLine("vb6_Init();");
                            c_.emitLine("vb6_SetAppInstance((void*)hInst);");
                            c_.emitLine("vb6_form_show_" + cIdent(formName) + "(NULL);  /* Show form modeless, NULL=hMDIClient */");
                            c_.emitLine("int ret = vb6_MessageLoop();");
                            c_.emitLine("vb6_Exit();");
                            c_.emitLine("return ret;");
                            c_.dedent();
                            c_.emitLine("}");
                        } else {
                            c_.emitLine("int main(int argc, char* argv[]) {");
                            c_.indent();
                            c_.emitLine("vb6_Init();");
                            c_.emitLine(cProcName(sub.name, sub.access) + "();");
                            c_.emitLine("vb6_Exit();");
                            c_.emitLine("return 0;");
                            c_.dedent();
                            c_.emitLine("}");
                        }
                        break;
                    }
                }
            }
        }
        if (shouldGenMain && hasMain) {
            // P7: 窗体模块生成WinMain, 标准模块生成main
            if (module.isFormModule) {
                c_.emitLine("int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrevInst, LPSTR lpCmdLine, int nCmdShow) {");
                c_.indent();
                c_.emitLine("(void)hPrevInst; (void)lpCmdLine; (void)nCmdShow;");
                c_.emitLine("vb6_Init();");
                c_.emitLine("vb6_SetAppInstance((void*)hInst);");
                c_.emitLine(cProcName("Main", AccessLevel::Public) + "();");
                c_.emitLine("int ret = vb6_MessageLoop();");
                c_.emitLine("vb6_Exit();");
                c_.emitLine("return ret;");
                c_.dedent();
                c_.emitLine("}");
            } else {
                c_.emitLine("int main(int argc, char* argv[]) {");
                c_.indent();
                c_.emitLine("vb6_Init();");
                c_.emitLine(cProcName("Main", AccessLevel::Public) + "();");
                c_.emitLine("vb6_Exit();");
                c_.emitLine("return 0;");
                c_.dedent();
                c_.emitLine("}");
            }
        } else if (!shouldGenMain) {
            if (module.isFormModule && frmDesc) {
                // P7: 空窗体也要生成WinMain, 自动显示窗体
                std::string formName = frmDesc->formName;
                c_.emitLine("int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrevInst, LPSTR lpCmdLine, int nCmdShow) {");
                c_.indent();
                c_.emitLine("(void)hPrevInst; (void)lpCmdLine; (void)nCmdShow;");
                c_.emitLine("vb6_Init();");
                c_.emitLine("vb6_SetAppInstance((void*)hInst);");
                c_.emitLine("vb6_form_show_" + cIdent(formName) + "(NULL);  /* Show form modeless, NULL=hMDIClient */");
                c_.emitLine("int ret = vb6_MessageLoop();");
                c_.emitLine("vb6_Exit();");
                c_.emitLine("return ret;");
                c_.dedent();
                c_.emitLine("}");
            } else {
                c_.emitLine("// No entry point (library module)");
            }
        }
        }  // end else (EXE mode)
    }

    // 保存生成结果
    header_ = h_.str();
    source_ = c_.str();

    // P6.3: 如果使用了COM接口类型, 在头文件中插入typedef前向声明
    // vb6_ComIface_<Name> 是不透明结构体, 仅用作类型化指针
    if (!usedComIfaceTypes_.empty() || !usedVb6IfaceTypes_.empty()) {
        std::string typedefBlock;
        if (!usedComIfaceTypes_.empty()) {
            typedefBlock += "\n// P6.3: COM接口类型前向声明 (早期绑定)\n";
            for (const auto& ifaceName : usedComIfaceTypes_) {
                typedefBlock += "typedef struct vb6_ComIface_" + ifaceName + " vb6_ComIface_" + ifaceName + ";\n";
            }
        }
        if (!usedVb6IfaceTypes_.empty()) {
            typedefBlock += "\n// P6.4: VB6接口类型前向声明 (Implements)\n";
            for (const auto& ifaceName : usedVb6IfaceTypes_) {
                typedefBlock += "typedef struct vb6_vtbl_" + ifaceName + " vb6_vtbl_" + ifaceName + ";\n";
                typedefBlock += "typedef struct vb6_iface_" + ifaceName + " vb6_iface_" + ifaceName + ";\n";
            }
        }
        // 在 #include "vb6rtl.h" 之后插入
        std::string marker = "#include \"vb6rtl.h\"";
        size_t pos = header_.find(marker);
        if (pos != std::string::npos) {
            pos = header_.find('\n', pos);  // 找到行尾
            if (pos != std::string::npos) {
                header_.insert(pos + 1, typedefBlock);
            }
        }
    }

    currentModule_ = nullptr;
    return diag_.errorCount() == 0;
}

// ============================================================
// 类型映射
// ============================================================

std::string CCodeGen::mapType(Vb6Type type) const {
    // 检查数组标志
    bool isArray = (static_cast<uint16_t>(type) & static_cast<uint16_t>(Vb6Type::Array)) != 0;
    Vb6Type baseType = isArray
        ? static_cast<Vb6Type>(static_cast<uint16_t>(type) & ~static_cast<uint16_t>(Vb6Type::Array))
        : type;

    std::string cType;
    switch (baseType) {
        case Vb6Type::Empty:    cType = "int16_t"; break;   // VB6 Empty = 0
        case Vb6Type::Null:     cType = "int16_t"; break;   // VB6 Null = 1
        case Vb6Type::Integer:  cType = "int16_t"; break;
        case Vb6Type::Long:     cType = "int32_t"; break;
        case Vb6Type::Single:   cType = "float"; break;
        case Vb6Type::Double:   cType = "double"; break;
        case Vb6Type::Currency: cType = "int64_t"; break;   // scaled integer
        case Vb6Type::Date:     cType = "double"; break;    // OLE date
        case Vb6Type::String:   cType = "BSTR"; break;      // wchar_t* wrapper
        case Vb6Type::Object:   cType = "void*"; break;     // IDispatch* → void* for now
        case Vb6Type::Error:    cType = "int32_t"; break;   // SCODE/HRESULT
        case Vb6Type::Boolean:  cType = "int16_t"; break;   // VB6: True=-1, False=0
        case Vb6Type::Variant:  cType = "vb6_VARIANT"; break;   // tagged union
        case Vb6Type::Byte:     cType = "uint8_t"; break;
        case Vb6Type::ULong:    cType = "uint32_t"; break;
        case Vb6Type::Void:     cType = "void"; break;
        case Vb6Type::Decimal:  cType = "vb6_VARIANT"; break;   // 用VARIANT兜底
        case Vb6Type::UserDefinedType: cType = "vb6_VARIANT"; break; // 占位, 后续改进
        default:                cType = "vb6_VARIANT"; break;    // 未知/安全兜底
    }

    if (isArray) {
        cType = "vb6_SafeArray1D*";  // 数组用SAFEARRAY
    }
    return cType;
}

std::string CCodeGen::mapTypeRef(ASTNode* typeRef) {
    if (!typeRef) return "vb6_VARIANT";  // 未指定类型 = Variant

    switch (typeRef->kind) {
        case ASTNodeKind::SimpleTypeRef: {
            auto& simple = static_cast<SimpleTypeRef&>(*typeRef);
            // 尝试从类型系统解析
            Vb6Type t = typeSys_.resolveTypeName(simple.name);
            if (t != Vb6Type::Unknown) {
                return mapType(t);
            }
            // 检查是否是类名 → 映射为类结构体指针
            auto* clsSym = symTab_.lookupModule(simple.name);
            if (clsSym && clsSym->kind == SymbolKind::Class) {
                // P6.4: 接口类 → vb6_iface_<Name> 包装类型 (非指针)
                if (clsSym->isInterface) {
                    usedVb6IfaceTypes_.insert(cIdent(clsSym->name));  // 收集用于前向声明
                    return "vb6_iface_" + cIdent(clsSym->name);
                }
                return "vb6_cls_" + cIdent(clsSym->name) + "*";
            }
            // P6.3: 检查是否是COM coclass/接口 → 映射为接口指针类型 (前期绑定)
            if (clsSym && (clsSym->kind == SymbolKind::ComClass || clsSym->kind == SymbolKind::ComInterface)) {
                // 生成类型化接口指针: vb6_ComIface_<InterfaceName>*
                // 运行时通过vb6_ComQI获取, vtable直接调用
                std::string ifaceName = clsSym->name;
                if (clsSym->kind == SymbolKind::ComClass && !clsSym->comDefaultIfaceName.empty()) {
                    ifaceName = clsSym->comDefaultIfaceName;
                }
                std::string cIfaceName = cIdent(ifaceName);
                usedComIfaceTypes_.insert(cIfaceName);  // 收集接口类型名用于typedef
                return "vb6_ComIface_" + cIfaceName + "*";
            }
            // 检查是否是用户定义类型 (UDT) → vb6_type_<Name>
            auto* udtSym = symTab_.lookup(simple.name);
            if (udtSym && udtSym->kind == SymbolKind::UserDefinedType) {
                return "vb6_type_" + cIdent(simple.name);
            }
            // 检查是否是枚举类型 → 基础类型int32_t (VB6枚举底层是Long)
            if (udtSym && udtSym->kind == SymbolKind::EnumType) {
                return "int32_t";
            }
            // 兜底: 可能是未知类型
            return cIdent(simple.name);
        }
        case ASTNodeKind::ArrayTypeRef:
            return "vb6_SafeArray1D*";  // SAFEARRAY指针
        case ASTNodeKind::FixedStringTypeRef:
            return "BSTR";
        default:
            return "vb6_VARIANT";
    }
}

std::string CCodeGen::defaultValue(Vb6Type type) const {
    switch (type) {
        case Vb6Type::Integer:
        case Vb6Type::Long:
        case Vb6Type::Byte:
        case Vb6Type::Boolean:
        case Vb6Type::Error:
            return "0";
        case Vb6Type::Single:
        case Vb6Type::Double:
        case Vb6Type::Date:
            return "0.0";
        case Vb6Type::Currency:
            return "0LL";
        case Vb6Type::String:
            return "vb6_BSTR_Empty()";
        case Vb6Type::Object:
            return "NULL";
        case Vb6Type::Variant:
        case Vb6Type::Empty:
        case Vb6Type::Null:
            return "vb6_VariantEmpty()";
        default:
            return "vb6_VariantEmpty()";
    }
}

// ============================================================
// 标识符命名
// ============================================================

std::string CCodeGen::cIdent(const std::string& vb6Name) const {
    // VB6标识符可能含C关键字冲突, 添加前缀
    static const std::unordered_set<std::string> cKeywords = {
        "auto", "break", "case", "char", "const", "continue", "default", "do",
        "double", "else", "enum", "extern", "float", "for", "goto", "if",
        "int", "long", "register", "return", "short", "signed", "sizeof",
        "static", "struct", "switch", "typedef", "union", "unsigned", "void",
        "volatile", "while", "bool", "true", "false", "NULL",
        // C99/C11
        "inline", "restrict", "_Bool", "_Complex", "_Imaginary",
        // MSVC扩展
        "cdecl", "stdcall", "declspec", "dllimport", "dllexport",
    };

    std::string name = vb6Name;

    // 替换VB6方括号标识符 [Name] → Name
    if (!name.empty() && name.front() == '[' && name.back() == ']') {
        name = name.substr(1, name.size() - 2);
    }

    // 如果是C关键字, 添加vb6_前缀
    std::string lower = name;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    if (cKeywords.count(lower)) {
        return "vb6_" + name;
    }

    return name;
}

std::string CCodeGen::cProcName(const std::string& procName, AccessLevel access,
                                 const std::string& sourceModule) const {
    // 跨模块函数(外部符号): vb6_<ModuleName>_<ProcName>
    if (!sourceModule.empty()) {
        return "vb6_" + cIdent(sourceModule) + "_" + cIdent(procName);
    }
    // 多模块项目本模块 Public 函数: vb6_<ModuleName>_<ProcName>
    // （Private 函数只在本模块内可见，不需要模块前缀）
    // 单模块项目: vb6_<ProcName> (保持向后兼容)
    if (isMultiModule_ && access == AccessLevel::Public && !moduleName_.empty()) {
        return "vb6_" + cIdent(moduleName_) + "_" + cIdent(procName);
    }
    return "vb6_" + cIdent(procName);
}

// ============================================================
// 表达式求值 (累加器模式: lastExpr_接收结果)
// ============================================================


} // namespace vb6c3
