#include "backend/cgen.hpp"
#include <algorithm>
#include <cctype>
#include <iostream>

namespace vb6c3 {

// ============================================================
// CodeEmitter
// ============================================================

void CodeEmitter::emitLine(const std::string& line) {
    for (int i = 0; i < indentLevel_; i++) {
        oss_ << "    ";  // 4空格缩进
    }
    oss_ << line << "\n";
}

void CodeEmitter::emit(const std::string& text) {
    oss_ << text;
}

void CodeEmitter::emitBlank() {
    oss_ << "\n";
}

// ============================================================
// CCodeGen 构造
// ============================================================

CCodeGen::CCodeGen(Diagnostics& diag, const SymbolTable& symTab,
                   const TypeSystem& typeSys, bool verbose)
    : diag_(diag), symTab_(symTab), typeSys_(typeSys), verbose_(verbose) {}

// ============================================================
// 主入口: 生成 .h + .c
// ============================================================

bool CCodeGen::generate(Module& module, const std::string& baseName,
                         const std::unordered_set<std::string>& externalModules) {
    currentModule_ = &module;
    baseName_ = baseName;
    moduleName_ = baseName;  // 模块名 = 输出基名（如 "MathUtils"）
    isMultiModule_ = !externalModules.empty();  // 有外部依赖 = 多模块项目
    emittedSymbols_.clear();
    labelCounter_ = 0;
    tempCounter_ = 0;

    // 生成 .h 头文件
    std::string guard = "VB6CGEN_" + cIdent(baseName_) + "_H";
    std::transform(guard.begin(), guard.end(), guard.begin(), ::toupper);

    h_.emitLine("// Generated by vb6c3 (c3.exe) from " + module.filename);
    h_.emitLine("#ifndef " + guard);
    h_.emitLine("#define " + guard);
    h_.emitBlank();
    h_.emitLine("#include <stdint.h>");
    h_.emitLine("#include <stddef.h>");
    h_.emitLine("#include <stdbool.h>");
    h_.emitLine("#include <wchar.h>");
    h_.emitLine("#include \"vb6rtl.h\"");
    // 跨模块 #include: 引用外部模块的头文件
    for (const auto& extMod : externalModules) {
        h_.emitLine("#include \"" + extMod + ".h\"");
    }
    h_.emitBlank();

    // 生成 .c 源文件头
    c_.emitLine("// Generated by vb6c3 (c3.exe) from " + module.filename);
    c_.emitLine("#include \"" + baseName_ + ".h\"");
    c_.emitBlank();

    // === 第一遍: 声明 (前向声明 → .h, 定义 → .c) ===

    // 模块级声明: 枚举、类型、常量、变量、过程
    // 按类别有序输出, 确保C编译器能看到前向声明

    // 1. Enum定义 (必须最先, 因为常量可能引用枚举值)
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::EnumDecl) {
            visit(static_cast<EnumDecl&>(*decl));
        }
    }

    // 2. Type定义
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::TypeDecl) {
            visit(static_cast<TypeDecl&>(*decl));
        }
    }

    // 3. Const
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::ConstDecl) {
            visit(static_cast<ConstDecl&>(*decl));
        }
    }

    // 4. 变量声明 (前向声明 → .h, 定义 → .c)
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::VariableDecl) {
            visit(static_cast<VariableDecl&>(*decl));
        }
    }

    // 5. Declare (外部函数声明)
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::DeclareDecl) {
            visit(static_cast<DeclareDecl&>(*decl));
        }
    }

    // 6. 过程前向声明 → .h
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::SubDecl) {
            auto& sub = static_cast<SubDecl&>(*decl);
            std::string sig = makeProcSignature(sub);
            if (sub.access == AccessLevel::Public) {
                h_.emitLine(sig + ";");
            } else {
                h_.emitLine("static " + sig + ";");
            }
        } else if (decl->kind == ASTNodeKind::FunctionDecl) {
            auto& func = static_cast<FunctionDecl&>(*decl);
            std::string sig = makeProcSignature(func);
            if (func.access == AccessLevel::Public) {
                h_.emitLine(sig + ";");
            } else {
                h_.emitLine("static " + sig + ";");
            }
        }
    }

    h_.emitBlank();
    h_.emitLine("#endif /* " + guard + " */");

    // === 第二遍: 过程体 → .c ===
    c_.emitBlank();
    c_.emitLine("// === 过程实现 ===");
    c_.emitBlank();

    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::SubDecl) {
            visit(static_cast<SubDecl&>(*decl));
        } else if (decl->kind == ASTNodeKind::FunctionDecl) {
            visit(static_cast<FunctionDecl&>(*decl));
        }
    }

    // 生成入口点
    c_.emitBlank();
    c_.emitLine("// === 入口点 ===");
    bool hasMain = false;
    std::string firstPublicSub;  // 备用入口：首个Public Sub
    for (auto& decl : module.declarations) {
        if (decl->kind == ASTNodeKind::SubDecl) {
            auto& sub = static_cast<SubDecl&>(*decl);
            if (sub.name == "Main" && sub.access == AccessLevel::Public) {
                hasMain = true;
            } else if (sub.access == AccessLevel::Public && firstPublicSub.empty()) {
                firstPublicSub = sub.name;
            }
        }
    }
    if (hasMain) {
        c_.emitLine("int main(int argc, char* argv[]) {");
        c_.indent();
        c_.emitLine("vb6_Init();");
        c_.emitLine(cProcName("Main", AccessLevel::Public) + "();");
        c_.emitLine("vb6_Exit();");
        c_.emitLine("return 0;");
        c_.dedent();
        c_.emitLine("}");
    } else if (!firstPublicSub.empty()) {
        // 无 Sub Main 时自动调用首个 Public Sub
        c_.emitLine("int main(int argc, char* argv[]) {");
        c_.indent();
        c_.emitLine("vb6_Init();");
        c_.emitLine(cProcName(firstPublicSub, AccessLevel::Public) + "();");
        c_.emitLine("vb6_Exit();");
        c_.emitLine("return 0;");
        c_.dedent();
        c_.emitLine("}");
    } else {
        c_.emitLine("// No Public Sub found - no entry point generated");
    }

    // 保存生成结果
    header_ = h_.str();
    source_ = c_.str();

    currentModule_ = nullptr;
    return diag_.errorCount() == 0;
}

// ============================================================
// 类型映射
// ============================================================

std::string CCodeGen::mapType(Vb6Type type) const {
    // 检查数组标志
    bool isArray = (static_cast<uint16_t>(type) & static_cast<uint16_t>(Vb6Type::Array)) != 0;
    Vb6Type baseType = isArray
        ? static_cast<Vb6Type>(static_cast<uint16_t>(type) & ~static_cast<uint16_t>(Vb6Type::Array))
        : type;

    std::string cType;
    switch (baseType) {
        case Vb6Type::Empty:    cType = "int16_t"; break;   // VB6 Empty = 0
        case Vb6Type::Null:     cType = "int16_t"; break;   // VB6 Null = 1
        case Vb6Type::Integer:  cType = "int16_t"; break;
        case Vb6Type::Long:     cType = "int32_t"; break;
        case Vb6Type::Single:   cType = "float"; break;
        case Vb6Type::Double:   cType = "double"; break;
        case Vb6Type::Currency: cType = "int64_t"; break;   // scaled integer
        case Vb6Type::Date:     cType = "double"; break;    // OLE date
        case Vb6Type::String:   cType = "BSTR"; break;      // wchar_t* wrapper
        case Vb6Type::Object:   cType = "void*"; break;     // IDispatch* → void* for now
        case Vb6Type::Error:    cType = "int32_t"; break;   // SCODE/HRESULT
        case Vb6Type::Boolean:  cType = "int16_t"; break;   // VB6: True=-1, False=0
        case Vb6Type::Variant:  cType = "VARIANT"; break;   // tagged union
        case Vb6Type::Byte:     cType = "uint8_t"; break;
        case Vb6Type::ULong:    cType = "uint32_t"; break;
        case Vb6Type::Void:     cType = "void"; break;
        case Vb6Type::Decimal:  cType = "VARIANT"; break;   // 用VARIANT兜底
        case Vb6Type::UserDefinedType: cType = "VARIANT"; break; // 占位, 后续改进
        default:                cType = "VARIANT"; break;    // 未知/安全兜底
    }

    if (isArray) {
        cType = "vb6_SafeArray1D*";  // 数组用SAFEARRAY
    }
    return cType;
}

std::string CCodeGen::mapTypeRef(ASTNode* typeRef) const {
    if (!typeRef) return "VARIANT";  // 未指定类型 = Variant

    switch (typeRef->kind) {
        case ASTNodeKind::SimpleTypeRef: {
            auto& simple = static_cast<SimpleTypeRef&>(*typeRef);
            // 尝试从类型系统解析
            Vb6Type t = typeSys_.resolveTypeName(simple.name);
            if (t != Vb6Type::Unknown) {
                return mapType(t);
            }
            // 可能是用户定义类型
            return cIdent(simple.name);
        }
        case ASTNodeKind::ArrayTypeRef:
            return "vb6_SafeArray1D*";  // SAFEARRAY指针
        case ASTNodeKind::FixedStringTypeRef:
            return "BSTR";
        default:
            return "VARIANT";
    }
}

std::string CCodeGen::defaultValue(Vb6Type type) const {
    switch (type) {
        case Vb6Type::Integer:
        case Vb6Type::Long:
        case Vb6Type::Byte:
        case Vb6Type::Boolean:
        case Vb6Type::Error:
            return "0";
        case Vb6Type::Single:
        case Vb6Type::Double:
        case Vb6Type::Date:
            return "0.0";
        case Vb6Type::Currency:
            return "0LL";
        case Vb6Type::String:
            return "vb6_BSTR_Empty()";
        case Vb6Type::Object:
            return "NULL";
        case Vb6Type::Variant:
        case Vb6Type::Empty:
        case Vb6Type::Null:
            return "vb6_VariantEmpty()";
        default:
            return "vb6_VariantEmpty()";
    }
}

// ============================================================
// 标识符命名
// ============================================================

std::string CCodeGen::cIdent(const std::string& vb6Name) const {
    // VB6标识符可能含C关键字冲突, 添加前缀
    static const std::unordered_set<std::string> cKeywords = {
        "auto", "break", "case", "char", "const", "continue", "default", "do",
        "double", "else", "enum", "extern", "float", "for", "goto", "if",
        "int", "long", "register", "return", "short", "signed", "sizeof",
        "static", "struct", "switch", "typedef", "union", "unsigned", "void",
        "volatile", "while", "bool", "true", "false", "NULL",
        // C99/C11
        "inline", "restrict", "_Bool", "_Complex", "_Imaginary",
        // MSVC扩展
        "cdecl", "stdcall", "declspec", "dllimport", "dllexport",
    };

    std::string name = vb6Name;

    // 替换VB6方括号标识符 [Name] → Name
    if (!name.empty() && name.front() == '[' && name.back() == ']') {
        name = name.substr(1, name.size() - 2);
    }

    // 如果是C关键字, 添加vb6_前缀
    std::string lower = name;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    if (cKeywords.count(lower)) {
        return "vb6_" + name;
    }

    return name;
}

std::string CCodeGen::cProcName(const std::string& procName, AccessLevel access,
                                 const std::string& sourceModule) const {
    // 跨模块函数(外部符号): vb6_<ModuleName>_<ProcName>
    if (!sourceModule.empty()) {
        return "vb6_" + cIdent(sourceModule) + "_" + cIdent(procName);
    }
    // 多模块项目本模块 Public 函数: vb6_<ModuleName>_<ProcName>
    // （Private 函数只在本模块内可见，不需要模块前缀）
    // 单模块项目: vb6_<ProcName> (保持向后兼容)
    if (isMultiModule_ && access == AccessLevel::Public && !moduleName_.empty()) {
        return "vb6_" + cIdent(moduleName_) + "_" + cIdent(procName);
    }
    return "vb6_" + cIdent(procName);
}

// ============================================================
// 表达式求值 (累加器模式: lastExpr_接收结果)
// ============================================================

void CCodeGen::emitExpr(Expr& expr) {
    switch (expr.kind) {
        case ASTNodeKind::LiteralExpr:
            visit(static_cast<LiteralExpr&>(expr)); break;
        case ASTNodeKind::IdentifierExpr:
            visit(static_cast<IdentifierExpr&>(expr)); break;
        case ASTNodeKind::BinaryExpr:
            visit(static_cast<BinaryExpr&>(expr)); break;
        case ASTNodeKind::UnaryExpr:
            visit(static_cast<UnaryExpr&>(expr)); break;
        case ASTNodeKind::MemberAccessExpr:
            visit(static_cast<MemberAccessExpr&>(expr)); break;
        case ASTNodeKind::DictionaryAccessExpr:
            visit(static_cast<DictionaryAccessExpr&>(expr)); break;
        case ASTNodeKind::IndexOrCallExpr:
            visit(static_cast<IndexOrCallExpr&>(expr)); break;
        case ASTNodeKind::NewExpr:
            visit(static_cast<NewExpr&>(expr)); break;
        case ASTNodeKind::TypeOfExpr:
            visit(static_cast<TypeOfExpr&>(expr)); break;
        case ASTNodeKind::AddressOfExpr:
            visit(static_cast<AddressOfExpr&>(expr)); break;
        case ASTNodeKind::MeExpr:
            visit(static_cast<MeExpr&>(expr)); break;
        case ASTNodeKind::WithMemberExpr:
            visit(static_cast<WithMemberExpr&>(expr)); break;
        default:
            lastExpr_ = "/* unknown expr */";
            break;
    }
}

// ============================================================
// 表达式 visit 方法
// ============================================================

void CCodeGen::visit(LiteralExpr& node) {
    switch (node.literalKind) {
        case LiteralKind::Integer:
            lastExpr_ = std::to_string(static_cast<int>(node.intValue));
            break;
        case LiteralKind::Long:
            lastExpr_ = std::to_string(node.longValue) + "L";
            break;
        case LiteralKind::Single:
            lastExpr_ = std::to_string(node.floatValue) + "f";
            break;
        case LiteralKind::Double:
        case LiteralKind::Currency:
        case LiteralKind::Decimal:
            lastExpr_ = std::to_string(node.doubleValue);
            break;
        case LiteralKind::String: {
            // VB6字符串 → C宽字符串字面量 L"..."
            // rawText包含引号, 需要strip
            std::string inner = node.rawText;
            if (inner.size() >= 2 && inner.front() == '"' && inner.back() == '"') {
                inner = inner.substr(1, inner.size() - 2);
            }
            // VB6的""转义 (双引号在字符串内) → C的\"转义
            // 同时转义反斜杠
            std::string escaped;
            escaped.reserve(inner.size() + 4);
            for (size_t j = 0; j < inner.size(); j++) {
                char ch = inner[j];
                if (ch == '"') {
                    // VB6中""表示引号内的一个", 已被lexer解码为单个"
                    escaped += "\\\"";
                } else if (ch == '\\') {
                    escaped += "\\\\";
                } else if (ch == '\n') {
                    escaped += "\\n";
                } else if (ch == '\r') {
                    escaped += "\\r";
                } else if (ch == '\t') {
                    escaped += "\\t";
                } else {
                    escaped += ch;
                }
            }
            lastExpr_ = "vb6_BSTR_FromStr(L\"" + escaped + "\")";
            break;
        }
        case LiteralKind::Boolean:
            lastExpr_ = node.boolValue ? "(-1)" : "0";  // VB6: True=-1
            break;
        case LiteralKind::Nothing:
            lastExpr_ = "NULL";
            break;
        case LiteralKind::Empty:
            lastExpr_ = "vb6_VariantEmpty()";
            break;
        case LiteralKind::Null:
            lastExpr_ = "vb6_VariantNull()";
            break;
        case LiteralKind::Date:
            lastExpr_ = std::to_string(node.doubleValue);  // OLE date as double
            break;
    }
}

void CCodeGen::visit(IdentifierExpr& node) {
    // 查找符号确定类型
    std::string cName = cIdent(node.name);

    // 内置对象特殊处理
    std::string lower = node.name;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);

    if (lower == "me") {
        lastExpr_ = "vb6_Me";
        return;
    }

    // 检查是否是当前函数名 (Function返回值赋值 = 设置返回变量)
    if (currentProc_ && lower == Symbol::toLower(currentProc_->name)
        && currentProc_->kind == SymbolKind::Function) {
        lastExpr_ = currentReturnVar_;
        return;
    }

    // 内置常量/枚举映射
    if (lower == "vbokonly")       { lastExpr_ = "0"; return; }
    if (lower == "vbcancel")       { lastExpr_ = "2"; return; }
    if (lower == "vbabortretryignore") { lastExpr_ = "2"; return; }
    if (lower == "vbyesnocancel")  { lastExpr_ = "3"; return; }
    if (lower == "vbyesno")        { lastExpr_ = "4"; return; }
    if (lower == "vbretrycancel")  { lastExpr_ = "5"; return; }
    if (lower == "vbcritical")     { lastExpr_ = "16"; return; }
    if (lower == "vbquestion")     { lastExpr_ = "32"; return; }
    if (lower == "vbexclamation")  { lastExpr_ = "48"; return; }
    if (lower == "vbinformation")  { lastExpr_ = "64"; return; }
    if (lower == "vbcrlf")         { lastExpr_ = "vb6_BSTR_FromStr(L\"\\r\\n\")"; return; }
    if (lower == "vblf")           { lastExpr_ = "vb6_BSTR_FromStr(L\"\\n\")"; return; }
    if (lower == "vbcr")           { lastExpr_ = "vb6_BSTR_FromStr(L\"\\r\")"; return; }
    if (lower == "vbtab")          { lastExpr_ = "vb6_BSTR_FromStr(L\"\\t\")"; return; }
    if (lower == "vbnewline")      { lastExpr_ = "vb6_BSTR_FromStr(L\"\\r\\n\")"; return; }
    if (lower == "vbnullstring")   { lastExpr_ = "vb6_BSTR_Empty()"; return; }
    if (lower == "vbempty")        { lastExpr_ = "vb6_VariantEmpty()"; return; }
    if (lower == "vbnothing")      { lastExpr_ = "NULL"; return; }
    if (lower == "vbtrue")         { lastExpr_ = "(-1)"; return; }
    if (lower == "vbfalse")        { lastExpr_ = "0"; return; }

    // 内置函数映射 (名称 → RTL函数名)
    static const std::unordered_map<std::string, std::string> builtinFuncs = {
        {"len",      "vb6_Len"},
        {"msgbox",   "vb6_MsgBox"},
        {"inputbox", "vb6_InputBox"},
        {"format",   "vb6_Format"},
        {"cstr",     "vb6_CStr"},
        {"cint",     "vb6_CInt"},
        {"clng",     "vb6_CLng"},
        {"cdbl",     "vb6_CDbl"},
        {"csng",     "vb6_CSng"},
        {"cbool",    "vb6_CBool"},
        {"cdate",    "vb6_CDate"},
        {"cbyt",     "vb6_CByte"},
        {"instr",    "vb6_InStr"},
        {"left",     "vb6_Left"},
        {"right",    "vb6_Right"},
        {"mid",      "vb6_Mid"},
        {"trim",     "vb6_Trim"},
        {"ltrim",    "vb6_LTrim"},
        {"rtrim",    "vb6_RTrim"},
        {"ucase",    "vb6_UCase"},
        {"lcase",    "vb6_LCase"},
        {"chr",      "vb6_Chr"},
        {"asc",      "vb6_Asc"},
        {"abs",      "vb6_Abs"},
        {"int",      "vb6_Int"},
        {"fix",      "vb6_Fix"},
        {"sgn",      "vb6_Sgn"},
        {"sqr",      "vb6_Sqr"},
        {"ubound",   "vb6_UBound"},
        {"lbound",   "vb6_LBound"},
        {"isarray",  "vb6_IsArray"},
        {"isnumeric","vb6_IsNumeric"},
        {"isnothing","vb6_IsNothing"},
        {"typeof",   "vb6_TypeOf"},
        {"typename", "vb6_TypeName"},
        {"createobject","vb6_CreateObject"},
        {"getobject","vb6_GetObject"},
        // 字符串函数 (P4新增)
        {"replace",  "vb6_Replace"},
        {"space",    "vb6_Space"},
        {"string",   "vb6_String"},   // String$函数
        {"strcomp",  "vb6_StrComp"},
        {"strreverse","vb6_StrReverse"},
        {"instrrev", "vb6_InStrRev"},
        {"val",      "vb6_Val"},
        {"str",      "vb6_Str"},
        // 数学函数 (P4新增)
        {"sin",      "vb6_Sin"},
        {"cos",      "vb6_Cos"},
        {"tan",      "vb6_Tan"},
        {"atn",      "vb6_Atn"},
        {"log",      "vb6_Log"},
        {"exp",      "vb6_Exp"},
        {"round",    "vb6_Round"},
        {"rnd",      "vb6_Rnd"},
        {"randomize","vb6_Randomize"},
        // 日期时间 (P4新增)
        {"now",      "vb6_Now"},
        {"date",     "vb6_Date"},
        {"time",     "vb6_Time"},
        {"year",     "vb6_Year"},
        {"month",    "vb6_Month"},
        {"day",      "vb6_Day"},
        {"hour",     "vb6_Hour"},
        {"minute",   "vb6_Minute"},
        {"second",   "vb6_Second"},
        // 类型转换 (P4新增)
        {"cbyte",    "vb6_CByte"},
        {"cvar",     "vb6_CVar"},
        {"hex",      "vb6_Hex"},
        {"oct",      "vb6_Oct"},
        // 类型检查 (P4新增)
        {"isnull",   "vb6_IsNull"},
        {"isempty",  "vb6_IsEmpty"},
        {"isobject", "vb6_IsObject"},
        {"isdate",   "vb6_IsDate"},
        {"iserror",  "vb6_IsError"},
        {"vartype",  "vb6_VarType"},
        // 文件I/O (P4新增)
        {"freefile", "vb6_FreeFile"},
        {"eof",      "vb6_EOF"},
        {"lof",      "vb6_LOF"},
        {"loc",      "vb6_Loc"},
        {"kill",     "vb6_Kill"},
    };

    auto it = builtinFuncs.find(lower);
    if (it != builtinFuncs.end()) {
        // 无参内置函数: VB6允许省略括号(如 Now, Date, Time)
        // 当IdentifierExpr引用这些函数时，必须生成调用(带括号)
        static const std::unordered_set<std::string> zeroArgBuiltinFuncs = {
            "now", "date", "time", "freefile"
        };
        if (zeroArgBuiltinFuncs.count(lower)) {
            lastExpr_ = it->second + "()";
        } else {
            lastExpr_ = it->second;
        }
        return;
    }

    // 用户定义的过程: 加vb6_前缀
    // 查找模块级符号
    Symbol* sym = symTab_.lookupModule(node.name);
    if (sym && (sym->kind == SymbolKind::Sub || sym->kind == SymbolKind::Function
             || sym->kind == SymbolKind::DeclareSub || sym->kind == SymbolKind::DeclareFunc)) {
        // Declare函数: 使用VB6函数名的cIdent形式 (通过#define映射到导出名)
        if (sym->kind == SymbolKind::DeclareSub || sym->kind == SymbolKind::DeclareFunc) {
            lastExpr_ = cIdent(node.name);
        } else if (sym->isExternal) {
            // 跨模块函数: 使用 vb6_<ModuleName>_<ProcName> 格式
            lastExpr_ = cProcName(node.name, sym->access, sym->sourceModule);
        } else {
            lastExpr_ = cProcName(node.name, sym->access);
        }
        return;
    }

    // 外部变量/常量: 使用 vb6_<ModuleName>_<Name> 格式
    if (sym && sym->isExternal) {
        lastExpr_ = "vb6_" + cIdent(sym->sourceModule) + "_" + cName;
        return;
    }

    lastExpr_ = cName;
}

void CCodeGen::visit(BinaryExpr& node) {
    emitExpr(*node.left);
    std::string left = std::move(lastExpr_);
    emitExpr(*node.right);
    std::string right = std::move(lastExpr_);

    // 字符串连接运算: VB6 & → vb6_BSTR_Concat
    if (node.op == BinaryOp::Concat) {
        lastExpr_ = "vb6_BSTR_Concat(" + left + ", " + right + ")";
        return;
    }

    // 幂运算: VB6 ^ → pow()
    if (node.op == BinaryOp::Pow) {
        lastExpr_ = "vb6_Pow(" + left + ", " + right + ")";
        return;
    }

    // 整除: VB6 \ → vb6_IntDiv (确保整数截断)
    if (node.op == BinaryOp::IntDiv) {
        lastExpr_ = "vb6_IntDiv(" + left + ", " + right + ")";
        return;
    }

    // 等价运算: VB6 Eqv → ~(a^b)
    if (node.op == BinaryOp::Eqv) {
        lastExpr_ = "(~(" + left + " ^ " + right + "))";
        return;
    }

    // 蕴含运算: VB6 Imp → (~a | b)
    if (node.op == BinaryOp::Imp) {
        lastExpr_ = "((~" + left + ") | " + right + ")";
        return;
    }

    // Like运算: VB6 Like → vb6_Like
    if (node.op == BinaryOp::Like) {
        lastExpr_ = "vb6_Like(" + left + ", " + right + ")";
        return;
    }

    std::string op = mapBinaryOp(node.op);

    // VB6的And/Or/Not是逻辑运算也是位运算（取决于操作数类型）
    // 简化处理: 直接映射为C位运算, VB6语义兼容
    lastExpr_ = "(" + left + " " + op + " " + right + ")";
}

void CCodeGen::visit(UnaryExpr& node) {
    emitExpr(*node.operand);
    std::string operand = std::move(lastExpr_);

    switch (node.op) {
        case UnaryOp::Negate:
            lastExpr_ = "(-" + operand + ")";
            break;
        case UnaryOp::Not:
            // VB6 Not = 位取反 (C: ~)
            lastExpr_ = "(~" + operand + ")";
            break;
    }
}

void CCodeGen::visit(MemberAccessExpr& node) {
    // 内置对象方法: Debug.Print → vb6_DebugPrint
    // 检查 object 是否是 IdentifierExpr
    if (node.object && node.object->kind == ASTNodeKind::IdentifierExpr) {
        auto& objIdent = static_cast<IdentifierExpr&>(*node.object);
        std::string objLower = objIdent.name;
        std::transform(objLower.begin(), objLower.end(), objLower.begin(), ::tolower);
        std::string memLower = node.memberName;
        std::transform(memLower.begin(), memLower.end(), memLower.begin(), ::tolower);

        if (objLower == "debug" && memLower == "print") {
            lastExpr_ = "vb6_DebugPrint";
            return;
        }
        if (objLower == "debug" && memLower == "assert") {
            lastExpr_ = "vb6_DebugAssert";
            return;
        }
    }

    // 通用成员访问
    emitExpr(*node.object);
    std::string obj = std::move(lastExpr_);
    lastExpr_ = obj + "." + cIdent(node.memberName);
}

void CCodeGen::visit(DictionaryAccessExpr& node) {
    emitExpr(*node.object);
    std::string obj = std::move(lastExpr_);
    // obj!key → 字典访问, 暂用函数调用
    lastExpr_ = "vb6_DictAccess(" + obj + ", L\"" + node.key + "\")";
}

void CCodeGen::visit(IndexOrCallExpr& node) {
    // 检测数组访问: arr(i) — callee 是 IdentifierExpr 且在已知数组集合中
    // VB6 不区分数组索引和函数调用, 统一为 IndexOrCallExpr
    bool isArrayAccess = false;
    std::string arrName;
    Vb6Type arrElemType = Vb6Type::Variant;

    if (node.callee && node.callee->kind == ASTNodeKind::IdentifierExpr && node.named.empty()) {
        auto& ident = static_cast<IdentifierExpr&>(*node.callee);
        std::string lower = ident.name;
        std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);

        // 先查已知数组集合 (cgen过程中维护)
        if (knownArrays_.count(lower)) {
            isArrayAccess = true;
            arrName = cIdent(ident.name);
            arrElemType = arrayElemTypes_[lower];
        } else {
            // 再查符号表 (模块级数组)
            Symbol* sym = symTab_.lookupModule(ident.name);
            if (sym && sym->kind == SymbolKind::Variable && sym->isArray) {
                isArrayAccess = true;
                arrName = cIdent(ident.name);
                arrElemType = sym->type;
            }
        }
    }

    if (isArrayAccess) {
        // 数组元素访问: arr(i) → VB6_SA_AT(type, arr, i)
        emitExpr(*node.callee);
        std::string callee = std::move(lastExpr_);

        // 参数: 只取第一个位置参数作为索引 (一维)
        std::string index = "0";
        if (!node.positional.empty()) {
            emitExpr(*node.positional[0]);
            index = std::move(lastExpr_);
        }

        std::string elemCType = mapSaElemCType(arrElemType);
        lastExpr_ = "VB6_SA_AT(" + elemCType + ", " + arrName + ", " + index + ")";
        return;
    }

    // 函数调用路径 (原有逻辑)
    emitExpr(*node.callee);
    std::string callee = std::move(lastExpr_);

    // 如果callee已经是func()形式(无参内置函数调用如vb6_Now())，
    // 需要拆开重组为func(args)，因为IndexOrCallExpr表示带参数调用
    bool calleeIsZeroArgCall = false;
    if (callee.size() >= 2 && callee.substr(callee.size() - 2) == "()") {
        calleeIsZeroArgCall = true;
        callee = callee.substr(0, callee.size() - 2);
    }

    // 位置参数
    std::vector<std::string> args;
    for (auto& arg : node.positional) {
        emitExpr(*arg);
        args.push_back(std::move(lastExpr_));
    }

    // 命名参数暂按位置展开(TODO: 按参数名映射)
    for (auto& named : node.named) {
        emitExpr(*named.value);
        args.push_back(std::move(lastExpr_));
    }

    // 构造调用
    std::string argList;
    for (size_t i = 0; i < args.size(); i++) {
        if (i > 0) argList += ", ";
        argList += args[i];
    }

    // 特殊处理: UBound/LBound 缺省维度参数时补1
    if ((callee == "vb6_UBound" || callee == "vb6_LBound") && args.size() == 1) {
        argList += ", 1";
    }

    lastExpr_ = callee + "(" + argList + ")";
}

void CCodeGen::visit(NewExpr& node) {
    lastExpr_ = "vb6_NewObject(L\"" + node.className + "\")";
}

void CCodeGen::visit(TypeOfExpr& node) {
    emitExpr(*node.object);
    std::string obj = std::move(lastExpr_);
    lastExpr_ = "vb6_TypeOf(" + obj + ", L\"" + node.typeName + "\")";
}

void CCodeGen::visit(AddressOfExpr& node) {
    lastExpr_ = "(void*)" + cProcName(node.funcName, AccessLevel::Private);
}

void CCodeGen::visit(MeExpr& node) {
    lastExpr_ = "vb6_Me";
}

void CCodeGen::visit(WithMemberExpr& node) {
    // With块内的 .Member
    if (!withObjectVars_.empty()) {
        lastExpr_ = withObjectVars_.back() + "." + cIdent(node.memberName);
    } else {
        lastExpr_ = "/* .Member outside With */";
    }
}

// ============================================================
// 数组辅助方法
// ============================================================

std::string CCodeGen::mapSaElemType(Vb6Type type) const {
    switch (type) {
        case Vb6Type::Boolean:  return "vb6_sa_bool";
        case Vb6Type::Byte:     return "vb6_sa_byte";
        case Vb6Type::Integer:  return "vb6_sa_int";
        case Vb6Type::Long:     return "vb6_sa_long";
        case Vb6Type::Single:   return "vb6_sa_single";
        case Vb6Type::Double:   return "vb6_sa_double";
        case Vb6Type::Date:     return "vb6_sa_double";
        case Vb6Type::Currency: return "vb6_sa_long";  // 简化
        case Vb6Type::String:   return "vb6_sa_bstr";
        case Vb6Type::Variant:  return "vb6_sa_variant";
        case Vb6Type::Object:   return "vb6_sa_ptr";
        default:                return "vb6_sa_variant";
    }
}

std::string CCodeGen::mapSaElemCType(Vb6Type type) const {
    switch (type) {
        case Vb6Type::Boolean:  return "int16_t";
        case Vb6Type::Byte:     return "uint8_t";
        case Vb6Type::Integer:  return "int16_t";
        case Vb6Type::Long:     return "int32_t";
        case Vb6Type::Single:   return "float";
        case Vb6Type::Double:   return "double";
        case Vb6Type::Date:     return "double";
        case Vb6Type::String:   return "BSTR";
        case Vb6Type::Variant:  return "VARIANT";
        case Vb6Type::Object:   return "void*";
        default:                return "VARIANT";
    }
}

Vb6Type CCodeGen::resolveArrayElemType(ASTNode* typeRef) const {
    if (!typeRef) return Vb6Type::Variant;
    if (typeRef->kind == ASTNodeKind::ArrayTypeRef) {
        auto& arrType = static_cast<ArrayTypeRef&>(*typeRef);
        return resolveArrayElemType(arrType.elementType.get());
    }
    if (typeRef->kind == ASTNodeKind::SimpleTypeRef) {
        auto& simple = static_cast<SimpleTypeRef&>(*typeRef);
        return typeSys_.resolveTypeName(simple.name);
    }
    return Vb6Type::Variant;
}

// ============================================================
// 二元运算符映射
// ============================================================

std::string CCodeGen::mapBinaryOp(BinaryOp op) const {
    switch (op) {
        case BinaryOp::Or:     return "|";    // VB6 Or = 位或
        case BinaryOp::Xor:    return "^";    // VB6 Xor = 位异或
        case BinaryOp::And:    return "&";    // VB6 And = 位与
        case BinaryOp::Eq:     return "==";
        case BinaryOp::Neq:    return "!=";
        case BinaryOp::Lt:     return "<";
        case BinaryOp::Gt:     return ">";
        case BinaryOp::Le:     return "<=";
        case BinaryOp::Ge:     return ">=";
        case BinaryOp::Add:    return "+";
        case BinaryOp::Sub:    return "-";
        case BinaryOp::Mod:    return "%";
        case BinaryOp::Mul:    return "*";
        case BinaryOp::Div:    return "/";
        case BinaryOp::Is:     return "==";   // 对象引用比较
        // 以下运算符在visit(BinaryExpr&)中已特殊处理, 此处不应到达
        case BinaryOp::Concat: return "/* CONCAT */";
        case BinaryOp::IntDiv: return "/* INTDIV */";
        case BinaryOp::Pow:    return "/* POW */";
        case BinaryOp::Eqv:    return "/* EQV */";
        case BinaryOp::Imp:    return "/* IMP */";
        case BinaryOp::Like:   return "/* LIKE */";
        default:               return "/* ? */";
    }
}

// ============================================================
// 语句 visit 方法
// ============================================================

void CCodeGen::emitStmtList(StmtList& stmts) {
    for (auto& stmt : stmts) {
        if (!stmt) continue;
        switch (stmt->kind) {
            case ASTNodeKind::AssignmentStmt:  visit(static_cast<AssignmentStmt&>(*stmt)); break;
            case ASTNodeKind::SetStmt:         visit(static_cast<SetStmt&>(*stmt)); break;
            case ASTNodeKind::LetStmt:         visit(static_cast<LetStmt&>(*stmt)); break;
            case ASTNodeKind::IfStmt:          visit(static_cast<IfStmt&>(*stmt)); break;
            case ASTNodeKind::ForStmt:         visit(static_cast<ForStmt&>(*stmt)); break;
            case ASTNodeKind::ForEachStmt:     visit(static_cast<ForEachStmt&>(*stmt)); break;
            case ASTNodeKind::DoLoopStmt:      visit(static_cast<DoLoopStmt&>(*stmt)); break;
            case ASTNodeKind::WhileWendStmt:   visit(static_cast<WhileWendStmt&>(*stmt)); break;
            case ASTNodeKind::SelectCaseStmt:  visit(static_cast<SelectCaseStmt&>(*stmt)); break;
            case ASTNodeKind::WithStmt:        visit(static_cast<WithStmt&>(*stmt)); break;
            case ASTNodeKind::GoToStmt:        visit(static_cast<GoToStmt&>(*stmt)); break;
            case ASTNodeKind::OnErrorStmt:     visit(static_cast<OnErrorStmt&>(*stmt)); break;
            case ASTNodeKind::ExitStmt:        visit(static_cast<ExitStmt&>(*stmt)); break;
            case ASTNodeKind::CallStmt:        visit(static_cast<CallStmt&>(*stmt)); break;
            case ASTNodeKind::ReDimStmt:       visit(static_cast<ReDimStmt&>(*stmt)); break;
            case ASTNodeKind::EraseStmt:       visit(static_cast<EraseStmt&>(*stmt)); break;
            case ASTNodeKind::LabelStmt:       visit(static_cast<LabelStmt&>(*stmt)); break;
            case ASTNodeKind::LocalDeclStmt:   visit(static_cast<LocalDeclStmt&>(*stmt)); break;
            // 文件 I/O
            case ASTNodeKind::OpenStmt:        visit(static_cast<OpenStmt&>(*stmt)); break;
            case ASTNodeKind::CloseStmt:       visit(static_cast<CloseStmt&>(*stmt)); break;
            case ASTNodeKind::PrintStmt:       visit(static_cast<PrintStmt&>(*stmt)); break;
            case ASTNodeKind::WriteStmt:       visit(static_cast<WriteStmt&>(*stmt)); break;
            case ASTNodeKind::LineInputStmt:   visit(static_cast<LineInputStmt&>(*stmt)); break;
            case ASTNodeKind::InputStmt:       visit(static_cast<InputStmt&>(*stmt)); break;
            case ASTNodeKind::GetStmt:         visit(static_cast<GetStmt&>(*stmt)); break;
            case ASTNodeKind::PutStmt:         visit(static_cast<PutStmt&>(*stmt)); break;
            case ASTNodeKind::SeekStmt:        visit(static_cast<SeekStmt&>(*stmt)); break;
            case ASTNodeKind::LockStmt:        visit(static_cast<LockStmt&>(*stmt)); break;
            case ASTNodeKind::UnlockStmt:      visit(static_cast<UnlockStmt&>(*stmt)); break;
            case ASTNodeKind::WidthStmt:       visit(static_cast<WidthStmt&>(*stmt)); break;
            case ASTNodeKind::KillStmt:        visit(static_cast<KillStmt&>(*stmt)); break;
            case ASTNodeKind::NameStmt:        visit(static_cast<NameStmt&>(*stmt)); break;
            case ASTNodeKind::MkDirStmt:       visit(static_cast<MkDirStmt&>(*stmt)); break;
            case ASTNodeKind::RmDirStmt:       visit(static_cast<RmDirStmt&>(*stmt)); break;
            case ASTNodeKind::ChDirStmt:       visit(static_cast<ChDirStmt&>(*stmt)); break;
            case ASTNodeKind::ChDriveStmt:     visit(static_cast<ChDriveStmt&>(*stmt)); break;
            case ASTNodeKind::FileCopyStmt:    visit(static_cast<FileCopyStmt&>(*stmt)); break;
            case ASTNodeKind::EndStmt:
                c_.emitLine("vb6_End();");
                break;
            case ASTNodeKind::StopStmt:
                c_.emitLine("__debugbreak();");  // MSVC intrinsic
                break;
            case ASTNodeKind::ReturnStmt:
                if (currentProc_ && currentProc_->kind == SymbolKind::Function) {
                    c_.emitLine("return " + currentReturnVar_ + ";");
                } else {
                    c_.emitLine("return;");
                }
                break;
            // 文件I/O和杂项语句暂不处理, 后续P4阶段
            default:
                c_.emitLine("/* TODO: " + std::string(stmt->kindName()) + " */");
                break;
        }
    }
}

void CCodeGen::visit(Block& node) {
    emitStmtList(node.stmts);
}

void CCodeGen::visit(AssignmentStmt& node) {
    if (!node.target || !node.value) return;

    emitExpr(*node.target);
    std::string target = std::move(lastExpr_);
    emitExpr(*node.value);
    std::string value = std::move(lastExpr_);

    c_.emitLine(target + " = " + value + ";");
}

void CCodeGen::visit(SetStmt& node) {
    if (!node.target || !node.value) return;

    emitExpr(*node.target);
    std::string target = std::move(lastExpr_);
    emitExpr(*node.value);
    std::string value = std::move(lastExpr_);

    c_.emitLine(target + " = " + value + ";  /* Set */");
}

void CCodeGen::visit(LetStmt& node) {
    if (!node.target || !node.value) return;

    emitExpr(*node.target);
    std::string target = std::move(lastExpr_);
    emitExpr(*node.value);
    std::string value = std::move(lastExpr_);

    c_.emitLine(target + " = " + value + ";  /* Let */");
}

void CCodeGen::visit(IfStmt& node) {
    emitExpr(*node.condition);
    c_.emitLine("if (" + lastExpr_ + ") {");
    c_.indent();
    emitStmtList(node.thenBody);
    c_.dedent();

    for (auto& elseif : node.elseIfs) {
        emitExpr(*elseif->condition);
        c_.emitLine("} else if (" + lastExpr_ + ") {");
        c_.indent();
        emitStmtList(elseif->body);
        c_.dedent();
    }

    if (!node.elseBody.empty()) {
        c_.emitLine("} else {");
        c_.indent();
        emitStmtList(node.elseBody);
        c_.dedent();
    }

    c_.emitLine("}");
}

void CCodeGen::visit(ElseIfClause& node) {
    // 由IfStmt内部处理
}

void CCodeGen::visit(ForStmt& node) {
    emitExpr(*node.start);
    std::string start = std::move(lastExpr_);
    emitExpr(*node.end);
    std::string end = std::move(lastExpr_);

    std::string step = "1";
    if (node.step) {
        emitExpr(*node.step);
        step = std::move(lastExpr_);
    }

    std::string var = cIdent(node.varName);

    c_.emitLine("{");
    c_.indent();
    c_.emitLine("int32_t " + var + "_end = " + end + ";");
    c_.emitLine("int32_t " + var + "_step = " + step + ";");
    c_.emitLine(var + " = " + start + ";");
    c_.emitLine("if (" + var + "_step > 0) {");
    c_.indent();
    c_.emitLine("for (; " + var + " <= " + var + "_end; " + var + " += " + var + "_step) {");
    c_.indent();
    emitStmtList(node.body);
    c_.dedent();
    c_.emitLine("}");
    c_.dedent();
    c_.emitLine("} else {");
    c_.indent();
    c_.emitLine("for (; " + var + " >= " + var + "_end; " + var + " += " + var + "_step) {");
    c_.indent();
    emitStmtList(node.body);
    c_.dedent();
    c_.emitLine("}");
    c_.dedent();
    c_.emitLine("}");
    c_.dedent();
    c_.emitLine("}");
}

void CCodeGen::visit(ForEachStmt& node) {
    c_.emitLine("/* TODO: For Each */");
    emitStmtList(node.body);
}

void CCodeGen::visit(DoLoopStmt& node) {
    switch (node.loopKind) {
        case DoLoopKind::DoWhileLoop:
            if (node.condition) {
                emitExpr(*node.condition);
                c_.emitLine("while (" + lastExpr_ + ") {");
            } else {
                c_.emitLine("while (1) {");
            }
            c_.indent();
            emitStmtList(node.body);
            c_.dedent();
            c_.emitLine("}");
            break;

        case DoLoopKind::DoUntilLoop:
            if (node.condition) {
                emitExpr(*node.condition);
                c_.emitLine("while (!(" + lastExpr_ + ")) {");
            } else {
                c_.emitLine("while (1) {");
            }
            c_.indent();
            emitStmtList(node.body);
            c_.dedent();
            c_.emitLine("}");
            break;

        case DoLoopKind::DoLoopWhile:
            c_.emitLine("do {");
            c_.indent();
            emitStmtList(node.body);
            c_.dedent();
            if (node.condition) {
                emitExpr(*node.condition);
                c_.emitLine("} while (" + lastExpr_ + ");");
            } else {
                c_.emitLine("} while (1);");
            }
            break;

        case DoLoopKind::DoLoopUntil:
            c_.emitLine("do {");
            c_.indent();
            emitStmtList(node.body);
            c_.dedent();
            if (node.condition) {
                emitExpr(*node.condition);
                c_.emitLine("} while (!(" + lastExpr_ + "));");
            } else {
                c_.emitLine("} while (1);");
            }
            break;

        case DoLoopKind::DoLoop:
            c_.emitLine("do {");
            c_.indent();
            emitStmtList(node.body);
            c_.dedent();
            c_.emitLine("} while (1);");
            break;
    }
}

void CCodeGen::visit(WhileWendStmt& node) {
    emitExpr(*node.condition);
    c_.emitLine("while (" + lastExpr_ + ") {");
    c_.indent();
    emitStmtList(node.body);
    c_.dedent();
    c_.emitLine("}");
}

void CCodeGen::visit(SelectCaseStmt& node) {
    emitExpr(*node.testExpr);
    std::string testVar = lastExpr_;
    // 为test创建临时变量
    std::string tempVar = "_vb6_select_" + std::to_string(tempCounter_++);
    c_.emitLine("{");
    c_.indent();
    // 声明并初始化临时变量, 保存测试表达式的值
    c_.emitLine("int32_t " + tempVar + " = " + testVar + ";");
    // 简化: 用if-else if链代替switch (VB6 Select Case支持范围比较)
    bool first = true;
    for (auto& caseClause : node.cases) {
        for (auto& cv : caseClause->values) {
            std::string cond;
            if (cv.isIsClause) {
                // Case Is > 0 → _var > 0
                if (cv.value) {
                    emitExpr(*cv.value);
                    cond = tempVar + " " + lastExpr_;  // 运算符在表达式内
                }
            } else if (cv.toValue) {
                // Case 1 To 10 → _var >= 1 && _var <= 10
                emitExpr(*cv.value);
                std::string lo = std::move(lastExpr_);
                emitExpr(*cv.toValue);
                std::string hi = std::move(lastExpr_);
                cond = tempVar + " >= " + lo + " && " + tempVar + " <= " + hi;
            } else {
                emitExpr(*cv.value);
                cond = tempVar + " == " + lastExpr_;
            }

            if (first) {
                c_.emitLine("if (" + cond + ") {");
                first = false;
            } else {
                c_.emitLine("} else if (" + cond + ") {");
            }
            c_.indent();
            emitStmtList(caseClause->body);
            c_.dedent();
        }
    }

    if (!node.elseCase.empty()) {
        c_.emitLine("} else {");
        c_.indent();
        emitStmtList(node.elseCase);
        c_.dedent();
    }

    if (!first) {
        c_.emitLine("}");
    }
    c_.dedent();
    c_.emitLine("}");
}

void CCodeGen::visit(CaseClause& node) {
    // 由SelectCaseStmt内部处理
}

void CCodeGen::visit(WithStmt& node) {
    emitExpr(*node.object);
    std::string tempVar = "_vb6_with_" + std::to_string(tempCounter_++);
    c_.emitLine("{");
    c_.indent();
    c_.emitLine("void* " + tempVar + " = " + lastExpr_ + ";");
    withObjectVars_.push_back(tempVar);
    emitStmtList(node.body);
    withObjectVars_.pop_back();
    c_.dedent();
    c_.emitLine("}");
}

void CCodeGen::visit(GoToStmt& node) {
    c_.emitLine("goto vb6_label_" + cIdent(node.labelName) + ";");
}

void CCodeGen::visit(OnErrorStmt& node) {
    switch (node.errorKind) {
        case OnErrorKind::GoToLabel: {
            // On Error GoTo label
            // 生成 setjmp 保护点，错误发生时 longjmp 回来后跳转到对应标签
            // C代码:
            //   if (setjmp(vb6_error_jmp_buf) != 0) {
            //       goto vb6_label_ErrorHandler;
            //   }
            //   vb6_err_jmp_active = 1;
            c_.emitLine("if (setjmp(vb6_error_jmp_buf) != 0) {");
            c_.indent();
            c_.emitLine("goto vb6_label_" + cIdent(node.labelName) + ";");
            c_.dedent();
            c_.emitLine("}");
            c_.emitLine("vb6_err_jmp_active = 1;");
            // 需要setjmp头文件
            needSetjmp_ = true;
            break;
        }
        case OnErrorKind::ResumeNext: {
            // On Error Resume Next
            c_.emitLine("vb6_err_resume_next = 1;");
            break;
        }
        case OnErrorKind::GoToZero:
            // On Error GoTo 0: 禁用错误处理
            c_.emitLine("vb6_err_resume_next = 0;");
            c_.emitLine("vb6_err_jmp_active = 0;");
            break;
    }
}

void CCodeGen::visit(ExitStmt& node) {
    switch (node.exitKind) {
        case ExitKind::Do:
            c_.emitLine("break;");
            break;
        case ExitKind::For:
            c_.emitLine("break;");
            break;
        case ExitKind::Sub:
            c_.emitLine("return;");
            break;
        case ExitKind::Function:
            c_.emitLine("return " + currentReturnVar_ + ";");
            break;
        case ExitKind::Property:
            c_.emitLine("return;");
            break;
    }
}

void CCodeGen::visit(CallStmt& node) {
    if (node.callee) {
        // 检测 Debug.Print 调用: 特殊处理多参数输出
        if (node.callee->kind == ASTNodeKind::IndexOrCallExpr) {
            auto& call = static_cast<IndexOrCallExpr&>(*node.callee);
            if (call.callee && call.callee->kind == ASTNodeKind::MemberAccessExpr) {
                auto& member = static_cast<MemberAccessExpr&>(*call.callee);
                if (member.object && member.object->kind == ASTNodeKind::IdentifierExpr) {
                    auto& objIdent = static_cast<IdentifierExpr&>(*member.object);
                    std::string objLower = objIdent.name;
                    std::transform(objLower.begin(), objLower.end(), objLower.begin(), ::tolower);
                    std::string memLower = member.memberName;
                    std::transform(memLower.begin(), memLower.end(), memLower.begin(), ::tolower);

                    if (objLower == "debug" && memLower == "print") {
                        // Debug.Print: 逐参数输出, 最后换行
                        // 每个参数转为BSTR后用vb6_DebugWriteBSTR输出
                        if (call.positional.empty()) {
                            c_.emitLine("vb6_DebugWriteNewline();");
                        } else {
                            // 已知返回BSTR的内置函数前缀
                            static const std::vector<std::string> bstrFuncs = {
                                "vb6_BSTR_FromStr", "vb6_Left", "vb6_Right", "vb6_Mid",
                                "vb6_UCase", "vb6_LCase", "vb6_UCase_str", "vb6_LCase_str",
                                "vb6_Trim", "vb6_LTrim", "vb6_RTrim", "vb6_Chr",
                                "vb6_Str", "vb6_CStr", "vb6_Format", "vb6_Hex", "vb6_Oct",
                                "vb6_Replace", "vb6_Space", "vb6_String", "vb6_StrReverse",
                                "vb6_BSTR_Concat", "vb6_BSTR_Empty"
                            };
                            auto isBstrExpr = [&](const std::string& expr) -> bool {
                                for (auto& prefix : bstrFuncs) {
                                    if (expr.compare(0, prefix.size(), prefix) == 0) return true;
                                }
                                // vb6_BSTR_ 开头的都是 BSTR
                                if (expr.compare(0, 8, "vb6_BSTR") == 0) return true;
                                // VB6_SA_AT(BSTR, ...) 也是 BSTR
                                if (expr.find("VB6_SA_AT(BSTR,") != std::string::npos) return true;
                                // 已知BSTR变量名 (小写匹配)
                                std::string lower = expr;
                                std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
                                if (knownBstrVars_.count(lower)) return true;
                                return false;
                            };

                            for (size_t j = 0; j < call.positional.size(); j++) {
                                emitExpr(*call.positional[j]);
                                std::string val = std::move(lastExpr_);
                                if (isBstrExpr(val)) {
                                    // 已经是BSTR, 直接输出
                                    c_.emitLine("vb6_DebugWriteBSTR(" + val + ");");
                                } else {
                                    // 非BSTR, 用vb6_Str转BSTR后输出
                                    // 对于整数/布尔值直接转, 浮点数用vb6_CStr
                                    c_.emitLine("vb6_DebugWriteBSTR(vb6_Str((int32_t)(" + val + ")));");
                                }
                            }
                            c_.emitLine("vb6_DebugWriteNewline();");
                        }
                        return;
                    }
            }
        }
    }

        emitExpr(*node.callee);
        // 语句级调用: 确保表达式被求值(即使是void调用)
        c_.emitLine(lastExpr_ + ";");
    }
}

void CCodeGen::visit(ReDimStmt& node) {
    std::string cName = cIdent(node.varName);
    Vb6Type elemType = resolveArrayElemType(node.asType.get());
    std::string saElemType = mapSaElemType(elemType);

    if (node.dimensions.empty()) return;

    auto& dim = node.dimensions[0];
    std::string lBound = "0";
    std::string uBound = "0";
    if (dim.lower) {
        emitExpr(*dim.lower);
        lBound = std::move(lastExpr_);
    }
    if (dim.upper) {
        emitExpr(*dim.upper);
        uBound = std::move(lastExpr_);
    }

    if (node.preserve) {
        c_.emitLine(cName + " = vb6_SafeArrayReDimPreserve1D(" + cName + ", " + lBound + ", " + uBound + ");");
    } else {
        c_.emitLine("vb6_SafeArrayDestroy1D(" + cName + ");");
        c_.emitLine(cName + " = vb6_SafeArrayReDim1D(" + saElemType + ", " + lBound + ", " + uBound + ");");
    }
}

void CCodeGen::visit(EraseStmt& node) {
    for (auto& name : node.varNames) {
        std::string cName = cIdent(name);
        c_.emitLine("vb6_SafeArrayDestroy1D(" + cName + "); " + cName + " = NULL;");
    }
}

void CCodeGen::visit(OpenStmt& node) {
    // VB6: Open pathname For Mode [Access access] As #filenumber
    // C:   vb6_Open(pathname, mode, access, filenumber)
    emitExpr(*node.pathName);
    std::string pathName = std::move(lastExpr_);

    // OpenMode → 数值: Input=1, Output=2, Random=4, Append=8, Binary=16
    int32_t modeVal = 1;
    switch (node.mode) {
        case OpenMode::Input:   modeVal = 1; break;
        case OpenMode::Output:  modeVal = 2; break;
        case OpenMode::Random:  modeVal = 4; break;
        case OpenMode::Append:  modeVal = 8; break;
        case OpenMode::Binary:  modeVal = 16; break;
    }

    // OpenAccess → 数值: Read=1, Write=2, ReadWrite=3, Default=0
    int32_t accessVal = 0;
    switch (node.access) {
        case OpenAccess::Read:      accessVal = 1; break;
        case OpenAccess::Write:     accessVal = 2; break;
        case OpenAccess::ReadWrite: accessVal = 3; break;
        case OpenAccess::Default:   accessVal = 0; break;
    }

    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);

    c_.emitLine("vb6_Open(" + pathName + ", " + std::to_string(modeVal) + ", " +
                std::to_string(accessVal) + ", " + fnum + ");");
}

void CCodeGen::visit(CloseStmt& node) {
    if (node.fileNumbers.empty()) {
        c_.emitLine("/* Close All: TODO close all open files */");
    } else {
        for (auto& fn : node.fileNumbers) {
            emitExpr(*fn);
            c_.emitLine("vb6_Close(" + lastExpr_ + ");");
        }
    }
}

void CCodeGen::visit(PrintStmt& node) {
    // Print #fnum, expr1; expr2; ...
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);

    // BSTR表达式检测 (复用Debug.Print相同逻辑)
    static const std::vector<std::string> bstrFuncs = {
        "vb6_BSTR_FromStr", "vb6_Left", "vb6_Right", "vb6_Mid",
        "vb6_UCase", "vb6_LCase", "vb6_UCase_str", "vb6_LCase_str",
        "vb6_Trim", "vb6_LTrim", "vb6_RTrim", "vb6_Chr",
        "vb6_Str", "vb6_CStr", "vb6_Format", "vb6_Hex", "vb6_Oct",
        "vb6_Replace", "vb6_Space", "vb6_String", "vb6_StrReverse",
        "vb6_BSTR_Concat", "vb6_BSTR_Empty"
    };
    auto isBstrExpr = [&](const std::string& expr) -> bool {
        for (auto& prefix : bstrFuncs) {
            if (expr.compare(0, prefix.size(), prefix) == 0) return true;
        }
        if (expr.compare(0, 8, "vb6_BSTR") == 0) return true;
        if (expr.find("VB6_SA_AT(BSTR,") != std::string::npos) return true;
        std::string lower = expr;
        std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
        if (knownBstrVars_.count(lower)) return true;
        return false;
    };

    if (node.outputList.empty()) {
        c_.emitLine("vb6_Print(" + fnum + ", NULL);");
    } else {
        for (auto& expr : node.outputList) {
            emitExpr(*expr);
            std::string val = lastExpr_;
            if (isBstrExpr(val)) {
                // 已经是BSTR, 直接传给vb6_Print
                c_.emitLine("vb6_Print(" + fnum + ", " + val + ");");
            } else {
                // 非BSTR: 转换为BSTR后输出
                c_.emitLine("vb6_Print(" + fnum + ", vb6_Str((int32_t)(" + val + ")));");
            }
        }
    }
}

void CCodeGen::visit(WriteStmt& node) {
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);

    static const std::vector<std::string> bstrFuncs = {
        "vb6_BSTR_FromStr", "vb6_Left", "vb6_Right", "vb6_Mid",
        "vb6_UCase", "vb6_LCase", "vb6_UCase_str", "vb6_LCase_str",
        "vb6_Trim", "vb6_LTrim", "vb6_RTrim", "vb6_Chr",
        "vb6_Str", "vb6_CStr", "vb6_Format", "vb6_Hex", "vb6_Oct",
        "vb6_Replace", "vb6_Space", "vb6_String", "vb6_StrReverse",
        "vb6_BSTR_Concat", "vb6_BSTR_Empty"
    };
    auto isBstrExpr = [&](const std::string& expr) -> bool {
        for (auto& prefix : bstrFuncs) {
            if (expr.compare(0, prefix.size(), prefix) == 0) return true;
        }
        if (expr.compare(0, 8, "vb6_BSTR") == 0) return true;
        if (expr.find("VB6_SA_AT(BSTR,") != std::string::npos) return true;
        std::string lower = expr;
        std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
        if (knownBstrVars_.count(lower)) return true;
        return false;
    };

    if (node.outputList.empty()) {
        c_.emitLine("vb6_Write(" + fnum + ", NULL);");
    } else {
        for (auto& expr : node.outputList) {
            emitExpr(*expr);
            std::string val = lastExpr_;
            if (isBstrExpr(val)) {
                c_.emitLine("vb6_Write(" + fnum + ", " + val + ");");
            } else {
                c_.emitLine("vb6_Write(" + fnum + ", vb6_Str((int32_t)(" + val + ")));");
            }
        }
    }
}

void CCodeGen::visit(LineInputStmt& node) {
    // Line Input #fnum, varName
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);
    emitExpr(*node.varName);
    std::string varExpr = lastExpr_;
    c_.emitLine(varExpr + " = vb6_LineInput(" + fnum + ");");
}

void CCodeGen::visit(InputStmt& node) {
    // Input #fnum, var1, var2, ...
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);
    for (auto& var : node.varList) {
        emitExpr(*var);
        std::string varExpr = lastExpr_;
        c_.emitLine("vb6_Input(" + fnum + ", &" + varExpr + ");");
    }
}

void CCodeGen::visit(GetStmt& node) {
    // Get #fnum, [recnum], var
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);
    if (node.recordNumber) {
        emitExpr(*node.recordNumber);
        std::string recnum = lastExpr_;
        emitExpr(*node.varName);
        c_.emitLine("/* TODO: vb6_Get(" + fnum + ", " + recnum + ", &" + lastExpr_ + ") */");
    } else {
        c_.emitLine("/* TODO: Get sequential */");
    }
}

void CCodeGen::visit(PutStmt& node) {
    // Put #fnum, [recnum], var
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);
    if (node.recordNumber) {
        emitExpr(*node.recordNumber);
        std::string recnum = lastExpr_;
        emitExpr(*node.varName);
        c_.emitLine("/* TODO: vb6_Put(" + fnum + ", " + recnum + ", &" + lastExpr_ + ") */");
    } else {
        c_.emitLine("/* TODO: Put sequential */");
    }
}

void CCodeGen::visit(SeekStmt& node) {
    emitExpr(*node.fileNumber);
    std::string fnum = std::move(lastExpr_);
    emitExpr(*node.position);
    c_.emitLine("fseek(vb6_file_table[" + fnum + "], (long)" + lastExpr_ + ", SEEK_SET);");
}

void CCodeGen::visit(LockStmt& node) {
    // 简化: 文件锁在单进程场景不需要
    c_.emitLine("/* Lock: no-op in single-process */");
}

void CCodeGen::visit(UnlockStmt& node) {
    // 简化: 文件锁在单进程场景不需要
    c_.emitLine("/* Unlock: no-op in single-process */");
}

void CCodeGen::visit(WidthStmt& node) {
    c_.emitLine("/* Width: no-op */");
}

void CCodeGen::visit(KillStmt& node) {
    emitExpr(*node.pathName);
    c_.emitLine("vb6_Kill(" + lastExpr_ + ");");
}

void CCodeGen::visit(NameStmt& node) {
    emitExpr(*node.oldPath);
    std::string oldP = std::move(lastExpr_);
    emitExpr(*node.newPath);
    c_.emitLine("vb6_Name(" + oldP + ", " + lastExpr_ + ");");
}

void CCodeGen::visit(MkDirStmt& node) {
    emitExpr(*node.pathName);
    c_.emitLine("vb6_MkDir(" + lastExpr_ + ");");
}

void CCodeGen::visit(RmDirStmt& node) {
    emitExpr(*node.pathName);
    c_.emitLine("vb6_RmDir(" + lastExpr_ + ");");
}

void CCodeGen::visit(ChDirStmt& node) {
    emitExpr(*node.pathName);
    c_.emitLine("vb6_ChDir(" + lastExpr_ + ");");
}

void CCodeGen::visit(ChDriveStmt& node) {
    emitExpr(*node.drive);
    c_.emitLine("vb6_ChDrive(" + lastExpr_ + ");");
}

void CCodeGen::visit(FileCopyStmt& node) {
    emitExpr(*node.source);
    std::string src = std::move(lastExpr_);
    emitExpr(*node.destination);
    c_.emitLine("vb6_FileCopy(" + src + ", " + lastExpr_ + ");");
}

void CCodeGen::visit(LabelStmt& node) {
    c_.emitLine("vb6_label_" + cIdent(node.labelName) + ":;");
}

void CCodeGen::visit(OptionStmt& node) {
    // Option语句不影响C代码生成
}

void CCodeGen::visit(LocalDeclStmt& node) {
    if (!node.decl) return;

    switch (node.decl->kind) {
        case ASTNodeKind::VariableDecl: {
            auto& var = static_cast<VariableDecl&>(*node.decl);
            std::string cName = cIdent(var.name);

            // 局部数组声明
            if (!var.dimensions.empty()) {
                Vb6Type elemType = resolveArrayElemType(var.asType.get());
                std::string saElemType = mapSaElemType(elemType);

                auto& dim = var.dimensions[0];
                std::string lBound = "0";
                std::string uBound = "0";
                if (dim.lower) {
                    emitExpr(*dim.lower);
                    lBound = std::move(lastExpr_);
                }
                if (dim.upper) {
                    emitExpr(*dim.upper);
                    uBound = std::move(lastExpr_);
                }

                std::string initCode = "vb6_SafeArrayCreate1D(" + saElemType + ", " + lBound + ", " + uBound + ")";
                c_.emitLine("vb6_SafeArray1D* " + cName + " = " + initCode + ";");

                // 注册到已知数组集合
                std::string lower = var.name;
                std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
                knownArrays_.insert(lower);
                arrayElemTypes_[lower] = elemType;
                break;
            }

            // 动态数组声明: Dim arr() As Long → vb6_SafeArray1D* arr = NULL;
            if (var.isDynamicArray) {
                Vb6Type elemType = resolveArrayElemType(var.asType.get());
                c_.emitLine("vb6_SafeArray1D* " + cName + " = NULL;");

                // 注册到已知数组集合
                std::string lower = var.name;
                std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
                knownArrays_.insert(lower);
                arrayElemTypes_[lower] = elemType;
                break;
            }

            std::string cType = mapTypeRef(var.asType.get());

            // 记录BSTR类型变量名
            if (cType == "BSTR") {
                std::string lower = var.name;
                std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
                knownBstrVars_.insert(lower);
            }

            if (var.initializer) {
                emitExpr(*var.initializer);
                c_.emitLine(cType + " " + cName + " = " + lastExpr_ + ";");
            } else {
                c_.emitLine(cType + " " + cName + " = " + defaultValue(
                    var.asType ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(var.asType.get())->name) : Vb6Type::Variant
                ) + ";");
            }
            break;
        }
        case ASTNodeKind::ConstDecl: {
            auto& con = static_cast<ConstDecl&>(*node.decl);
            std::string cType = mapTypeRef(con.asType.get());
            std::string cName = cIdent(con.name);
            if (con.value) {
                emitExpr(*con.value);
                c_.emitLine("const " + cType + " " + cName + " = " + lastExpr_ + ";");
            }
            break;
        }
        default:
            c_.emitLine("/* TODO: LocalDeclStmt " + std::string(node.decl->kindName()) + " */");
            break;
    }
}

// ============================================================
// 声明 visit 方法
// ============================================================

void CCodeGen::visit(SubDecl& node) {
    std::string sig = makeProcSignature(node);

    if (node.access != AccessLevel::Public) {
        c_.emitLine("static " + sig + " {");
    } else {
        c_.emitLine(sig + " {");
    }

    c_.indent();

    // 查找符号获取参数信息
    auto* sym = symTab_.lookupModule(node.name);
    currentProc_ = sym;
    currentReturnVar_ = "";

    // 清空已知数组集合 (新过程)
    knownArrays_.clear();
    arrayElemTypes_.clear();
    knownBstrVars_.clear();

    // 生成过程体
    emitStmtList(node.body);

    currentProc_ = nullptr;
    c_.dedent();
    c_.emitLine("}");
    c_.emitBlank();
}

void CCodeGen::visit(FunctionDecl& node) {
    std::string sig = makeProcSignature(node);

    if (node.access != AccessLevel::Public) {
        c_.emitLine("static " + sig + " {");
    } else {
        c_.emitLine(sig + " {");
    }

    c_.indent();

    // 查找符号获取参数信息
    auto* sym = symTab_.lookupModule(node.name);
    currentProc_ = sym;

    // 清空已知数组集合 (新过程)
    knownArrays_.clear();
    arrayElemTypes_.clear();
    knownBstrVars_.clear();

    // Function返回值变量
    std::string retType = mapTypeRef(node.returnType.get());
    currentReturnVar_ = "vb6_ret_" + cIdent(node.name);
    c_.emitLine(retType + " " + currentReturnVar_ + " = " + defaultValue(
        node.returnType ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(node.returnType.get())->name) : Vb6Type::Variant
    ) + ";");

    // 生成过程体
    emitStmtList(node.body);

    // 返回值
    c_.emitLine("return " + currentReturnVar_ + ";");

    currentProc_ = nullptr;
    currentReturnVar_ = "";
    c_.dedent();
    c_.emitLine("}");
    c_.emitBlank();
}

std::string CCodeGen::makeProcSignature(SubDecl& node) {
    std::string name = cProcName(node.name, node.access);
    std::string params = makeParamList(node.params);
    return "void " + name + "(" + params + ")";
}

std::string CCodeGen::makeProcSignature(FunctionDecl& node) {
    std::string name = cProcName(node.name, node.access);
    std::string params = makeParamList(node.params);
    std::string retType = mapTypeRef(node.returnType.get());
    return retType + " " + name + "(" + params + ")";
}

std::string CCodeGen::makeParamList(std::vector<std::unique_ptr<ParameterDecl>>& params) {
    if (params.empty()) return "void";

    std::string result;
    for (size_t i = 0; i < params.size(); i++) {
        if (i > 0) result += ", ";
        auto& p = params[i];
        std::string cType = mapTypeRef(p->asType.get());
        std::string cName = cIdent(p->name);

        if (p->isByVal) {
            result += cType + " " + cName;
        } else {
            // ByRef → C指针
            result += cType + "* " + cName;
        }
    }
    return result;
}

void CCodeGen::visit(EnumDecl& node) {
    std::string enumName = cIdent(node.name);

    h_.emitLine("typedef enum vb6_enum_" + enumName + " {");
    h_.indent();

    int64_t nextVal = 0;
    for (auto& member : node.members) {
        std::string memName = enumName + "_" + cIdent(member->name);
        if (member->value) {
            // 枚举成员有显式值
            emitExpr(*member->value);
            h_.emitLine("vb6_enum_" + memName + " = " + lastExpr_ + ",");
            // 更新nextVal (简化: 不知道精确值, 重置为0自增)
            nextVal = 0;  // TODO: 从表达式求值
        } else {
            h_.emitLine("vb6_enum_" + memName + " = " + std::to_string(nextVal) + ",");
        }
        nextVal++;
    }

    h_.dedent();
    h_.emitLine("} vb6_enum_" + enumName + ";");
    h_.emitBlank();
}

void CCodeGen::visit(EnumMember& node) {
    // 由EnumDecl内部处理
}

void CCodeGen::visit(TypeDecl& node) {
    std::string typeName = cIdent(node.name);

    h_.emitLine("typedef struct vb6_type_" + typeName + " {");
    h_.indent();

    for (auto& member : node.members) {
        std::string memType = mapTypeRef(member->type.get());
        std::string memName = cIdent(member->name);
        // TODO: 固定大小数组成员
        h_.emitLine(memType + " " + memName + ";");
    }

    h_.dedent();
    h_.emitLine("} vb6_type_" + typeName + ";");
    h_.emitBlank();
}

void CCodeGen::visit(TypeMember& node) {
    // 由TypeDecl内部处理
}

void CCodeGen::visit(ConstDecl& node) {
    std::string cType = mapTypeRef(node.asType.get());
    std::string cName = cIdent(node.name);

    if (node.value) {
        emitExpr(*node.value);
        // 公共常量 → .h, 私有 → .c
        if (node.access == AccessLevel::Public) {
            h_.emitLine("#define " + cName + " (" + lastExpr_ + ")");
        } else {
            c_.emitLine("#define " + cName + " (" + lastExpr_ + ")");
        }
    }
}

void CCodeGen::visit(VariableDecl& node) {
    std::string cName = cIdent(node.name);

    // 数组声明
    if (!node.dimensions.empty()) {
        Vb6Type elemType = resolveArrayElemType(node.asType.get());
        std::string saElemType = mapSaElemType(elemType);
        std::string cType = "vb6_SafeArray1D*";

        // 前向声明 → .h
        if (node.access == AccessLevel::Public) {
            h_.emitLine("extern " + cType + " " + cName + ";");
        }

        // 数组创建代码
        // 目前只支持一维数组
        auto& dim = node.dimensions[0];
        std::string lBound = "0";
        std::string uBound = "0";
        if (dim.lower) {
            emitExpr(*dim.lower);
            lBound = std::move(lastExpr_);
        }
        if (dim.upper) {
            emitExpr(*dim.upper);
            uBound = std::move(lastExpr_);
        }

        std::string initCode = "vb6_SafeArrayCreate1D(" + saElemType + ", " + lBound + ", " + uBound + ")";
        if (node.access == AccessLevel::Public) {
            c_.emitLine(cType + " " + cName + " = " + initCode + ";");
        } else {
            c_.emitLine("static " + cType + " " + cName + " = " + initCode + ";");
        }

        // 注册到已知数组集合
        std::string lower = node.name;
        std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
        knownArrays_.insert(lower);
        arrayElemTypes_[lower] = elemType;
        return;
    }

    // 动态数组声明: Dim arr() As Long → vb6_SafeArray1D* arr = NULL;
    if (node.isDynamicArray) {
        Vb6Type elemType = resolveArrayElemType(node.asType.get());
        std::string cType = "vb6_SafeArray1D*";

        if (node.access == AccessLevel::Public) {
            h_.emitLine("extern " + cType + " " + cName + ";");
            c_.emitLine(cType + " " + cName + " = NULL;");
        } else {
            c_.emitLine("static " + cType + " " + cName + " = NULL;");
        }

        // 注册到已知数组集合
        std::string lower = node.name;
        std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
        knownArrays_.insert(lower);
        arrayElemTypes_[lower] = elemType;
        return;
    }

    std::string cType = mapTypeRef(node.asType.get());

    // 前向声明 → .h, 定义 → .c
    if (node.access == AccessLevel::Public) {
        h_.emitLine("extern " + cType + " " + cName + ";");
    }

    // 变量定义 → .c
    if (node.initializer) {
        emitExpr(*node.initializer);
        if (node.access == AccessLevel::Public) {
            c_.emitLine(cType + " " + cName + " = " + lastExpr_ + ";");
        } else {
            c_.emitLine("static " + cType + " " + cName + " = " + lastExpr_ + ";");
        }
    } else {
        if (node.access == AccessLevel::Public) {
            c_.emitLine(cType + " " + cName + " = " + defaultValue(
                node.asType ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(node.asType.get())->name) : Vb6Type::Variant
            ) + ";");
        } else {
            c_.emitLine("static " + cType + " " + cName + " = " + defaultValue(
                node.asType ? typeSys_.resolveTypeName(static_cast<SimpleTypeRef*>(node.asType.get())->name) : Vb6Type::Variant
            ) + ";");
        }
    }
}

void CCodeGen::visit(DeclareDecl& node) {
    // 外部函数声明 (Declare Sub/Function ... Lib "xxx" [Alias "yyy"] [CDecl])
    std::string retType = (node.procKind == ProcKind::Function)
        ? mapTypeRef(node.returnType.get()) : "void";

    std::string params = makeParamList(node.params);
    if (params.empty()) params = "void";

    // 调用约定
    std::string callConv = (node.callingConv == CallConv::CDecl) ? "__cdecl" : "__stdcall";

    // 去除字符串两端引号 (词法器保留引号)
    auto stripQuotes = [](const std::string& s) -> std::string {
        if (s.size() >= 2 && s.front() == '"' && s.back() == '"')
            return s.substr(1, s.size() - 2);
        return s;
    };

    // Lib名: 去引号、去.dll后缀
    std::string libName = stripQuotes(node.libName);
    if (libName.size() > 4 &&
        (libName.compare(libName.size()-4, 4, ".dll") == 0 ||
         libName.compare(libName.size()-4, 4, ".DLL") == 0)) {
        libName = libName.substr(0, libName.size()-4);
    }

    // Alias: 去引号, 保持原始导出名 (大小写敏感, 可能含#序号前缀)
    std::string aliasName = stripQuotes(node.aliasName);

    // VB6函数名→C标识符 (用于调用点)
    std::string cFuncIdent = cIdent(node.name);

    // 导出名: Alias优先, 否则用VB6函数名
    // 注意: Windows API函数名是大小写敏感的, 需要保持原始大小写
    std::string exportedName = aliasName.empty() ? node.name : aliasName;

    // 生成: #pragma comment(lib, "xxx.lib")
    c_.emitLine("#pragma comment(lib, \"" + libName + ".lib\")");

    // 生成DLL导入声明 + 名称映射
    if (exportedName != cFuncIdent) {
        // 导出名≠VB6名: 声明导出名, 用#define映射
        h_.emitLine("__declspec(dllimport) " + retType + " " + callConv + " " + exportedName + "(" + params + ");");
        h_.emitLine("#define " + cFuncIdent + " " + exportedName);
    } else {
        // 导出名=VB6名: 直接声明
        h_.emitLine("__declspec(dllimport) " + retType + " " + callConv + " " + exportedName + "(" + params + ");");
    }
}

void CCodeGen::visit(PropertyDecl& node) {
    c_.emitLine("/* TODO: Property " + node.name + " */");
}

void CCodeGen::visit(EventDecl& node) {
    c_.emitLine("/* TODO: Event " + node.name + " */");
}

void CCodeGen::visit(ParameterDecl& node) {
    // 由makeParamList内部处理
}

// ============================================================
// 类型引用 visit (代码生成中通常不用这些, mapTypeRef直接处理)
// ============================================================

void CCodeGen::visit(SimpleTypeRef& node) {}
void CCodeGen::visit(ArrayTypeRef& node) {}
void CCodeGen::visit(FixedStringTypeRef& node) {}

// ============================================================
// 模块 visit (generate()已按类别分派, 此处为空)
// ============================================================

void CCodeGen::visit(Module& node) {}

} // namespace vb6c3
