// vb6_di_shell_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "x"` (Fix 076 scheme: C3 emits
// `extern <ret> __stdcall vb6_di_<alias>(...)` and the RTL implements it).
//
// Family: shell   (libs: shell32, shlwapi, imagehlp)   stubs: 5
//
// Each stub reproduces C3's own generated prototype verbatim (that is the ABI the
// caller uses: ByVal Long is widened to intptr_t, ByVal Single stays float, ByRef
// Long stays int32_t*) and forwards 1:1 to the real API through a function-pointer
// cast. The cast keeps the compiler from complaining about unrelated API parameter
// types while preserving the register/memory passing class of every argument.
//
// generated from: C:\Users\ADMINI~1\AppData\Local\Temp\C3C\119778974291800
// date: 2026-09-21 14:08
//
// Hand-maintained special cases stay in vb6_di_stubs.c (ordinals, msvbvm60 runtime,
// dynamically loaded DLLs). Re-run the generator after a build exposes new symbols.

/* VB6 code uses the classic winsock names (gethostbyname, inet_addr, ...) */
#define _WINSOCK_DEPRECATED_NO_WARNINGS
/* winsock2.h must come before windows.h */
#include <winsock2.h>
#include <windows.h>
#include <dwmapi.h>
#undef RtlMoveMemory
#undef RtlCopyMemory
#undef RtlFillMemory
#undef RtlZeroMemory
void WINAPI RtlMoveMemory(void*, const void*, size_t);
void WINAPI RtlCopyMemory(void*, const void*, size_t);
void WINAPI RtlFillMemory(void*, size_t, unsigned char);
void WINAPI RtlZeroMemory(void*, size_t);
#include <stdint.h>
#include <string.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <mmsystem.h>
#include <dbghelp.h>
#include <iphlpapi.h>
#include <bcrypt.h>
#include <ncrypt.h>
#include <ole2.h>
#include <oleauto.h>
#include <olectl.h>
/* NOTE: gdiplus.h is C++-only (class Gdiplus...). The GDI+ flat API is
 * resolved with GetProcAddress instead - see below. */

/* Import libs for the DLLs below. Adding one that is not needed is harmless:
 * a static import lib is only pulled when a symbol from it is referenced. */
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "shlwapi.lib")
#pragma comment(lib, "imagehlp.lib")
#pragma comment(lib, "comdlg32.lib")

/* PathGetArgsW */
intptr_t __stdcall vb6_di_PathGetArgsW(intptr_t lpszPath) {
    return ((intptr_t (WINAPI *)(intptr_t))PathGetArgsW)(lpszPath);
}

/* DragAcceptFiles */
void __stdcall vb6_di_DragAcceptFiles(intptr_t hWnd, intptr_t fAccept) {
    ((void (WINAPI *)(intptr_t, intptr_t))DragAcceptFiles)(hWnd, fAccept);
}

/* DragFinish */
void __stdcall vb6_di_DragFinish(intptr_t hDrop) {
    ((void (WINAPI *)(intptr_t))DragFinish)(hDrop);
}

/* DragQueryFileW */
intptr_t __stdcall vb6_di_DragQueryFileW(intptr_t hDrop, intptr_t iFile, intptr_t lpszFile, intptr_t cch) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))DragQueryFileW)(hDrop, iFile, lpszFile, cch);
}

/* DragQueryPoint */
intptr_t __stdcall vb6_di_DragQueryPoint(intptr_t hDrop, void* lpPoint) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))DragQueryPoint)(hDrop, lpPoint);
}
