// vb6_di_win32_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "x"` (Fix 076 scheme: C3 emits
// `extern <ret> __stdcall vb6_di_<alias>(...)` and the RTL implements it).
//
// Family: win32   (libs: kernel32, winmm)   stubs: 67
//
// Each stub reproduces C3's own generated prototype verbatim (that is the ABI the
// caller uses: ByVal Long is widened to intptr_t, ByVal Single stays float, ByRef
// Long stays int32_t*) and forwards 1:1 to the real API through a function-pointer
// cast. The cast keeps the compiler from complaining about unrelated API parameter
// types while preserving the register/memory passing class of every argument.
//
// generated from: C:\Users\user\AppData\Local\Temp\di_migrate_session
// date: 2026-09-17 11:07
//
// Hand-maintained special cases stay in vb6_di_stubs.c (ordinals, msvbvm60 runtime,
// dynamically loaded DLLs). Re-run the generator after a build exposes new symbols.

/* VB6 code uses the classic winsock names (gethostbyname, inet_addr, ...) */
#define _WINSOCK_DEPRECATED_NO_WARNINGS
/* winsock2.h must come before windows.h */
#include <winsock2.h>
#include <windows.h>
#include <stdint.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <mmsystem.h>
#include <dbghelp.h>
#include <iphlpapi.h>
#include <bcrypt.h>
#include <ncrypt.h>
#include <ole2.h>
#include <oleauto.h>
#include <olectl.h>
/* NOTE: gdiplus.h is C++-only (class Gdiplus...). The GDI+ flat API is
 * resolved with GetProcAddress instead - see below. */

/* Import libs for the DLLs below. Adding one that is not needed is harmless:
 * a static import lib is only pulled when a symbol from it is referenced. */
#pragma comment(lib, "kernel32.lib")
#pragma comment(lib, "winmm.lib")

/* BuildCommDCBA */
intptr_t __stdcall vb6_di_BuildCommDCBA(BSTR lpDef, void* lpDCB) {
    return ((intptr_t (WINAPI *)(BSTR, void*))BuildCommDCBA)(lpDef, lpDCB);
}

/* ClearCommBreak */
intptr_t __stdcall vb6_di_ClearCommBreak(intptr_t hFile) {
    return ((intptr_t (WINAPI *)(intptr_t))ClearCommBreak)(hFile);
}

/* ClearCommError */
intptr_t __stdcall vb6_di_ClearCommError(intptr_t hFile, int32_t* lpErrors, void* lpStat) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*, void*))ClearCommError)(hFile, lpErrors, lpStat);
}

/* CloseHandle */
intptr_t __stdcall vb6_di_CloseHandle(intptr_t hObject) {
    return ((intptr_t (WINAPI *)(intptr_t))CloseHandle)(hObject);
}

/* CreatePipe */
intptr_t __stdcall vb6_di_CreatePipe(int32_t* phReadPipe, int32_t* phWritePipe, void* lpPipeAttributes, intptr_t nSize) {
    return ((intptr_t (WINAPI *)(int32_t*, int32_t*, void*, intptr_t))CreatePipe)(phReadPipe, phWritePipe, lpPipeAttributes, nSize);
}

/* CreateProcessA */
intptr_t __stdcall vb6_di_CreateProcessA(intptr_t lpApplicationName, BSTR lpCommandLine, void* lpProcessAttributes, void* lpThreadAttributes, intptr_t bInheritHandles, intptr_t dwCreationFlags, intptr_t lpEnvironment, intptr_t lpCurrentDirectory, void* lpStartupInfo, void* lpProcessInformation) {
    return ((intptr_t (WINAPI *)(intptr_t, BSTR, void*, void*, intptr_t, intptr_t, intptr_t, intptr_t, void*, void*))CreateProcessA)(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory, lpStartupInfo, lpProcessInformation);
}

/* DosDateTimeToFileTime */
intptr_t __stdcall vb6_di_DosDateTimeToFileTime(intptr_t wFatDate, intptr_t wFatTime, void* lpFileTime) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*))DosDateTimeToFileTime)(wFatDate, wFatTime, lpFileTime);
}

/* DuplicateHandle */
intptr_t __stdcall vb6_di_DuplicateHandle(intptr_t hSourceProcessHandle, intptr_t hSourceHandle, intptr_t hTargetProcessHandle, int32_t* lpTargetHandle, intptr_t dwDesiredAccess, intptr_t bInheritHandle, intptr_t dwOptions) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*, intptr_t, intptr_t, intptr_t))DuplicateHandle)(hSourceProcessHandle, hSourceHandle, hTargetProcessHandle, lpTargetHandle, dwDesiredAccess, bInheritHandle, dwOptions);
}

/* EscapeCommFunction */
intptr_t __stdcall vb6_di_EscapeCommFunction(intptr_t hFile, intptr_t dwFunc) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))EscapeCommFunction)(hFile, dwFunc);
}

/* FileTimeToDosDateTime */
intptr_t __stdcall vb6_di_FileTimeToDosDateTime(void* lpFileTime, intptr_t lpFatDate, intptr_t lpFatTime) {
    return ((intptr_t (WINAPI *)(void*, intptr_t, intptr_t))FileTimeToDosDateTime)(lpFileTime, lpFatDate, lpFatTime);
}

/* FileTimeToLocalFileTime */
intptr_t __stdcall vb6_di_FileTimeToLocalFileTime(void* lpFileTime, void* lpLocalFileTime) {
    return ((intptr_t (WINAPI *)(void*, void*))FileTimeToLocalFileTime)(lpFileTime, lpLocalFileTime);
}

/* FileTimeToSystemTime */
intptr_t __stdcall vb6_di_FileTimeToSystemTime(void* lpFileTime, void* lpSystemTime) {
    return ((intptr_t (WINAPI *)(void*, void*))FileTimeToSystemTime)(lpFileTime, lpSystemTime);
}

/* FindClose */
intptr_t __stdcall vb6_di_FindClose(intptr_t hFindFile) {
    return ((intptr_t (WINAPI *)(intptr_t))FindClose)(hFindFile);
}

/* FormatMessageA */
intptr_t __stdcall vb6_di_FormatMessageA(intptr_t dwFlags, void* lpSource, intptr_t dwMessageId, intptr_t dwLanguageId, BSTR lpBuffer, intptr_t nSize, int32_t* Arguments) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, BSTR, intptr_t, int32_t*))FormatMessageA)(dwFlags, lpSource, dwMessageId, dwLanguageId, lpBuffer, nSize, Arguments);
}

/* GetCommMask */
intptr_t __stdcall vb6_di_GetCommMask(intptr_t hFile, int32_t* lpEventMask) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetCommMask)(hFile, lpEventMask);
}

/* GetCommModemStatus */
intptr_t __stdcall vb6_di_GetCommModemStatus(intptr_t hFile, int32_t* lpModemStat) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetCommModemStatus)(hFile, lpModemStat);
}

/* GetCommProperties */
intptr_t __stdcall vb6_di_GetCommProperties(intptr_t hFile, void* lpCommProp) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetCommProperties)(hFile, lpCommProp);
}

/* GetCommState */
intptr_t __stdcall vb6_di_GetCommState(intptr_t hFile, void* lpDCB) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetCommState)(hFile, lpDCB);
}

/* GetCommTimeouts */
intptr_t __stdcall vb6_di_GetCommTimeouts(intptr_t hCommDev, void* lpCommTimeouts) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetCommTimeouts)(hCommDev, lpCommTimeouts);
}

/* GetCurrentProcess */
intptr_t __stdcall vb6_di_GetCurrentProcess() {
    return ((intptr_t (WINAPI *)(void))GetCurrentProcess)();
}

/* GetCurrentProcessId */
intptr_t __stdcall vb6_di_GetCurrentProcessId() {
    return ((intptr_t (WINAPI *)(void))GetCurrentProcessId)();
}

/* GetExitCodeProcess */
intptr_t __stdcall vb6_di_GetExitCodeProcess(intptr_t hProcess, int32_t* lpExitCode) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetExitCodeProcess)(hProcess, lpExitCode);
}

/* GetLastError */
intptr_t __stdcall vb6_di_GetLastError() {
    return ((intptr_t (WINAPI *)(void))GetLastError)();
}

/* GetModuleHandleA */
intptr_t __stdcall vb6_di_GetModuleHandleA(BSTR lpModuleName) {
    return ((intptr_t (WINAPI *)(BSTR))GetModuleHandleA)(lpModuleName);
}

/* GetModuleHandleW */
intptr_t __stdcall vb6_di_GetModuleHandleW(intptr_t lpModuleName) {
    return ((intptr_t (WINAPI *)(intptr_t))GetModuleHandleW)(lpModuleName);
}

/* GetProcAddress */
intptr_t __stdcall vb6_di_GetProcAddress(intptr_t hModule, BSTR lpProcName) {
    return ((intptr_t (WINAPI *)(intptr_t, BSTR))GetProcAddress)(hModule, lpProcName);
}

/* GetStdHandle */
intptr_t __stdcall vb6_di_GetStdHandle(intptr_t nStdHandle) {
    return ((intptr_t (WINAPI *)(intptr_t))GetStdHandle)(nStdHandle);
}

/* GetSystemDefaultLangID */
int16_t __stdcall vb6_di_GetSystemDefaultLangID() {
    return ((int16_t (WINAPI *)(void))GetSystemDefaultLangID)();
}

/* GetSystemTime */
void __stdcall vb6_di_GetSystemTime(void* lpSystemTime) {
    ((void (WINAPI *)(void*))GetSystemTime)(lpSystemTime);
}

/* GetTickCount */
intptr_t __stdcall vb6_di_GetTickCount() {
    return ((intptr_t (WINAPI *)(void))GetTickCount)();
}

/* GetTimeZoneInformation */
intptr_t __stdcall vb6_di_GetTimeZoneInformation(void* utc_lpTimeZoneInformation) {
    return ((intptr_t (WINAPI *)(void*))GetTimeZoneInformation)(utc_lpTimeZoneInformation);
}

/* GlobalAlloc */
intptr_t __stdcall vb6_di_GlobalAlloc(intptr_t wFlags, intptr_t dwBytes) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))GlobalAlloc)(wFlags, dwBytes);
}

/* GlobalFree */
intptr_t __stdcall vb6_di_GlobalFree(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))GlobalFree)(hMem);
}

/* GlobalLock */
intptr_t __stdcall vb6_di_GlobalLock(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))GlobalLock)(hMem);
}

/* GlobalUnlock */
intptr_t __stdcall vb6_di_GlobalUnlock(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))GlobalUnlock)(hMem);
}

/* IsBadCodePtr */
intptr_t __stdcall vb6_di_IsBadCodePtr(intptr_t lpFn) {
    return ((intptr_t (WINAPI *)(intptr_t))IsBadCodePtr)(lpFn);
}

/* IsBadReadPtr */
intptr_t __stdcall vb6_di_IsBadReadPtr(intptr_t lp, intptr_t ucb) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))IsBadReadPtr)(lp, ucb);
}

/* LocalFileTimeToFileTime */
intptr_t __stdcall vb6_di_LocalFileTimeToFileTime(void* lpLocalFileTime, void* lpFileTime) {
    return ((intptr_t (WINAPI *)(void*, void*))LocalFileTimeToFileTime)(lpLocalFileTime, lpFileTime);
}

/* LocalFree */
intptr_t __stdcall vb6_di_LocalFree(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))LocalFree)(hMem);
}

/* lstrlenA */
intptr_t __stdcall vb6_di_lstrlenA(intptr_t lpStr) {
    return ((intptr_t (WINAPI *)(intptr_t))lstrlenA)(lpStr);
}

/* lstrlenW */
intptr_t __stdcall vb6_di_lstrlenW(intptr_t lpStr) {
    return ((intptr_t (WINAPI *)(intptr_t))lstrlenW)(lpStr);
}

/* MultiByteToWideChar */
intptr_t __stdcall vb6_di_MultiByteToWideChar(intptr_t CodePage, intptr_t dwFlags, void* lpMultiByteStr, intptr_t cchMultiByte, intptr_t lpWideCharStr, intptr_t cchWideChar) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, intptr_t, intptr_t))MultiByteToWideChar)(CodePage, dwFlags, lpMultiByteStr, cchMultiByte, lpWideCharStr, cchWideChar);
}

/* PeekNamedPipe */
intptr_t __stdcall vb6_di_PeekNamedPipe(intptr_t hNamedPipe, intptr_t lpBuffer, intptr_t nBufferSize, int32_t* lpBytesRead, int32_t* lpTotalBytesAvail, int32_t* lpBytesLeftThisMessage) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*, int32_t*, int32_t*))PeekNamedPipe)(hNamedPipe, lpBuffer, nBufferSize, lpBytesRead, lpTotalBytesAvail, lpBytesLeftThisMessage);
}

/* PurgeComm */
intptr_t __stdcall vb6_di_PurgeComm(intptr_t hFile, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))PurgeComm)(hFile, dwFlags);
}

/* QueryPerformanceCounter */
intptr_t __stdcall vb6_di_QueryPerformanceCounter(int64_t* lpPerformanceCount) {
    return ((intptr_t (WINAPI *)(int64_t*))QueryPerformanceCounter)(lpPerformanceCount);
}

/* QueryPerformanceFrequency */
intptr_t __stdcall vb6_di_QueryPerformanceFrequency(int64_t* lpFrequency) {
    return ((intptr_t (WINAPI *)(int64_t*))QueryPerformanceFrequency)(lpFrequency);
}

/* ReadFile */
intptr_t __stdcall vb6_di_ReadFile(intptr_t hFile, void* lpBuffer, intptr_t nNumberOfBytesToRead, int32_t* lpNumberOfBytesRead, intptr_t lpOverlapped) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, int32_t*, intptr_t))ReadFile)(hFile, lpBuffer, nNumberOfBytesToRead, lpNumberOfBytesRead, lpOverlapped);
}

/* SetCommBreak */
intptr_t __stdcall vb6_di_SetCommBreak(intptr_t hFile) {
    return ((intptr_t (WINAPI *)(intptr_t))SetCommBreak)(hFile);
}

/* SetCommMask */
intptr_t __stdcall vb6_di_SetCommMask(intptr_t hFile, intptr_t dwEventMask) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))SetCommMask)(hFile, dwEventMask);
}

/* SetCommState */
intptr_t __stdcall vb6_di_SetCommState(intptr_t hFile, void* lpDCB) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))SetCommState)(hFile, lpDCB);
}

/* SetCommTimeouts */
intptr_t __stdcall vb6_di_SetCommTimeouts(intptr_t hFile, void* lpCommTimeouts) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))SetCommTimeouts)(hFile, lpCommTimeouts);
}

/* SetEndOfFile */
intptr_t __stdcall vb6_di_SetEndOfFile(intptr_t hFile) {
    return ((intptr_t (WINAPI *)(intptr_t))SetEndOfFile)(hFile);
}

/* SetFilePointerEx */
intptr_t __stdcall vb6_di_SetFilePointerEx(intptr_t hFile, int64_t liDistanceToMove, void* lpNewFilePointer, intptr_t dwMoveMethod) {
    return ((intptr_t (WINAPI *)(intptr_t, int64_t, void*, intptr_t))SetFilePointerEx)(hFile, liDistanceToMove, lpNewFilePointer, dwMoveMethod);
}

/* SetFileTime */
intptr_t __stdcall vb6_di_SetFileTime(intptr_t hFile, void* lpCreationTime, void* lpLastAccessTime, void* lpLastWriteTime) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, void*, void*))SetFileTime)(hFile, lpCreationTime, lpLastAccessTime, lpLastWriteTime);
}

/* SetupComm */
intptr_t __stdcall vb6_di_SetupComm(intptr_t hFile, intptr_t dwInQueue, intptr_t dwOutQueue) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))SetupComm)(hFile, dwInQueue, dwOutQueue);
}

/* Sleep */
void __stdcall vb6_di_Sleep(intptr_t dwMilliseconds) {
    ((void (WINAPI *)(intptr_t))Sleep)(dwMilliseconds);
}

/* SystemTimeToFileTime */
intptr_t __stdcall vb6_di_SystemTimeToFileTime(void* lpSystemTime, void* lpFileTime) {
    return ((intptr_t (WINAPI *)(void*, void*))SystemTimeToFileTime)(lpSystemTime, lpFileTime);
}

/* SystemTimeToTzSpecificLocalTime */
intptr_t __stdcall vb6_di_SystemTimeToTzSpecificLocalTime(void* utc_lpTimeZoneInformation, void* utc_lpUniversalTime, void* utc_lpLocalTime) {
    return ((intptr_t (WINAPI *)(void*, void*, void*))SystemTimeToTzSpecificLocalTime)(utc_lpTimeZoneInformation, utc_lpUniversalTime, utc_lpLocalTime);
}

/* timeGetTime */
intptr_t __stdcall vb6_di_timeGetTime() {
    return ((intptr_t (WINAPI *)(void))timeGetTime)();
}

/* TransmitCommChar */
intptr_t __stdcall vb6_di_TransmitCommChar(intptr_t hCommDev, uint8_t cChar) {
    return ((intptr_t (WINAPI *)(intptr_t, uint8_t))TransmitCommChar)(hCommDev, cChar);
}

/* TzSpecificLocalTimeToSystemTime */
intptr_t __stdcall vb6_di_TzSpecificLocalTimeToSystemTime(void* utc_lpTimeZoneInformation, void* utc_lpLocalTime, void* utc_lpUniversalTime) {
    return ((intptr_t (WINAPI *)(void*, void*, void*))TzSpecificLocalTimeToSystemTime)(utc_lpTimeZoneInformation, utc_lpLocalTime, utc_lpUniversalTime);
}

/* VirtualAlloc */
intptr_t __stdcall vb6_di_VirtualAlloc(intptr_t lpAddress, intptr_t dwSize, intptr_t flAllocationType, intptr_t flProtect) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))VirtualAlloc)(lpAddress, dwSize, flAllocationType, flProtect);
}

/* VirtualFree */
intptr_t __stdcall vb6_di_VirtualFree(intptr_t lpAddress, intptr_t dwSize, intptr_t dwFreeType) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))VirtualFree)(lpAddress, dwSize, dwFreeType);
}

/* VirtualProtect */
intptr_t __stdcall vb6_di_VirtualProtect(intptr_t lpAddress, intptr_t dwSize, intptr_t flNewProtect, int32_t* lpflOldProtect) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*))VirtualProtect)(lpAddress, dwSize, flNewProtect, lpflOldProtect);
}

/* WaitCommEvent */
intptr_t __stdcall vb6_di_WaitCommEvent(intptr_t hFile, int32_t* lpEventMask, void* lpOverlapped) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*, void*))WaitCommEvent)(hFile, lpEventMask, lpOverlapped);
}

/* WaitForSingleObject */
intptr_t __stdcall vb6_di_WaitForSingleObject(intptr_t hHandle, intptr_t dwMilliseconds) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))WaitForSingleObject)(hHandle, dwMilliseconds);
}

/* WriteFile */
intptr_t __stdcall vb6_di_WriteFile(intptr_t hFile, void* lpBuffer, intptr_t nNumberOfBytesToWrite, int32_t* lpNumberOfBytesWritten, intptr_t lpOverlapped) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, int32_t*, intptr_t))WriteFile)(hFile, lpBuffer, nNumberOfBytesToWrite, lpNumberOfBytesWritten, lpOverlapped);
}
