// vb6_di_net_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "x"` (Fix 076 scheme: C3 emits
// `extern <ret> __stdcall vb6_di_<alias>(...)` and the RTL implements it).
//
// Family: net   (libs: ws2_32, iphlpapi)   stubs: 29
//
// Each stub reproduces C3's own generated prototype verbatim (that is the ABI the
// caller uses: ByVal Long is widened to intptr_t, ByVal Single stays float, ByRef
// Long stays int32_t*) and forwards 1:1 to the real API through a function-pointer
// cast. The cast keeps the compiler from complaining about unrelated API parameter
// types while preserving the register/memory passing class of every argument.
//
// generated from: a C3 compile session (pass -SessionDir to regenerate)
// date: 2026-09-20 07:16
//
// Hand-maintained special cases stay in vb6_di_stubs.c (ordinals, msvbvm60 runtime,
// dynamically loaded DLLs). Re-run the generator after a build exposes new symbols.

/* VB6 code uses the classic winsock names (gethostbyname, inet_addr, ...) */
#define _WINSOCK_DEPRECATED_NO_WARNINGS
/* winsock2.h must come before windows.h */
#include <winsock2.h>
#include <windows.h>
#include <dwmapi.h>
#undef RtlMoveMemory
#undef RtlCopyMemory
#undef RtlFillMemory
#undef RtlZeroMemory
void WINAPI RtlMoveMemory(void*, const void*, size_t);
void WINAPI RtlCopyMemory(void*, const void*, size_t);
void WINAPI RtlFillMemory(void*, size_t, unsigned char);
void WINAPI RtlZeroMemory(void*, size_t);
#include <stdint.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <mmsystem.h>
#include <dbghelp.h>
#include <iphlpapi.h>
#include <bcrypt.h>
#include <ncrypt.h>
#include <ole2.h>
#include <oleauto.h>
#include <olectl.h>
/* NOTE: gdiplus.h is C++-only (class Gdiplus...). The GDI+ flat API is
 * resolved with GetProcAddress instead - see below. */

/* Import libs for the DLLs below. Adding one that is not needed is harmless:
 * a static import lib is only pulled when a symbol from it is referenced. */
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "iphlpapi.lib")
#pragma comment(lib, "comdlg32.lib")

/* GetAdaptersInfo */
intptr_t __stdcall vb6_di_GetAdaptersInfo(void* lpAdapterInfo, int32_t* lpSize) {
    return ((intptr_t (WINAPI *)(void*, int32_t*))GetAdaptersInfo)(lpAdapterInfo, lpSize);
}

/* GetIpForwardTable */
intptr_t __stdcall vb6_di_GetIpForwardTable(void* pIpForwardTable, int32_t* pdwSize, intptr_t bOrder) {
    return ((intptr_t (WINAPI *)(void*, int32_t*, intptr_t))GetIpForwardTable)(pIpForwardTable, pdwSize, bOrder);
}

/* WSAStartup */
intptr_t __stdcall vb6_di_WSAStartup(intptr_t wVersionRequired, void* lpWSAData) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))WSAStartup)(wVersionRequired, lpWSAData);
}

/* WSACleanup */
intptr_t __stdcall vb6_di_WSACleanup() {
    return ((intptr_t (WINAPI *)(void))WSACleanup)();
}

/* WSAAsyncGetHostByName */
intptr_t __stdcall vb6_di_WSAAsyncGetHostByName(intptr_t hWnd, intptr_t wMsg, BSTR strHostName, void* lpBuf, intptr_t lBufLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, BSTR, void*, intptr_t))WSAAsyncGetHostByName)(hWnd, wMsg, strHostName, lpBuf, lBufLen);
}

/* WSAAsyncSelect */
intptr_t __stdcall vb6_di_WSAAsyncSelect(intptr_t lSocket, intptr_t hWnd, intptr_t wMsg, intptr_t lEvent) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))WSAAsyncSelect)(lSocket, hWnd, wMsg, lEvent);
}

/* WSACancelAsyncRequest */
intptr_t __stdcall vb6_di_WSACancelAsyncRequest(intptr_t hAsyncTaskHandle) {
    return ((intptr_t (WINAPI *)(intptr_t))WSACancelAsyncRequest)(hAsyncTaskHandle);
}

/* WSASocketW */
intptr_t __stdcall vb6_di_WSASocketW(intptr_t lAf, intptr_t lType, intptr_t lProtocol, intptr_t lpProtocolInfo, intptr_t lGroup, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))WSASocketW)(lAf, lType, lProtocol, lpProtocolInfo, lGroup, dwFlags);
}

/* connect */
intptr_t __stdcall vb6_di_connect(intptr_t lSocket, void* uName, intptr_t lNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t))connect)(lSocket, uName, lNameLen);
}

/* bind */
intptr_t __stdcall vb6_di_bind(intptr_t lSocket, void* uName, intptr_t lNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t))bind)(lSocket, uName, lNameLen);
}

/* htonl */
intptr_t __stdcall vb6_di_htonl(intptr_t lHostLong) {
    return ((intptr_t (WINAPI *)(intptr_t))htonl)(lHostLong);
}

/* htons */
int16_t __stdcall vb6_di_htons(intptr_t lHostShort) {
    return ((int16_t (WINAPI *)(intptr_t))htons)(lHostShort);
}

/* ntohs */
int16_t __stdcall vb6_di_ntohs(intptr_t lNetShort) {
    return ((int16_t (WINAPI *)(intptr_t))ntohs)(lNetShort);
}

/* inet_ntoa */
intptr_t __stdcall vb6_di_inet_ntoa(intptr_t lIn) {
    return ((intptr_t (WINAPI *)(intptr_t))inet_ntoa)(lIn);
}

/* recv */
intptr_t __stdcall vb6_di_recv(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t))recv)(lSocket, lpBuf, lBufLen, dwFlags);
}

/* recvfrom */
intptr_t __stdcall vb6_di_recvfrom(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags, void* uFrom, int32_t* lpFromLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, void*, int32_t*))recvfrom)(lSocket, lpBuf, lBufLen, dwFlags, uFrom, lpFromLen);
}

/* send */
intptr_t __stdcall vb6_di_send(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t))send)(lSocket, lpBuf, lBufLen, dwFlags);
}

/* sendto */
intptr_t __stdcall vb6_di_sendto(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags, void* uTo, intptr_t lToLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, void*, intptr_t))sendto)(lSocket, lpBuf, lBufLen, dwFlags, uTo, lToLen);
}

/* getpeername */
intptr_t __stdcall vb6_di_getpeername(intptr_t lSocket, void* uName, int32_t* lpNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, int32_t*))getpeername)(lSocket, uName, lpNameLen);
}

/* getsockname */
intptr_t __stdcall vb6_di_getsockname(intptr_t lSocket, void* uName, int32_t* lpNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, int32_t*))getsockname)(lSocket, uName, lpNameLen);
}

/* shutdown */
intptr_t __stdcall vb6_di_shutdown(intptr_t lSocket, intptr_t lHow) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))shutdown)(lSocket, lHow);
}

/* listen */
intptr_t __stdcall vb6_di_listen(intptr_t lSocket, intptr_t lBackLog) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))listen)(lSocket, lBackLog);
}

/* accept */
intptr_t __stdcall vb6_di_accept(intptr_t lSocket, void* lpAddr, void* lpAddrLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, void*))accept)(lSocket, lpAddr, lpAddrLen);
}

/* ioctlsocket */
intptr_t __stdcall vb6_di_ioctlsocket(intptr_t lSocket, intptr_t lCmd, int32_t* lpArg) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, int32_t*))ioctlsocket)(lSocket, lCmd, lpArg);
}

/* getsockopt */
intptr_t __stdcall vb6_di_getsockopt(intptr_t lSocket, intptr_t lLevel, intptr_t lOptName, void* lpOptVal, int32_t* lpOptLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*, int32_t*))getsockopt)(lSocket, lLevel, lOptName, lpOptVal, lpOptLen);
}

/* setsockopt */
intptr_t __stdcall vb6_di_setsockopt(intptr_t lSocket, intptr_t lLevel, intptr_t lOptName, void* lpOptVal, intptr_t lOptLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*, intptr_t))setsockopt)(lSocket, lLevel, lOptName, lpOptVal, lOptLen);
}

/* inet_addr */
intptr_t __stdcall vb6_di_inet_addr(BSTR sAddr) {
    return ((intptr_t (WINAPI *)(BSTR))inet_addr)(sAddr);
}

/* gethostbyname */
intptr_t __stdcall vb6_di_gethostbyname(BSTR sHostName) {
    return ((intptr_t (WINAPI *)(BSTR))gethostbyname)(sHostName);
}

/* gethostname */
intptr_t __stdcall vb6_di_gethostname(BSTR sHostName, intptr_t lNameLen) {
    return ((intptr_t (WINAPI *)(BSTR, intptr_t))gethostname)(sHostName, lNameLen);
}
