# emit_manifest.ps1 - build a **toolchain-attributable** shape manifest for the corpus.
#
# Why (ledger 245 / B73): the emitted C is what a shipped program is made of, but two
# C3.exe binaries built from the *same commit* with different MSVC versions disagree on
# 14 of 788 corpus captures (all Charts 2020 UC projects, all in one shape: which COM
# getter a With-target member read is allowed to use). A gate that builds and tests with
# the same binary can never see that, and a local A/B can only ever describe the local
# binary's answer. So CI records *its* answer here: one sha256 line per input plus the
# toolset that produced it. Not a pass/fail check (yet) - the point is that evidence for
# "what does the shipped codegen look like" stops being local-only.
#
# x64 only: the measured divergence has the same lines and same shape on both arches, so
# a second arch costs ~2x wall time for no new coverage.
#
# Byte-exact hashing rules (must match on both sides):
#   * only the compiler's stdout is hashed (stderr carries machine-specific warnings);
#   * "// Generated by vb6c3 (C3.exe) from <abs path>" headers are normalised to <PATH>,
#     and any occurrence of this checkout's own root becomes <ROOT>;
#   * text is handled as Latin-1 (codepage 28591) so bytes round-trip 1:1.
#
# Usage:  powershell -File scripts/emit_manifest.ps1 [-Root <repo>] [-Out <file>]
param(
    [string]$Root = "",
    [string]$Out = "",
    [string]$Samples = "tests/acc/acc_main.bas,tests/asm/AsmTest.bas,tests/Charts 2020/ucChartArea/Proyecto1.vbp"
)
$ErrorActionPreference = 'Continue'
if (-not $Root) { $Root = (Split-Path -Parent $PSScriptRoot) }
$Root = (Resolve-Path $Root).Path
if (-not $Out) { $Out = Join-Path $Root "emit-manifest.txt" }

$c3 = Join-Path $Root ".build\C3.exe"
if (-not (Test-Path $c3)) { Write-Host "MISSING C3.exe: $c3"; exit 2 }

$lat = [System.Text.Encoding]::GetEncoding(28591)

function Get-NormHash([string]$path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $text = $lat.GetString($bytes)
    $text = [regex]::Replace($text, '(?m)^// Generated by vb6c3 \(C3\.exe\) from .*$',
                             '// Generated by vb6c3 (C3.exe) from <PATH>')
    foreach ($form in @($Root, $Root.Replace('\', '/'))) {
        if ($form) { $text = $text.Replace($form, '<ROOT>') }
    }
    $rebytes = $lat.GetBytes($text)
    # 第二列 = 只把**纯 ASCII 行**拿去哈希。理由（账 #267）：产品发出的中文注释字节随"编译 C3.exe 的那台
    # 工具链"变（14.29 按 GBK、14.51 按 UTF-8），跨构建比清单时这一族会把每一行都刷成"不同"，
    # 把真正的语义差淹掉（实测 319/395 vs 语义那 14 份）。ascii256 相同 + sha256 不同 ⇒ 只差在编码。
    $ascii = (($text -split "`n") | Where-Object { $_ -notmatch '[^\x09\x0A\x0D\x20-\x7E]' }) -join "`n"
    $ab = $lat.GetBytes($ascii)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hex = ($sha.ComputeHash($rebytes) | ForEach-Object { $_.ToString("x2") }) -join ''
        $ahex = ($sha.ComputeHash($ab) | ForEach-Object { $_.ToString("x2") }) -join ''
    } finally { $sha.Dispose() }
    return @($hex, $rebytes.Length, $ahex)
}

$exeHash = (Get-NormHash $c3)[0]
$exeSize = (Get-Item $c3).Length

# Toolset identity. 两处读数，缺一不可：
#   * pe-lnk = 从**这枚二进制自己的 PE 头**读链接器版本 (optional header 的 MajorLinkerVersion/
#     MinorLinkerVersion) —— 这是"谁编出它"的唯一硬证据，与本机装了几个 VS 无关。
#   * msvc-installed = 这台机器上装的 MSVC 工具目录**全部列出**。曾经这里只写
#     `Get-ChildItem | Select -First 1`，那是"按字母序最小的一档"，runner 上多版本共存时
#     会把实际用的那档漏掉（门 #410 就因此报成 msvc=14.29.30133，看着和本机一样，
#     而 Build 作业按 vswhere -latest 选的工具集未必是它）⇒ 那一版读数不能用来判"两侧工具链相同"。
$vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
$vsVer = "unknown"; $msvcList = "unknown"
if (Test-Path $vswhere) {
    $vsVer = (& $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationVersion 2>$null)
    $vsPath = (& $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath 2>$null)
    if ($vsPath) {
        $tools = Join-Path $vsPath "VC\Tools\MSVC"
        if (Test-Path $tools) { $msvcList = ((Get-ChildItem $tools | ForEach-Object { $_.Name }) -join '+') }
    }
}
$peLnk = "unknown"
try {
    $bytes = [System.IO.File]::ReadAllBytes($c3)
    $off = [BitConverter]::ToInt32($bytes, 0x3C)          # e_lfanew
    # PE\0\0 = 4 字节, IMAGE_FILE_HEADER = 20 字节 ⇒ optional header 在 off+24;
    # 它的前两字节是 Magic，链接器版本在 +2/+3 ⇒ 绝对偏移 off+26 / off+27。
    $peLnk = ("{0}.{1}" -f $bytes[$off + 26], $bytes[$off + 27])
} catch { }

$inputs = Get-ChildItem -Path (Join-Path $Root "tests") -Recurse -File |
    Where-Object { $_.Extension -match '^\.(vbp|bas)$' } |
    Where-Object { $_.FullName -notmatch '\\(bin|obj|output)\\' } |
    Sort-Object FullName

$lines = @()
$lines += "# c3-exe sha256=$exeHash size=$exeSize"
$lines += "# toolset pe-lnk=$peLnk vs=$vsVer msvc-installed=$msvcList runner=$env:COMPUTERNAME"
$lines += "# arch=x64 inputs=$($inputs.Count)"
# 列义：sha256 = 归一化后全文哈希；ascii256 = 只取纯 ASCII 行的哈希（两侧对齐用它，见上面注释）；
#        bytes = 归一化后全文字节数；最后一段是仓库内的相对路径。
$lines += "# columns: sha256=<normalized全文> ascii256=<仅ASCII行> rc=<退出码> bytes=<归一化字节> <relpath>"
$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("emitnorm_" + [guid]::NewGuid().ToString("N") + ".c")
$sampleDir = Join-Path $Root ".build\emit-samples"
if (Test-Path $sampleDir) { Remove-Item $sampleDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path $sampleDir | Out-Null
$fail = 0
foreach ($in0 in $inputs) {
    $rel = $in0.FullName.Substring($Root.Length + 1).Replace('\', '/')
    if (Test-Path $tmp) { Remove-Item $tmp -Force }
    # 路径里有空格 ("Charts 2020") ⇒ 必须自己加引号: Start-Process 只是把参数串起来,
    # 不会替含空格的实参加引号 (不加就变成两个参数, C3.exe 报"找不到工程")。
    $p = Start-Process -FilePath $c3 -ArgumentList @('"' + $in0.FullName + '"', "--emit-c") `
        -WorkingDirectory $Root -RedirectStandardOutput $tmp -RedirectStandardError ([System.IO.Path]::ChangeExtension($tmp, ".err")) `
        -NoNewWindow -Wait -PassThru
    $rc = $p.ExitCode
    $pair = Get-NormHash $tmp
    $lines += ("sha256={0} ascii256={1} rc={2} bytes={3} {4}" -f $pair[0], $pair[2], $rc, $pair[1], $rel)
    if ($rc -ne 0) { $fail++ }
    # 清单只有哈希，跨机器对不出"差在哪一行"。$Samples 里点名的输入把**未归一化的原文**
    # 一并留下（文件名把路径里的分隔符/空格折成下划线），两边一比就知道差的是内容还是环境串。
    $flat = $rel -replace '[\\/ \-]', '_'
    if (($Samples -split ',') -contains $rel -or ($Samples -split ',') -contains $flat) {
        Copy-Item $tmp (Join-Path $sampleDir ($flat + '.c')) -Force
    }
}
if (Test-Path $tmp) { Remove-Item $tmp -Force }
Set-Content -Path $Out -Value $lines -Encoding UTF8
Write-Host ("manifest=$Out lines=$($lines.Count) inputs=$($inputs.Count) rc!=0=$fail")
