// vb6_di_win32_stubs.c - generated by scripts/gen_di_stubs.ps1
//
// Win32 forwarding stubs for VB6 `Declare ... Lib "x"` (Fix 076 scheme: C3 emits
// `extern <ret> __stdcall vb6_di_<alias>(...)` and the RTL implements it).
//
// Each stub reproduces C3's own generated prototype verbatim (that is the ABI the
// caller uses: ByVal Long is widened to intptr_t, ByVal Single stays float, ByRef
// Long stays int32_t*) and forwards 1:1 to the real API through a function-pointer
// cast. The cast keeps the compiler from complaining about unrelated API parameter
// types while preserving the register/memory passing class of every argument.
//
// generated from: C:\Users\vi\AppData\Local\Temp\C3C\963147007345900
// date: 2026-09-11 20:30
//
// Hand-maintained special cases stay in vb6_di_stubs.c (ordinals, msvbvm60 runtime,
// dynamically loaded DLLs). Re-run the generator after a build exposes new symbols.

/* VB6 code uses the classic winsock names (gethostbyname, inet_addr, ...) */
#define _WINSOCK_DEPRECATED_NO_WARNINGS
/* winsock2.h must come before windows.h */
#include <winsock2.h>
#include <windows.h>
#include <stdint.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <mmsystem.h>
#include <dbghelp.h>
#include <iphlpapi.h>
#include <bcrypt.h>
#include <ncrypt.h>
#include <ole2.h>
#include <oleauto.h>
#include <olectl.h>
/* NOTE: gdiplus.h is C++-only (class Gdiplus...). The GDI+ flat API is
 * resolved with GetProcAddress instead - see below. */

/* Import libs for the DLLs below. Adding one that is not needed is harmless:
 * a static import lib is only pulled when a symbol from it is referenced. */
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "kernel32.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "ole32.lib")
#pragma comment(lib, "oleaut32.lib")
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "shlwapi.lib")
#pragma comment(lib, "winmm.lib")
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "iphlpapi.lib")
#pragma comment(lib, "dbghelp.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "ncrypt.lib")
#pragma comment(lib, "uuid.lib")

/* GDI+ flat API lives in gdiplus.dll but its header is C++-only, so the
 * symbols below are resolved by name at first use. */
static void* vb6_di_gdiplus_proc(const char* name) {
    static HMODULE mod = NULL;
    if (mod == NULL) { mod = LoadLibraryA("gdiplus.dll"); }
    return (mod != NULL) ? (void*)GetProcAddress(mod, name) : NULL;
}

/* accept */
intptr_t __stdcall vb6_di_accept(intptr_t lSocket, void* lpAddr, void* lpAddrLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, void*))accept)(lSocket, lpAddr, lpAddrLen);
}

/* BCryptCloseAlgorithmProvider */
intptr_t __stdcall vb6_di_BCryptCloseAlgorithmProvider(intptr_t hAlgorithm, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))BCryptCloseAlgorithmProvider)(hAlgorithm, dwFlags);
}

/* BCryptDecrypt */
intptr_t __stdcall vb6_di_BCryptDecrypt(intptr_t hKey, void* pbInput, intptr_t cbInput, intptr_t pPaddingInfo, void* pbIV, intptr_t cbIV, void* pbOutput, intptr_t cbOutput, int32_t* cbResult, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, void*, intptr_t, void*, intptr_t, int32_t*, intptr_t))BCryptDecrypt)(hKey, pbInput, cbInput, pPaddingInfo, pbIV, cbIV, pbOutput, cbOutput, cbResult, dwFlags);
}

/* BCryptDeriveKeyPBKDF2 */
intptr_t __stdcall vb6_di_BCryptDeriveKeyPBKDF2(intptr_t hPrf, void* pbPassword, intptr_t cbPassword, void* pbSalt, intptr_t cbSalt, int64_t cIterations, void* pbDerivedKey, intptr_t cbDerivedKey, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, void*, intptr_t, int64_t, void*, intptr_t, intptr_t))BCryptDeriveKeyPBKDF2)(hPrf, pbPassword, cbPassword, pbSalt, cbSalt, cIterations, pbDerivedKey, cbDerivedKey, dwFlags);
}

/* BCryptDestroyKey */
intptr_t __stdcall vb6_di_BCryptDestroyKey(intptr_t hKey) {
    return ((intptr_t (WINAPI *)(intptr_t))BCryptDestroyKey)(hKey);
}

/* BCryptGenerateSymmetricKey */
intptr_t __stdcall vb6_di_BCryptGenerateSymmetricKey(intptr_t hAlgorithm, int32_t* phKey, void* pbKeyObject, intptr_t cbKeyObject, void* pbSecret, intptr_t cbSecret, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*, void*, intptr_t, void*, intptr_t, intptr_t))BCryptGenerateSymmetricKey)(hAlgorithm, phKey, pbKeyObject, cbKeyObject, pbSecret, cbSecret, dwFlags);
}

/* BCryptGetProperty */
intptr_t __stdcall vb6_di_BCryptGetProperty(intptr_t hObject, intptr_t pszProperty, void* pbOutput, intptr_t cbOutput, int32_t* cbResult, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, int32_t*, intptr_t))BCryptGetProperty)(hObject, pszProperty, pbOutput, cbOutput, cbResult, dwFlags);
}

/* BCryptOpenAlgorithmProvider */
intptr_t __stdcall vb6_di_BCryptOpenAlgorithmProvider(int32_t* hAlgorithm, intptr_t pszAlgId, intptr_t pszImplementation, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(int32_t*, intptr_t, intptr_t, intptr_t))BCryptOpenAlgorithmProvider)(hAlgorithm, pszAlgId, pszImplementation, dwFlags);
}

/* BCryptSetProperty */
intptr_t __stdcall vb6_di_BCryptSetProperty(intptr_t hObject, intptr_t pszProperty, intptr_t pbInput, intptr_t cbInput, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))BCryptSetProperty)(hObject, pszProperty, pbInput, cbInput, dwFlags);
}

/* bind */
intptr_t __stdcall vb6_di_bind(intptr_t lSocket, void* uName, intptr_t lNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t))bind)(lSocket, uName, lNameLen);
}

/* BitBlt */
intptr_t __stdcall vb6_di_BitBlt(intptr_t hDestDC, intptr_t x, intptr_t y, intptr_t nWidth, intptr_t nHeight, intptr_t hSrcDC, intptr_t xSrc, intptr_t ySrc, intptr_t dwRop) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))BitBlt)(hDestDC, x, y, nWidth, nHeight, hSrcDC, xSrc, ySrc, dwRop);
}

/* BuildCommDCBA */
intptr_t __stdcall vb6_di_BuildCommDCBA(BSTR lpDef, void* lpDCB) {
    return ((intptr_t (WINAPI *)(BSTR, void*))BuildCommDCBA)(lpDef, lpDCB);
}

/* CallWindowProcW */
intptr_t __stdcall vb6_di_CallWindowProcW(intptr_t lpPrevWndFunc, intptr_t hWnd, intptr_t wMsg, intptr_t wParam, intptr_t lParam) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))CallWindowProcW)(lpPrevWndFunc, hWnd, wMsg, wParam, lParam);
}

/* CertAddCertificateContextToStore */
intptr_t __stdcall vb6_di_CertAddCertificateContextToStore(intptr_t hCertStore, intptr_t pCertContext, intptr_t dwAddDisposition, void* ppStoreContext) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*))CertAddCertificateContextToStore)(hCertStore, pCertContext, dwAddDisposition, ppStoreContext);
}

/* CertAddEncodedCertificateToStore */
intptr_t __stdcall vb6_di_CertAddEncodedCertificateToStore(intptr_t hCertStore, intptr_t dwCertEncodingType, void* pbCertEncoded, intptr_t cbCertEncoded, intptr_t dwAddDisposition, void* ppCertContext) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, intptr_t, void*))CertAddEncodedCertificateToStore)(hCertStore, dwCertEncodingType, pbCertEncoded, cbCertEncoded, dwAddDisposition, ppCertContext);
}

/* CertCloseStore */
intptr_t __stdcall vb6_di_CertCloseStore(intptr_t hCertStore, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))CertCloseStore)(hCertStore, dwFlags);
}

/* CertCreateCertificateChainEngine */
intptr_t __stdcall vb6_di_CertCreateCertificateChainEngine(void* pConfig, int32_t* phChainEngine) {
    return ((intptr_t (WINAPI *)(void*, int32_t*))CertCreateCertificateChainEngine)(pConfig, phChainEngine);
}

/* CertCreateCertificateContext */
intptr_t __stdcall vb6_di_CertCreateCertificateContext(intptr_t dwCertEncodingType, void* pbCertEncoded, intptr_t cbCertEncoded) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t))CertCreateCertificateContext)(dwCertEncodingType, pbCertEncoded, cbCertEncoded);
}

/* CertCreateSelfSignCertificate */
intptr_t __stdcall vb6_di_CertCreateSelfSignCertificate(intptr_t hCryptProvOrNCryptKey, void* pSubjectIssuerBlob, intptr_t dwFlags, void* pKeyProvInfo, intptr_t pSignatureAlgorithm, void* pStartTime, void* pEndTime, intptr_t pExtensions) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, void*, intptr_t, void*, void*, intptr_t))CertCreateSelfSignCertificate)(hCryptProvOrNCryptKey, pSubjectIssuerBlob, dwFlags, pKeyProvInfo, pSignatureAlgorithm, pStartTime, pEndTime, pExtensions);
}

/* CertEnumCertificatesInStore */
intptr_t __stdcall vb6_di_CertEnumCertificatesInStore(intptr_t hCertStore, intptr_t pPrevCertContext) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))CertEnumCertificatesInStore)(hCertStore, pPrevCertContext);
}

/* CertFindCertificateInStore */
intptr_t __stdcall vb6_di_CertFindCertificateInStore(intptr_t hCertStore, intptr_t dwCertEncodingType, intptr_t dwFindFlags, intptr_t dwFindType, void* pvFindPara, intptr_t pPrevCertContext) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, void*, intptr_t))CertFindCertificateInStore)(hCertStore, dwCertEncodingType, dwFindFlags, dwFindType, pvFindPara, pPrevCertContext);
}

/* CertFindExtension */
intptr_t __stdcall vb6_di_CertFindExtension(BSTR pszObjId, intptr_t cExtensions, intptr_t rgExtensions) {
    return ((intptr_t (WINAPI *)(BSTR, intptr_t, intptr_t))CertFindExtension)(pszObjId, cExtensions, rgExtensions);
}

/* CertFreeCertificateChain */
intptr_t __stdcall vb6_di_CertFreeCertificateChain(intptr_t pChainContext) {
    return ((intptr_t (WINAPI *)(intptr_t))CertFreeCertificateChain)(pChainContext);
}

/* CertFreeCertificateChainEngine */
intptr_t __stdcall vb6_di_CertFreeCertificateChainEngine(intptr_t hChainEngine) {
    return ((intptr_t (WINAPI *)(intptr_t))CertFreeCertificateChainEngine)(hChainEngine);
}

/* CertFreeCertificateContext */
intptr_t __stdcall vb6_di_CertFreeCertificateContext(intptr_t pCertContext) {
    return ((intptr_t (WINAPI *)(intptr_t))CertFreeCertificateContext)(pCertContext);
}

/* CertGetCertificateChain */
intptr_t __stdcall vb6_di_CertGetCertificateChain(intptr_t hChainEngine, intptr_t pCertContext, intptr_t pTime, intptr_t hAdditionalStore, void* pChainPara, intptr_t dwFlags, intptr_t pvReserved, int32_t* ppChainContext) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, void*, intptr_t, intptr_t, int32_t*))CertGetCertificateChain)(hChainEngine, pCertContext, pTime, hAdditionalStore, pChainPara, dwFlags, pvReserved, ppChainContext);
}

/* CertGetCertificateContextProperty */
intptr_t __stdcall vb6_di_CertGetCertificateContextProperty(intptr_t pCertContext, intptr_t dwPropId, void* pvData, int32_t* pcbData) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, int32_t*))CertGetCertificateContextProperty)(pCertContext, dwPropId, pvData, pcbData);
}

/* CertOpenStore */
intptr_t __stdcall vb6_di_CertOpenStore(intptr_t lpszStoreProvider, intptr_t dwEncodingType, intptr_t hCryptProv, intptr_t dwFlags, intptr_t pvPara) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))CertOpenStore)(lpszStoreProvider, dwEncodingType, hCryptProv, dwFlags, pvPara);
}

/* CertSetCertificateContextProperty */
intptr_t __stdcall vb6_di_CertSetCertificateContextProperty(intptr_t pCertContext, intptr_t dwPropId, intptr_t dwFlags, void* pvData) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*))CertSetCertificateContextProperty)(pCertContext, dwPropId, dwFlags, pvData);
}

/* ClearCommBreak */
intptr_t __stdcall vb6_di_ClearCommBreak(intptr_t hFile) {
    return ((intptr_t (WINAPI *)(intptr_t))ClearCommBreak)(hFile);
}

/* ClearCommError */
intptr_t __stdcall vb6_di_ClearCommError(intptr_t hFile, int32_t* lpErrors, void* lpStat) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*, void*))ClearCommError)(hFile, lpErrors, lpStat);
}

/* ClientToScreen */
intptr_t __stdcall vb6_di_ClientToScreen(intptr_t hwnd, void* lpPoint) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))ClientToScreen)(hwnd, lpPoint);
}

/* CloseHandle */
intptr_t __stdcall vb6_di_CloseHandle(intptr_t hObject) {
    return ((intptr_t (WINAPI *)(intptr_t))CloseHandle)(hObject);
}

/* connect */
intptr_t __stdcall vb6_di_connect(intptr_t lSocket, void* uName, intptr_t lNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t))connect)(lSocket, uName, lNameLen);
}

/* CoTaskMemFree */
intptr_t __stdcall vb6_di_CoTaskMemFree(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))CoTaskMemFree)(hMem);
}

/* CreatePipe */
intptr_t __stdcall vb6_di_CreatePipe(int32_t* phReadPipe, int32_t* phWritePipe, void* lpPipeAttributes, intptr_t nSize) {
    return ((intptr_t (WINAPI *)(int32_t*, int32_t*, void*, intptr_t))CreatePipe)(phReadPipe, phWritePipe, lpPipeAttributes, nSize);
}

/* CreateProcessA */
intptr_t __stdcall vb6_di_CreateProcessA(intptr_t lpApplicationName, BSTR lpCommandLine, void* lpProcessAttributes, void* lpThreadAttributes, intptr_t bInheritHandles, intptr_t dwCreationFlags, intptr_t lpEnvironment, intptr_t lpCurrentDirectory, void* lpStartupInfo, void* lpProcessInformation) {
    return ((intptr_t (WINAPI *)(intptr_t, BSTR, void*, void*, intptr_t, intptr_t, intptr_t, intptr_t, void*, void*))CreateProcessA)(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory, lpStartupInfo, lpProcessInformation);
}

/* CreateRectRgn */
intptr_t __stdcall vb6_di_CreateRectRgn(intptr_t X1, intptr_t Y1, intptr_t X2, intptr_t Y2) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))CreateRectRgn)(X1, Y1, X2, Y2);
}

/* CreateStreamOnHGlobal */
intptr_t __stdcall vb6_di_CreateStreamOnHGlobal(intptr_t hGlobal, intptr_t fDeleteOnRelease, void* ppstm) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*))CreateStreamOnHGlobal)(hGlobal, fDeleteOnRelease, ppstm);
}

/* CryptAcquireCertificatePrivateKey */
intptr_t __stdcall vb6_di_CryptAcquireCertificatePrivateKey(intptr_t pCert, intptr_t dwFlags, intptr_t pvParameters, int32_t* phCryptProvOrNCryptKey, int32_t* pdwKeySpec, int32_t* pfCallerFreeProvOrNCryptKey) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*, int32_t*, int32_t*))CryptAcquireCertificatePrivateKey)(pCert, dwFlags, pvParameters, phCryptProvOrNCryptKey, pdwKeySpec, pfCallerFreeProvOrNCryptKey);
}

/* CryptCreateHash */
intptr_t __stdcall vb6_di_CryptCreateHash(intptr_t hProv, intptr_t Algid, intptr_t hKey, intptr_t dwFlags, int32_t* phHash) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, int32_t*))CryptCreateHash)(hProv, Algid, hKey, dwFlags, phHash);
}

/* CryptDecodeObjectEx */
intptr_t __stdcall vb6_di_CryptDecodeObjectEx(intptr_t dwCertEncodingType, void* lpszStructType, void* pbEncoded, intptr_t cbEncoded, intptr_t dwFlags, intptr_t pDecodePara, void* pvStructInfo, int32_t* pcbStructInfo) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, void*, intptr_t, intptr_t, intptr_t, void*, int32_t*))CryptDecodeObjectEx)(dwCertEncodingType, lpszStructType, pbEncoded, cbEncoded, dwFlags, pDecodePara, pvStructInfo, pcbStructInfo);
}

/* CryptDecrypt */
intptr_t __stdcall vb6_di_CryptDecrypt(intptr_t hKey, intptr_t hHash, intptr_t Final, intptr_t dwFlags, void* pbData, int32_t* pdwDataLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, void*, int32_t*))CryptDecrypt)(hKey, hHash, Final, dwFlags, pbData, pdwDataLen);
}

/* CryptDestroyHash */
intptr_t __stdcall vb6_di_CryptDestroyHash(intptr_t hHash) {
    return ((intptr_t (WINAPI *)(intptr_t))CryptDestroyHash)(hHash);
}

/* CryptDestroyKey */
intptr_t __stdcall vb6_di_CryptDestroyKey(intptr_t hKey) {
    return ((intptr_t (WINAPI *)(intptr_t))CryptDestroyKey)(hKey);
}

/* CryptEncodeObjectEx */
intptr_t __stdcall vb6_di_CryptEncodeObjectEx(intptr_t dwCertEncodingType, void* lpszStructType, void* pvStructInfo, intptr_t dwFlags, intptr_t pEncodePara, void* pvEncoded, int32_t* pcbEncoded) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, void*, intptr_t, intptr_t, void*, int32_t*))CryptEncodeObjectEx)(dwCertEncodingType, lpszStructType, pvStructInfo, dwFlags, pEncodePara, pvEncoded, pcbEncoded);
}

/* CryptExportKey */
intptr_t __stdcall vb6_di_CryptExportKey(intptr_t hKey, intptr_t hExpKey, intptr_t dwBlobType, intptr_t dwFlags, uint8_t* pbData, int32_t* pdwDataLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, uint8_t*, int32_t*))CryptExportKey)(hKey, hExpKey, dwBlobType, dwFlags, pbData, pdwDataLen);
}

/* CryptGenKey */
intptr_t __stdcall vb6_di_CryptGenKey(intptr_t hProv, intptr_t AlgId, intptr_t dwFlags, int32_t* phKey) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*))CryptGenKey)(hProv, AlgId, dwFlags, phKey);
}

/* CryptGenRandom */
intptr_t __stdcall vb6_di_CryptGenRandom(intptr_t hProv, intptr_t dwLen, intptr_t pbBuffer) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))CryptGenRandom)(hProv, dwLen, pbBuffer);
}

/* CryptGetHashParam */
intptr_t __stdcall vb6_di_CryptGetHashParam(intptr_t hHash, intptr_t dwParam, void* pbData, int32_t* pdwDataLen, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, int32_t*, intptr_t))CryptGetHashParam)(hHash, dwParam, pbData, pdwDataLen, dwFlags);
}

/* CryptGetUserKey */
intptr_t __stdcall vb6_di_CryptGetUserKey(intptr_t hProv, intptr_t dwKeySpec, int32_t* phUserKey) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, int32_t*))CryptGetUserKey)(hProv, dwKeySpec, phUserKey);
}

/* CryptHashData */
intptr_t __stdcall vb6_di_CryptHashData(intptr_t hHash, uint8_t* pbData, intptr_t dwDataLen, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, uint8_t*, intptr_t, intptr_t))CryptHashData)(hHash, pbData, dwDataLen, dwFlags);
}

/* CryptImportPublicKeyInfo */
intptr_t __stdcall vb6_di_CryptImportPublicKeyInfo(intptr_t hCryptProv, intptr_t dwCertEncodingType, void* pInfo, int32_t* phKey) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, int32_t*))CryptImportPublicKeyInfo)(hCryptProv, dwCertEncodingType, pInfo, phKey);
}

/* CryptReleaseContext */
intptr_t __stdcall vb6_di_CryptReleaseContext(intptr_t hProv, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))CryptReleaseContext)(hProv, dwFlags);
}

/* CryptSetHashParam */
intptr_t __stdcall vb6_di_CryptSetHashParam(intptr_t hHash, intptr_t dwParam, void* pbData, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t))CryptSetHashParam)(hHash, dwParam, pbData, dwFlags);
}

/* DestroyWindow */
intptr_t __stdcall vb6_di_DestroyWindow(intptr_t hwnd) {
    return ((intptr_t (WINAPI *)(intptr_t))DestroyWindow)(hwnd);
}

/* DosDateTimeToFileTime */
intptr_t __stdcall vb6_di_DosDateTimeToFileTime(intptr_t wFatDate, intptr_t wFatTime, void* lpFileTime) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*))DosDateTimeToFileTime)(wFatDate, wFatTime, lpFileTime);
}

/* DuplicateHandle */
intptr_t __stdcall vb6_di_DuplicateHandle(intptr_t hSourceProcessHandle, intptr_t hSourceHandle, intptr_t hTargetProcessHandle, int32_t* lpTargetHandle, intptr_t dwDesiredAccess, intptr_t bInheritHandle, intptr_t dwOptions) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*, intptr_t, intptr_t, intptr_t))DuplicateHandle)(hSourceProcessHandle, hSourceHandle, hTargetProcessHandle, lpTargetHandle, dwDesiredAccess, bInheritHandle, dwOptions);
}

/* EscapeCommFunction */
intptr_t __stdcall vb6_di_EscapeCommFunction(intptr_t hFile, intptr_t dwFunc) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))EscapeCommFunction)(hFile, dwFunc);
}

/* FileTimeToDosDateTime */
intptr_t __stdcall vb6_di_FileTimeToDosDateTime(void* lpFileTime, intptr_t lpFatDate, intptr_t lpFatTime) {
    return ((intptr_t (WINAPI *)(void*, intptr_t, intptr_t))FileTimeToDosDateTime)(lpFileTime, lpFatDate, lpFatTime);
}

/* FileTimeToLocalFileTime */
intptr_t __stdcall vb6_di_FileTimeToLocalFileTime(void* lpFileTime, void* lpLocalFileTime) {
    return ((intptr_t (WINAPI *)(void*, void*))FileTimeToLocalFileTime)(lpFileTime, lpLocalFileTime);
}

/* FileTimeToSystemTime */
intptr_t __stdcall vb6_di_FileTimeToSystemTime(void* lpFileTime, void* lpSystemTime) {
    return ((intptr_t (WINAPI *)(void*, void*))FileTimeToSystemTime)(lpFileTime, lpSystemTime);
}

/* FindClose */
intptr_t __stdcall vb6_di_FindClose(intptr_t hFindFile) {
    return ((intptr_t (WINAPI *)(intptr_t))FindClose)(hFindFile);
}

/* FormatMessageA */
intptr_t __stdcall vb6_di_FormatMessageA(intptr_t dwFlags, void* lpSource, intptr_t dwMessageId, intptr_t dwLanguageId, BSTR lpBuffer, intptr_t nSize, int32_t* Arguments) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, BSTR, intptr_t, int32_t*))FormatMessageA)(dwFlags, lpSource, dwMessageId, dwLanguageId, lpBuffer, nSize, Arguments);
}

/* GdipAddPathArcI */
intptr_t __stdcall vb6_di_GdipAddPathArcI(intptr_t mpath, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight, float mStartAngle, float mSweepAngle) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, float, float) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, float, float))vb6_di_gdiplus_proc("GdipAddPathArcI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mpath, mX, mY, mWidth, mHeight, mStartAngle, mSweepAngle);
}

/* GdipAddPathRectangleI */
intptr_t __stdcall vb6_di_GdipAddPathRectangleI(intptr_t mpath, intptr_t mX, intptr_t mY, intptr_t mWidth, intptr_t mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipAddPathRectangleI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mpath, mX, mY, mWidth, mHeight);
}

/* GdipBitmapLockBits */
intptr_t __stdcall vb6_di_GdipBitmapLockBits(intptr_t mBitmap, void* mRect, int32_t mFlags, intptr_t mPixelFormat, void* mLockedBitmapData) {
    intptr_t (WINAPI *fn)(intptr_t, void*, int32_t, intptr_t, void*) = (intptr_t (WINAPI *)(intptr_t, void*, int32_t, intptr_t, void*))vb6_di_gdiplus_proc("GdipBitmapLockBits");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBitmap, mRect, mFlags, mPixelFormat, mLockedBitmapData);
}

/* GdipBitmapUnlockBits */
intptr_t __stdcall vb6_di_GdipBitmapUnlockBits(intptr_t mBitmap, void* mLockedBitmapData) {
    intptr_t (WINAPI *fn)(intptr_t, void*) = (intptr_t (WINAPI *)(intptr_t, void*))vb6_di_gdiplus_proc("GdipBitmapUnlockBits");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBitmap, mLockedBitmapData);
}

/* GdipClosePathFigure */
intptr_t __stdcall vb6_di_GdipClosePathFigure(intptr_t mpath) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipClosePathFigure");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mpath);
}

/* GdipCreateBitmapFromHBITMAP */
intptr_t __stdcall vb6_di_GdipCreateBitmapFromHBITMAP(intptr_t mHbm, intptr_t mhPal, int32_t* mBitmap) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateBitmapFromHBITMAP");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mHbm, mhPal, mBitmap);
}

/* GdipCreateBitmapFromScan0 */
intptr_t __stdcall vb6_di_GdipCreateBitmapFromScan0(intptr_t mWidth, intptr_t mHeight, intptr_t mStride, intptr_t mPixelFormat, intptr_t mScan0, int32_t* mBitmap) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateBitmapFromScan0");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mWidth, mHeight, mStride, mPixelFormat, mScan0, mBitmap);
}

/* GdipCreateBitmapFromStream */
intptr_t __stdcall vb6_di_GdipCreateBitmapFromStream(intptr_t pStream, int32_t* pBitmap) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateBitmapFromStream");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(pStream, pBitmap);
}

/* GdipCreateFromHDC */
intptr_t __stdcall vb6_di_GdipCreateFromHDC(intptr_t hdc, int32_t* hGraphics) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateFromHDC");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(hdc, hGraphics);
}

/* GdipCreatePath */
intptr_t __stdcall vb6_di_GdipCreatePath(int32_t* mBrushMode, int32_t* mpath) {
    intptr_t (WINAPI *fn)(int32_t*, int32_t*) = (intptr_t (WINAPI *)(int32_t*, int32_t*))vb6_di_gdiplus_proc("GdipCreatePath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mBrushMode, mpath);
}

/* GdipCreatePen1 */
intptr_t __stdcall vb6_di_GdipCreatePen1(intptr_t mColor, float mWidth, intptr_t mUnit, int32_t* mPen) {
    intptr_t (WINAPI *fn)(intptr_t, float, intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, float, intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreatePen1");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mColor, mWidth, mUnit, mPen);
}

/* GdipCreateSolidFill */
intptr_t __stdcall vb6_di_GdipCreateSolidFill(intptr_t argb, int32_t* Brush) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipCreateSolidFill");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(argb, Brush);
}

/* GdipDeleteBrush */
intptr_t __stdcall vb6_di_GdipDeleteBrush(intptr_t Brush) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeleteBrush");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Brush);
}

/* GdipDeleteGraphics */
intptr_t __stdcall vb6_di_GdipDeleteGraphics(intptr_t hGraphics) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeleteGraphics");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(hGraphics);
}

/* GdipDeletePath */
intptr_t __stdcall vb6_di_GdipDeletePath(intptr_t mpath) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeletePath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mpath);
}

/* GdipDeletePen */
intptr_t __stdcall vb6_di_GdipDeletePen(intptr_t mPen) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDeletePen");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mPen);
}

/* GdipDisposeImage */
intptr_t __stdcall vb6_di_GdipDisposeImage(intptr_t pImage) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipDisposeImage");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(pImage);
}

/* GdipDrawImageRectRectI */
intptr_t __stdcall vb6_di_GdipDrawImageRectRectI(intptr_t hGraphics, intptr_t hImage, intptr_t DstX, intptr_t DstY, intptr_t DstWidth, intptr_t DstHeight, intptr_t SrcX, intptr_t SrcY, intptr_t SrcWidth, intptr_t SrcHeight, intptr_t srcUnit, intptr_t imageAttributes, intptr_t Callback, intptr_t callbackData) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawImageRectRectI");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(hGraphics, hImage, DstX, DstY, DstWidth, DstHeight, SrcX, SrcY, SrcWidth, SrcHeight, srcUnit, imageAttributes, Callback, callbackData);
}

/* GdipDrawPath */
intptr_t __stdcall vb6_di_GdipDrawPath(intptr_t mGraphics, intptr_t mPen, intptr_t mpath) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipDrawPath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mPen, mpath);
}

/* GdipFillPath */
intptr_t __stdcall vb6_di_GdipFillPath(intptr_t mGraphics, intptr_t mBrush, intptr_t mpath) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipFillPath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mBrush, mpath);
}

/* GdipGetImageGraphicsContext */
intptr_t __stdcall vb6_di_GdipGetImageGraphicsContext(intptr_t Image, int32_t* hGraphics) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipGetImageGraphicsContext");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Image, hGraphics);
}

/* GdipGetImageHeight */
intptr_t __stdcall vb6_di_GdipGetImageHeight(intptr_t mImage, int32_t* mHeight) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipGetImageHeight");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mImage, mHeight);
}

/* GdipGetImageWidth */
intptr_t __stdcall vb6_di_GdipGetImageWidth(intptr_t mImage, int32_t* mWidth) {
    intptr_t (WINAPI *fn)(intptr_t, int32_t*) = (intptr_t (WINAPI *)(intptr_t, int32_t*))vb6_di_gdiplus_proc("GdipGetImageWidth");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mImage, mWidth);
}

/* GdiplusShutdown */
void __stdcall vb6_di_GdiplusShutdown(intptr_t Token) {
    void (WINAPI *fn)(intptr_t) = (void (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdiplusShutdown");
    if (fn != NULL) { fn(Token); }
}

/* GdiplusStartup */
intptr_t __stdcall vb6_di_GdiplusStartup(int32_t* Token, void* inputBuf, intptr_t outputBuf) {
    intptr_t (WINAPI *fn)(int32_t*, void*, intptr_t) = (intptr_t (WINAPI *)(int32_t*, void*, intptr_t))vb6_di_gdiplus_proc("GdiplusStartup");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(Token, inputBuf, outputBuf);
}

/* GdipResetClip */
intptr_t __stdcall vb6_di_GdipResetClip(intptr_t mGraphics) {
    intptr_t (WINAPI *fn)(intptr_t) = (intptr_t (WINAPI *)(intptr_t))vb6_di_gdiplus_proc("GdipResetClip");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics);
}

/* GdipSetClipHrgn */
intptr_t __stdcall vb6_di_GdipSetClipHrgn(intptr_t mGraphics, intptr_t mHRgn, intptr_t mCombineMode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetClipHrgn");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mHRgn, mCombineMode);
}

/* GdipSetClipPath */
intptr_t __stdcall vb6_di_GdipSetClipPath(intptr_t mGraphics, intptr_t mpath, intptr_t mCombineMode) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetClipPath");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(mGraphics, mpath, mCombineMode);
}

/* GdipSetSmoothingMode */
intptr_t __stdcall vb6_di_GdipSetSmoothingMode(intptr_t graphics, intptr_t SmoothingMd) {
    intptr_t (WINAPI *fn)(intptr_t, intptr_t) = (intptr_t (WINAPI *)(intptr_t, intptr_t))vb6_di_gdiplus_proc("GdipSetSmoothingMode");
    if (fn == NULL) { return (intptr_t)2; /* GpStatus InvalidParameter */ }
    return fn(graphics, SmoothingMd);
}

/* GetAdaptersInfo */
intptr_t __stdcall vb6_di_GetAdaptersInfo(void* lpAdapterInfo, int32_t* lpSize) {
    return ((intptr_t (WINAPI *)(void*, int32_t*))GetAdaptersInfo)(lpAdapterInfo, lpSize);
}

/* GetBkColor */
intptr_t __stdcall vb6_di_GetBkColor(intptr_t hdc) {
    return ((intptr_t (WINAPI *)(intptr_t))GetBkColor)(hdc);
}

/* GetCommMask */
intptr_t __stdcall vb6_di_GetCommMask(intptr_t hFile, int32_t* lpEventMask) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetCommMask)(hFile, lpEventMask);
}

/* GetCommModemStatus */
intptr_t __stdcall vb6_di_GetCommModemStatus(intptr_t hFile, int32_t* lpModemStat) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetCommModemStatus)(hFile, lpModemStat);
}

/* GetCommProperties */
intptr_t __stdcall vb6_di_GetCommProperties(intptr_t hFile, void* lpCommProp) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetCommProperties)(hFile, lpCommProp);
}

/* GetCommState */
intptr_t __stdcall vb6_di_GetCommState(intptr_t hFile, void* lpDCB) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetCommState)(hFile, lpDCB);
}

/* GetCommTimeouts */
intptr_t __stdcall vb6_di_GetCommTimeouts(intptr_t hCommDev, void* lpCommTimeouts) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetCommTimeouts)(hCommDev, lpCommTimeouts);
}

/* GetCurrentProcess */
intptr_t __stdcall vb6_di_GetCurrentProcess() {
    return ((intptr_t (WINAPI *)(void))GetCurrentProcess)();
}

/* GetCurrentProcessId */
intptr_t __stdcall vb6_di_GetCurrentProcessId() {
    return ((intptr_t (WINAPI *)(void))GetCurrentProcessId)();
}

/* GetDC */
intptr_t __stdcall vb6_di_GetDC(intptr_t hwnd) {
    return ((intptr_t (WINAPI *)(intptr_t))GetDC)(hwnd);
}

/* GetExitCodeProcess */
intptr_t __stdcall vb6_di_GetExitCodeProcess(intptr_t hProcess, int32_t* lpExitCode) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetExitCodeProcess)(hProcess, lpExitCode);
}

/* gethostbyname */
intptr_t __stdcall vb6_di_gethostbyname(BSTR sHostName) {
    return ((intptr_t (WINAPI *)(BSTR))gethostbyname)(sHostName);
}

/* gethostname */
intptr_t __stdcall vb6_di_gethostname(BSTR sHostName, intptr_t lNameLen) {
    return ((intptr_t (WINAPI *)(BSTR, intptr_t))gethostname)(sHostName, lNameLen);
}

/* GetIpForwardTable */
intptr_t __stdcall vb6_di_GetIpForwardTable(void* pIpForwardTable, int32_t* pdwSize, intptr_t bOrder) {
    return ((intptr_t (WINAPI *)(void*, int32_t*, intptr_t))GetIpForwardTable)(pIpForwardTable, pdwSize, bOrder);
}

/* GetLastError */
intptr_t __stdcall vb6_di_GetLastError() {
    return ((intptr_t (WINAPI *)(void))GetLastError)();
}

/* GetModuleHandleA */
intptr_t __stdcall vb6_di_GetModuleHandleA(BSTR lpModuleName) {
    return ((intptr_t (WINAPI *)(BSTR))GetModuleHandleA)(lpModuleName);
}

/* GetModuleHandleW */
intptr_t __stdcall vb6_di_GetModuleHandleW(intptr_t lpModuleName) {
    return ((intptr_t (WINAPI *)(intptr_t))GetModuleHandleW)(lpModuleName);
}

/* GetParent */
intptr_t __stdcall vb6_di_GetParent(intptr_t hwnd) {
    return ((intptr_t (WINAPI *)(intptr_t))GetParent)(hwnd);
}

/* getpeername */
intptr_t __stdcall vb6_di_getpeername(intptr_t lSocket, void* uName, int32_t* lpNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, int32_t*))getpeername)(lSocket, uName, lpNameLen);
}

/* GetProcAddress */
intptr_t __stdcall vb6_di_GetProcAddress(intptr_t hModule, BSTR lpProcName) {
    return ((intptr_t (WINAPI *)(intptr_t, BSTR))GetProcAddress)(hModule, lpProcName);
}

/* getsockname */
intptr_t __stdcall vb6_di_getsockname(intptr_t lSocket, void* uName, int32_t* lpNameLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, int32_t*))getsockname)(lSocket, uName, lpNameLen);
}

/* getsockopt */
intptr_t __stdcall vb6_di_getsockopt(intptr_t lSocket, intptr_t lLevel, intptr_t lOptName, void* lpOptVal, int32_t* lpOptLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*, int32_t*))getsockopt)(lSocket, lLevel, lOptName, lpOptVal, lpOptLen);
}

/* GetStdHandle */
intptr_t __stdcall vb6_di_GetStdHandle(intptr_t nStdHandle) {
    return ((intptr_t (WINAPI *)(intptr_t))GetStdHandle)(nStdHandle);
}

/* GetSysColor */
intptr_t __stdcall vb6_di_GetSysColor(intptr_t nIndex) {
    return ((intptr_t (WINAPI *)(intptr_t))GetSysColor)(nIndex);
}

/* GetSystemDefaultLangID */
int16_t __stdcall vb6_di_GetSystemDefaultLangID() {
    return ((int16_t (WINAPI *)(void))GetSystemDefaultLangID)();
}

/* GetSystemTime */
void __stdcall vb6_di_GetSystemTime(void* lpSystemTime) {
    ((void (WINAPI *)(void*))GetSystemTime)(lpSystemTime);
}

/* GetTickCount */
intptr_t __stdcall vb6_di_GetTickCount() {
    return ((intptr_t (WINAPI *)(void))GetTickCount)();
}

/* GetTimeZoneInformation */
intptr_t __stdcall vb6_di_GetTimeZoneInformation(void* utc_lpTimeZoneInformation) {
    return ((intptr_t (WINAPI *)(void*))GetTimeZoneInformation)(utc_lpTimeZoneInformation);
}

/* GetWindowRect */
intptr_t __stdcall vb6_di_GetWindowRect(intptr_t hwnd, void* lpRect) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))GetWindowRect)(hwnd, lpRect);
}

/* GetWindowRgn */
intptr_t __stdcall vb6_di_GetWindowRgn(intptr_t hwnd, intptr_t hRgn) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))GetWindowRgn)(hwnd, hRgn);
}

/* GetWindowThreadProcessId */
intptr_t __stdcall vb6_di_GetWindowThreadProcessId(intptr_t hWnd, int32_t* lpdwProcessId) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*))GetWindowThreadProcessId)(hWnd, lpdwProcessId);
}

/* GlobalAlloc */
intptr_t __stdcall vb6_di_GlobalAlloc(intptr_t wFlags, intptr_t dwBytes) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))GlobalAlloc)(wFlags, dwBytes);
}

/* GlobalFree */
intptr_t __stdcall vb6_di_GlobalFree(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))GlobalFree)(hMem);
}

/* GlobalLock */
intptr_t __stdcall vb6_di_GlobalLock(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))GlobalLock)(hMem);
}

/* GlobalUnlock */
intptr_t __stdcall vb6_di_GlobalUnlock(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))GlobalUnlock)(hMem);
}

/* htonl */
intptr_t __stdcall vb6_di_htonl(intptr_t lHostLong) {
    return ((intptr_t (WINAPI *)(intptr_t))htonl)(lHostLong);
}

/* htons */
int16_t __stdcall vb6_di_htons(intptr_t lHostShort) {
    return ((int16_t (WINAPI *)(intptr_t))htons)(lHostShort);
}

/* inet_addr */
intptr_t __stdcall vb6_di_inet_addr(BSTR sAddr) {
    return ((intptr_t (WINAPI *)(BSTR))inet_addr)(sAddr);
}

/* inet_ntoa */
intptr_t __stdcall vb6_di_inet_ntoa(intptr_t lIn) {
    return ((intptr_t (WINAPI *)(intptr_t))inet_ntoa)(lIn);
}

/* ioctlsocket */
intptr_t __stdcall vb6_di_ioctlsocket(intptr_t lSocket, intptr_t lCmd, int32_t* lpArg) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, int32_t*))ioctlsocket)(lSocket, lCmd, lpArg);
}

/* IsBadCodePtr */
intptr_t __stdcall vb6_di_IsBadCodePtr(intptr_t lpFn) {
    return ((intptr_t (WINAPI *)(intptr_t))IsBadCodePtr)(lpFn);
}

/* IsBadReadPtr */
intptr_t __stdcall vb6_di_IsBadReadPtr(intptr_t lp, intptr_t ucb) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))IsBadReadPtr)(lp, ucb);
}

/* IsWindow */
intptr_t __stdcall vb6_di_IsWindow(intptr_t hWnd) {
    return ((intptr_t (WINAPI *)(intptr_t))IsWindow)(hWnd);
}

/* IsWindowUnicode */
intptr_t __stdcall vb6_di_IsWindowUnicode(intptr_t hWnd) {
    return ((intptr_t (WINAPI *)(intptr_t))IsWindowUnicode)(hWnd);
}

/* keybd_event */
intptr_t __stdcall vb6_di_keybd_event(uint8_t bVk, uint8_t bScan, intptr_t dwFlags, intptr_t dwExtraInfo) {
    return ((intptr_t (WINAPI *)(uint8_t, uint8_t, intptr_t, intptr_t))keybd_event)(bVk, bScan, dwFlags, dwExtraInfo);
}

/* KillTimer */
intptr_t __stdcall vb6_di_KillTimer(intptr_t hWnd, intptr_t nIDEvent) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))KillTimer)(hWnd, nIDEvent);
}

/* listen */
intptr_t __stdcall vb6_di_listen(intptr_t lSocket, intptr_t lBackLog) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))listen)(lSocket, lBackLog);
}

/* LocalFileTimeToFileTime */
intptr_t __stdcall vb6_di_LocalFileTimeToFileTime(void* lpLocalFileTime, void* lpFileTime) {
    return ((intptr_t (WINAPI *)(void*, void*))LocalFileTimeToFileTime)(lpLocalFileTime, lpFileTime);
}

/* LocalFree */
intptr_t __stdcall vb6_di_LocalFree(intptr_t hMem) {
    return ((intptr_t (WINAPI *)(intptr_t))LocalFree)(hMem);
}

/* lstrlenA */
intptr_t __stdcall vb6_di_lstrlenA(intptr_t lpStr) {
    return ((intptr_t (WINAPI *)(intptr_t))lstrlenA)(lpStr);
}

/* lstrlenW */
intptr_t __stdcall vb6_di_lstrlenW(intptr_t lpStr) {
    return ((intptr_t (WINAPI *)(intptr_t))lstrlenW)(lpStr);
}

/* MakeSureDirectoryPathExists */
intptr_t __stdcall vb6_di_MakeSureDirectoryPathExists(BSTR DirPath) {
    return ((intptr_t (WINAPI *)(BSTR))MakeSureDirectoryPathExists)(DirPath);
}

/* MultiByteToWideChar */
intptr_t __stdcall vb6_di_MultiByteToWideChar(intptr_t CodePage, intptr_t dwFlags, void* lpMultiByteStr, intptr_t cchMultiByte, intptr_t lpWideCharStr, intptr_t cchWideChar) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, intptr_t, intptr_t))MultiByteToWideChar)(CodePage, dwFlags, lpMultiByteStr, cchMultiByte, lpWideCharStr, cchWideChar);
}

/* NCryptDecrypt */
intptr_t __stdcall vb6_di_NCryptDecrypt(intptr_t hKey, void* pbInput, intptr_t cbInput, intptr_t pPaddingInfo, void* pbOutput, intptr_t cbOutput, int32_t* pcbResult, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, void*, intptr_t, int32_t*, intptr_t))NCryptDecrypt)(hKey, pbInput, cbInput, pPaddingInfo, pbOutput, cbOutput, pcbResult, dwFlags);
}

/* NCryptFreeObject */
intptr_t __stdcall vb6_di_NCryptFreeObject(intptr_t hKey) {
    return ((intptr_t (WINAPI *)(intptr_t))NCryptFreeObject)(hKey);
}

/* NCryptGetProperty */
intptr_t __stdcall vb6_di_NCryptGetProperty(intptr_t hObject, intptr_t pszProperty, void* pbOutput, intptr_t cbOutput, int32_t* pcbResult, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, int32_t*, intptr_t))NCryptGetProperty)(hObject, pszProperty, pbOutput, cbOutput, pcbResult, dwFlags);
}

/* NCryptOpenKey */
intptr_t __stdcall vb6_di_NCryptOpenKey(intptr_t hProvider, int32_t* phKey, intptr_t pszKeyName, intptr_t dwLegacyKeySpec, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*, intptr_t, intptr_t, intptr_t))NCryptOpenKey)(hProvider, phKey, pszKeyName, dwLegacyKeySpec, dwFlags);
}

/* NCryptOpenStorageProvider */
intptr_t __stdcall vb6_di_NCryptOpenStorageProvider(int32_t* phProvider, intptr_t pszProviderName, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(int32_t*, intptr_t, intptr_t))NCryptOpenStorageProvider)(phProvider, pszProviderName, dwFlags);
}

/* NCryptSignHash */
intptr_t __stdcall vb6_di_NCryptSignHash(intptr_t hKey, intptr_t pPaddingInfo, void* pbHashValue, intptr_t cbHashValue, void* pbSignature, intptr_t cbSignature, int32_t* pcbResult, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, intptr_t, void*, intptr_t, int32_t*, intptr_t))NCryptSignHash)(hKey, pPaddingInfo, pbHashValue, cbHashValue, pbSignature, cbSignature, pcbResult, dwFlags);
}

/* ntohs */
int16_t __stdcall vb6_di_ntohs(intptr_t lNetShort) {
    return ((int16_t (WINAPI *)(intptr_t))ntohs)(lNetShort);
}

/* OffsetRgn */
intptr_t __stdcall vb6_di_OffsetRgn(intptr_t hRgn, intptr_t x, intptr_t y) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))OffsetRgn)(hRgn, x, y);
}

/* OleLoadPicture */
intptr_t __stdcall vb6_di_OleLoadPicture(intptr_t pStream, intptr_t lSize, intptr_t fRunmode, void* riid, void* ppvObj) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*, void*))OleLoadPicture)(pStream, lSize, fRunmode, riid, ppvObj);
}

/* PathMatchSpecW */
intptr_t __stdcall vb6_di_PathMatchSpecW(intptr_t pszFileParam, intptr_t pszSpec) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))PathMatchSpecW)(pszFileParam, pszSpec);
}

/* PeekNamedPipe */
intptr_t __stdcall vb6_di_PeekNamedPipe(intptr_t hNamedPipe, intptr_t lpBuffer, intptr_t nBufferSize, int32_t* lpBytesRead, int32_t* lpTotalBytesAvail, int32_t* lpBytesLeftThisMessage) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*, int32_t*, int32_t*))PeekNamedPipe)(hNamedPipe, lpBuffer, nBufferSize, lpBytesRead, lpTotalBytesAvail, lpBytesLeftThisMessage);
}

/* PFXImportCertStore */
intptr_t __stdcall vb6_di_PFXImportCertStore(void* pPFX, intptr_t szPassword, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(void*, intptr_t, intptr_t))PFXImportCertStore)(pPFX, szPassword, dwFlags);
}

/* PurgeComm */
intptr_t __stdcall vb6_di_PurgeComm(intptr_t hFile, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))PurgeComm)(hFile, dwFlags);
}

/* QueryPerformanceCounter */
intptr_t __stdcall vb6_di_QueryPerformanceCounter(int64_t* lpPerformanceCount) {
    return ((intptr_t (WINAPI *)(int64_t*))QueryPerformanceCounter)(lpPerformanceCount);
}

/* QueryPerformanceFrequency */
intptr_t __stdcall vb6_di_QueryPerformanceFrequency(int64_t* lpFrequency) {
    return ((intptr_t (WINAPI *)(int64_t*))QueryPerformanceFrequency)(lpFrequency);
}

/* ReadFile */
intptr_t __stdcall vb6_di_ReadFile(intptr_t hFile, void* lpBuffer, intptr_t nNumberOfBytesToRead, int32_t* lpNumberOfBytesRead, intptr_t lpOverlapped) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, int32_t*, intptr_t))ReadFile)(hFile, lpBuffer, nNumberOfBytesToRead, lpNumberOfBytesRead, lpOverlapped);
}

/* recv */
intptr_t __stdcall vb6_di_recv(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t))recv)(lSocket, lpBuf, lBufLen, dwFlags);
}

/* recvfrom */
intptr_t __stdcall vb6_di_recvfrom(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags, void* uFrom, int32_t* lpFromLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, void*, int32_t*))recvfrom)(lSocket, lpBuf, lBufLen, dwFlags, uFrom, lpFromLen);
}

/* ReleaseDC */
intptr_t __stdcall vb6_di_ReleaseDC(intptr_t hwnd, intptr_t hdc) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))ReleaseDC)(hwnd, hdc);
}

/* ScreenToClient */
intptr_t __stdcall vb6_di_ScreenToClient(intptr_t hwnd, void* lpPoint) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))ScreenToClient)(hwnd, lpPoint);
}

/* send */
intptr_t __stdcall vb6_di_send(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t))send)(lSocket, lpBuf, lBufLen, dwFlags);
}

/* SendMessageA */
intptr_t __stdcall vb6_di_SendMessageA(intptr_t hWnd, intptr_t wMsg, intptr_t wParam, void* lParam) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*))SendMessageA)(hWnd, wMsg, wParam, lParam);
}

/* SendMessageW */
intptr_t __stdcall vb6_di_SendMessageW(intptr_t hWnd, intptr_t wMsg, intptr_t wParam, void* lParam) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*))SendMessageW)(hWnd, wMsg, wParam, lParam);
}

/* sendto */
intptr_t __stdcall vb6_di_sendto(intptr_t lSocket, void* lpBuf, intptr_t lBufLen, intptr_t dwFlags, void* uTo, intptr_t lToLen) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, intptr_t, void*, intptr_t))sendto)(lSocket, lpBuf, lBufLen, dwFlags, uTo, lToLen);
}

/* SetCommBreak */
intptr_t __stdcall vb6_di_SetCommBreak(intptr_t hFile) {
    return ((intptr_t (WINAPI *)(intptr_t))SetCommBreak)(hFile);
}

/* SetCommMask */
intptr_t __stdcall vb6_di_SetCommMask(intptr_t hFile, intptr_t dwEventMask) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))SetCommMask)(hFile, dwEventMask);
}

/* SetCommState */
intptr_t __stdcall vb6_di_SetCommState(intptr_t hFile, void* lpDCB) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))SetCommState)(hFile, lpDCB);
}

/* SetCommTimeouts */
intptr_t __stdcall vb6_di_SetCommTimeouts(intptr_t hFile, void* lpCommTimeouts) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))SetCommTimeouts)(hFile, lpCommTimeouts);
}

/* SetEndOfFile */
intptr_t __stdcall vb6_di_SetEndOfFile(intptr_t hFile) {
    return ((intptr_t (WINAPI *)(intptr_t))SetEndOfFile)(hFile);
}

/* SetFilePointerEx */
intptr_t __stdcall vb6_di_SetFilePointerEx(intptr_t hFile, int64_t liDistanceToMove, void* lpNewFilePointer, intptr_t dwMoveMethod) {
    return ((intptr_t (WINAPI *)(intptr_t, int64_t, void*, intptr_t))SetFilePointerEx)(hFile, liDistanceToMove, lpNewFilePointer, dwMoveMethod);
}

/* SetFileTime */
intptr_t __stdcall vb6_di_SetFileTime(intptr_t hFile, void* lpCreationTime, void* lpLastAccessTime, void* lpLastWriteTime) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, void*, void*))SetFileTime)(hFile, lpCreationTime, lpLastAccessTime, lpLastWriteTime);
}

/* SetForegroundWindow */
intptr_t __stdcall vb6_di_SetForegroundWindow(intptr_t hWnd) {
    return ((intptr_t (WINAPI *)(intptr_t))SetForegroundWindow)(hWnd);
}

/* SetParent */
intptr_t __stdcall vb6_di_SetParent(intptr_t hWndChild, intptr_t hWndNewParent) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))SetParent)(hWndChild, hWndNewParent);
}

/* SetRect */
intptr_t __stdcall vb6_di_SetRect(void* lpRect, intptr_t X1, intptr_t Y1, intptr_t X2, intptr_t Y2) {
    return ((intptr_t (WINAPI *)(void*, intptr_t, intptr_t, intptr_t, intptr_t))SetRect)(lpRect, X1, Y1, X2, Y2);
}

/* setsockopt */
intptr_t __stdcall vb6_di_setsockopt(intptr_t lSocket, intptr_t lLevel, intptr_t lOptName, void* lpOptVal, intptr_t lOptLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, void*, intptr_t))setsockopt)(lSocket, lLevel, lOptName, lpOptVal, lOptLen);
}

/* SetTimer */
intptr_t __stdcall vb6_di_SetTimer(intptr_t hWnd, intptr_t nIDEvent, intptr_t uElapse, intptr_t lpTimerFunc) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))SetTimer)(hWnd, nIDEvent, uElapse, lpTimerFunc);
}

/* SetupComm */
intptr_t __stdcall vb6_di_SetupComm(intptr_t hFile, intptr_t dwInQueue, intptr_t dwOutQueue) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))SetupComm)(hFile, dwInQueue, dwOutQueue);
}

/* SetWindowLongA */
intptr_t __stdcall vb6_di_SetWindowLongA(intptr_t hwnd, intptr_t nIndex, intptr_t dwNewLong) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))SetWindowLongA)(hwnd, nIndex, dwNewLong);
}

/* SetWindowLongW */
intptr_t __stdcall vb6_di_SetWindowLongW(intptr_t hWnd, intptr_t nIndex, intptr_t dwNewLong) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))SetWindowLongW)(hWnd, nIndex, dwNewLong);
}

/* SetWindowPos */
intptr_t __stdcall vb6_di_SetWindowPos(intptr_t hwnd, intptr_t hWndInsertAfter, intptr_t x, intptr_t y, intptr_t cx, intptr_t cy, intptr_t wFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))SetWindowPos)(hwnd, hWndInsertAfter, x, y, cx, cy, wFlags);
}

/* SHBrowseForFolder */
intptr_t __stdcall vb6_di_SHBrowseForFolder(void* lpbi) {
    return ((intptr_t (WINAPI *)(void*))SHBrowseForFolder)(lpbi);
}

/* SHGetPathFromIDListA */
intptr_t __stdcall vb6_di_SHGetPathFromIDListA(intptr_t pidl, BSTR pszPath) {
    return ((intptr_t (WINAPI *)(intptr_t, BSTR))SHGetPathFromIDListA)(pidl, pszPath);
}

/* ShowWindow */
intptr_t __stdcall vb6_di_ShowWindow(intptr_t hwnd, intptr_t nCmdShow) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))ShowWindow)(hwnd, nCmdShow);
}

/* shutdown */
intptr_t __stdcall vb6_di_shutdown(intptr_t lSocket, intptr_t lHow) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))shutdown)(lSocket, lHow);
}

/* Sleep */
void __stdcall vb6_di_Sleep(intptr_t dwMilliseconds) {
    ((void (WINAPI *)(intptr_t))Sleep)(dwMilliseconds);
}

/* SwitchToThisWindow */
intptr_t __stdcall vb6_di_SwitchToThisWindow(intptr_t hWnd, intptr_t fAltTab) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))SwitchToThisWindow)(hWnd, fAltTab);
}

/* SystemTimeToFileTime */
intptr_t __stdcall vb6_di_SystemTimeToFileTime(void* lpSystemTime, void* lpFileTime) {
    return ((intptr_t (WINAPI *)(void*, void*))SystemTimeToFileTime)(lpSystemTime, lpFileTime);
}

/* SystemTimeToTzSpecificLocalTime */
intptr_t __stdcall vb6_di_SystemTimeToTzSpecificLocalTime(void* utc_lpTimeZoneInformation, void* utc_lpUniversalTime, void* utc_lpLocalTime) {
    return ((intptr_t (WINAPI *)(void*, void*, void*))SystemTimeToTzSpecificLocalTime)(utc_lpTimeZoneInformation, utc_lpUniversalTime, utc_lpLocalTime);
}

/* SystemTimeToVariantTime */
intptr_t __stdcall vb6_di_SystemTimeToVariantTime(void* lpSystemTime, double* pvTime) {
    return ((intptr_t (WINAPI *)(void*, double*))SystemTimeToVariantTime)(lpSystemTime, pvTime);
}

/* timeGetTime */
intptr_t __stdcall vb6_di_timeGetTime() {
    return ((intptr_t (WINAPI *)(void))timeGetTime)();
}

/* TranslateMessage */
intptr_t __stdcall vb6_di_TranslateMessage(void* lpMsg) {
    return ((intptr_t (WINAPI *)(void*))TranslateMessage)(lpMsg);
}

/* TransmitCommChar */
intptr_t __stdcall vb6_di_TransmitCommChar(intptr_t hCommDev, uint8_t cChar) {
    return ((intptr_t (WINAPI *)(intptr_t, uint8_t))TransmitCommChar)(hCommDev, cChar);
}

/* TzSpecificLocalTimeToSystemTime */
intptr_t __stdcall vb6_di_TzSpecificLocalTimeToSystemTime(void* utc_lpTimeZoneInformation, void* utc_lpLocalTime, void* utc_lpUniversalTime) {
    return ((intptr_t (WINAPI *)(void*, void*, void*))TzSpecificLocalTimeToSystemTime)(utc_lpTimeZoneInformation, utc_lpLocalTime, utc_lpUniversalTime);
}

/* UpdateLayeredWindow */
intptr_t __stdcall vb6_di_UpdateLayeredWindow(intptr_t hwnd, intptr_t hdcDst, void* pptDst, void* psize, intptr_t hdcSrc, void* pptSrc, intptr_t crKey, void* pblend, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, void*, void*, intptr_t, void*, intptr_t, void*, intptr_t))UpdateLayeredWindow)(hwnd, hdcDst, pptDst, psize, hdcSrc, pptSrc, crKey, pblend, dwFlags);
}

/* VariantTimeToSystemTime */
intptr_t __stdcall vb6_di_VariantTimeToSystemTime(double vTime, void* lpSystemTime) {
    return ((intptr_t (WINAPI *)(double, void*))VariantTimeToSystemTime)(vTime, lpSystemTime);
}

/* VirtualAlloc */
intptr_t __stdcall vb6_di_VirtualAlloc(intptr_t lpAddress, intptr_t dwSize, intptr_t flAllocationType, intptr_t flProtect) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))VirtualAlloc)(lpAddress, dwSize, flAllocationType, flProtect);
}

/* VirtualFree */
intptr_t __stdcall vb6_di_VirtualFree(intptr_t lpAddress, intptr_t dwSize, intptr_t dwFreeType) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t))VirtualFree)(lpAddress, dwSize, dwFreeType);
}

/* VirtualProtect */
intptr_t __stdcall vb6_di_VirtualProtect(intptr_t lpAddress, intptr_t dwSize, intptr_t flNewProtect, int32_t* lpflOldProtect) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, int32_t*))VirtualProtect)(lpAddress, dwSize, flNewProtect, lpflOldProtect);
}

/* WaitCommEvent */
intptr_t __stdcall vb6_di_WaitCommEvent(intptr_t hFile, int32_t* lpEventMask, void* lpOverlapped) {
    return ((intptr_t (WINAPI *)(intptr_t, int32_t*, void*))WaitCommEvent)(hFile, lpEventMask, lpOverlapped);
}

/* WaitForSingleObject */
intptr_t __stdcall vb6_di_WaitForSingleObject(intptr_t hHandle, intptr_t dwMilliseconds) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t))WaitForSingleObject)(hHandle, dwMilliseconds);
}

/* WriteFile */
intptr_t __stdcall vb6_di_WriteFile(intptr_t hFile, void* lpBuffer, intptr_t nNumberOfBytesToWrite, int32_t* lpNumberOfBytesWritten, intptr_t lpOverlapped) {
    return ((intptr_t (WINAPI *)(intptr_t, void*, intptr_t, int32_t*, intptr_t))WriteFile)(hFile, lpBuffer, nNumberOfBytesToWrite, lpNumberOfBytesWritten, lpOverlapped);
}

/* WSAAsyncGetHostByName */
intptr_t __stdcall vb6_di_WSAAsyncGetHostByName(intptr_t hWnd, intptr_t wMsg, BSTR strHostName, void* lpBuf, intptr_t lBufLen) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, BSTR, void*, intptr_t))WSAAsyncGetHostByName)(hWnd, wMsg, strHostName, lpBuf, lBufLen);
}

/* WSAAsyncSelect */
intptr_t __stdcall vb6_di_WSAAsyncSelect(intptr_t lSocket, intptr_t hWnd, intptr_t wMsg, intptr_t lEvent) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t))WSAAsyncSelect)(lSocket, hWnd, wMsg, lEvent);
}

/* WSACancelAsyncRequest */
intptr_t __stdcall vb6_di_WSACancelAsyncRequest(intptr_t hAsyncTaskHandle) {
    return ((intptr_t (WINAPI *)(intptr_t))WSACancelAsyncRequest)(hAsyncTaskHandle);
}

/* WSACleanup */
intptr_t __stdcall vb6_di_WSACleanup() {
    return ((intptr_t (WINAPI *)(void))WSACleanup)();
}

/* WSASocketW */
intptr_t __stdcall vb6_di_WSASocketW(intptr_t lAf, intptr_t lType, intptr_t lProtocol, intptr_t lpProtocolInfo, intptr_t lGroup, intptr_t dwFlags) {
    return ((intptr_t (WINAPI *)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t))WSASocketW)(lAf, lType, lProtocol, lpProtocolInfo, lGroup, dwFlags);
}

/* WSAStartup */
intptr_t __stdcall vb6_di_WSAStartup(intptr_t wVersionRequired, void* lpWSAData) {
    return ((intptr_t (WINAPI *)(intptr_t, void*))WSAStartup)(wVersionRequired, lpWSAData);
}
